simplesamlphp/simplesamlphp

lib/SimpleSAML/Utilities.php
www/_include.php

To prevent local and remote file inclusion attacks. This is in most cases
already disabled by default in system libraries, so this will be a no-op to
most systems, but to be safe we explicitly disable it also.
Fixes #74

Disable the loading of external entities in XML documents.

---

www/admin/metadata-converter.php

Depending on server configuration this may be used in a Denial Of Service attack by tying up all webserver workers with large POST bodies.

Make sure metadata-converter.php requires an admin user

---

modules/saml/www/sp/metadata.php

This check was not ported to the saml2 module.

protectmetadata was not enforced for SP metadata.

---

lib/SimpleSAML/Auth/Simple.php
lib/SimpleSAML/Metadata/SAMLParser.php
modules/aselect/www/credentials.php

To allow for more focused attribute release it would be useful if the metadata import would preserve which of the requested attributes are required. This patch collects the required attributes into an “attributes.required” element.

Enhance the metadata import to preserve the "required" flag of requested attributes

---

docs/simplesamlphp-reference-sp-remote.txt

Adds documentation on behavior of signature.certificate when signature.privatekey is specified for a service provider.

Add documentation to sp-remote for signature.certificate

---

lib/SimpleSAML/Auth/Default.php
modules/saml/www/sp/saml1-acs.php

Fixed a bug where the subject nameid was not being returned back to the SP after successful authentication.

Bug fix to include the subject nameid in the data returned from a SAML 1.0 SSO authentication.

---

docs/simplesamlphp-automated_metadata.txt
lib/SimpleSAML/Metadata/SAMLParser.php
modules/metarefresh/bin/metarefresh.php
modules/metarefresh/config-templates/config-metarefresh.php
modules/metarefresh/lib/MetaLoader.php

Added the ability to verify the metadata signature with a certificate file. I added the functionality to both the cli and the automatic metarefresh module. It is possible to use more than one certificate to handle key rollover.

Add metadata signature verification by using pub key from certificate

---

modules/saml/lib/Message.php

This patch adds support for the sender-vouches SubjectConfirmation Method, requested in issue #50. 
It also depends on the constant added in https://github.com/simplesamlphp/saml2/pull/41

Add support for sender-vouches

---

modules/metaedit/config-template/module_metaedit.php

this admins array is not used anywhere,
but it may be misleading to administrators who wants to restrict
the access to the metadata registry.
Please consider removing this configure options.

remove misleading and unused config option

---

lib/SimpleSAML/Store.php

Removed a 'if' sentence than prevents a Store class couldn't be added it is named with a namespace instead with the sspmod_module_Store_class way.
I'm writing a module with a new SimpleSAML_Store class using namespaces. When I'm trying to load the class on my config file:
```
'store.type'                    => 'SimpleSAML\Modules\DBAL\Store\DBAL',
```
I get an exception because it expects a string with 'module:class' format. But ```SimpleSAML_Module::resolveClass($storeType, 'Store', 'SimpleSAML_Store');``` is enough to control if a class could be added or not.

Removed a 'if' sentence than prevents a Store class couldn't be added.

---

modules/authX509/dictionaries/X509warning.definition.json
modules/authX509/dictionaries/X509warning.translation.json
modules/authX509/docs/authX509.txt
modules/authX509/lib/Auth/Process/ExpiryWarning.php
modules/authX509/templates/X509warning.php
modules/authX509/www/expirywarning.php

In some simplesamlphp deployments there is a chicken&egg situation where users authenticate at their IDP using a X509 certificate, and apply for certificates at an SP using federated login. When a certificate expires, they are immediately locked out of their account, and are unable to fix this situation. This filter will warn users if their certificate is about to expire, so they can renew their certificate in time.

extend authX509 module with authentication processing filter for generating certificate expiry warnings

---

modules/aselect/docs/aselect.txt
modules/aselect/lib/Auth/Source/aselect.php
modules/aselect/www/credentials.php

uid and organization attributes are not always in `$creds['attributes']`, so we add an option for that.

A-Select: always add uid+organization to attributes

---

lib/SimpleSAML/Configuration.php

This option made it possible to override the configuration per host, but it has never been documented, and it can be replaced with simple PHP code in the configuration.
Closes #2

Remove override.host config variable.

---

config-templates/config.php
lib/SimpleSAML/SessionHandlerPHP.php

It's obviously more secure and therefore better as a default.

Set PHP session cookie configuation to be true by default.

---

lib/SimpleSAML/Utils/HTTP.php

Raise InvalidArgumentException if $retryURL is not a string AND is not null

Corrected logic in checkSessionCookie

---

bin/memcacheSync.php
lib/SimpleSAML/Configuration.php
lib/SimpleSAML/Utils/Config.php
modules/metarefresh/bin/metarefresh.php
modules/statistics/bin/loganalyzer.php
modules/statistics/bin/logcleaner.php
tests/lib/SimpleSAML/Utils/ConfigTest.php
www/_include.php

There is a similar pull request for this feature (I even borrowed the environment variable), but I wanted to try a different approach that makes this a little easier to understand.  The logic for finding the config directory is centralized.
I can make the necessary changes for the manual, but I wanted to put in the pull request and have someone look at it first before I finish it off.  If it looks good I'll finish it off.
For the bin files, the environment variable can be passed via cli like so:
```
SIMPLESAMLPHP_CONFIG_DIR=/home/user/samlconfig php modules/statistics/bin/loganalyzer.php
```

Moved logic pertaining to finding configdir to central location, added ability to set via environment variable

---

modules/saml/docs/nameid.txt
modules/saml/lib/Auth/Process/SQLPersistentNameID.php

SQLPersistentNameID is very conservative about adding entries into the data store, and will only do so in situations where it knows they're explicitly wanted. This is a problem if there are situations where you want it to behave more like other NameID generation filters -- for instance, to create a persistent NameID even if the SP did not explicitly ask for it.
This patch makes it more flexible, whilst still preserving the existing behaviour as the default. It allows you to  override three of the existing checks by means of config booleans.

Make SQLPersistentNameID more flexible

---

lib/SimpleSAML/Auth/LDAP.php

The `makeException` function returns an instantiated object, so the
caller shouldn't also call `new`.

Removed new call before makeException.

---

modules/core/templates/show_metadata.tpl.php

There is a typo in `show_metadata.tpl.php` referencing the key "blacklink" when it is actually "backlink".

Corrected typo in core:show_metadata template

---

composer.json

add sqlite3 as a dev dependency. you might not notice this when running
tests locally otherwise.

sqlite3 tests require the ext-sqlite3 module

---

tests/modules/core/lib/Auth/Process/AttributeLimitTest.php

test core:AttributeLimit - since array can only contain int and string
I can’t raise the non covered constructor exception.

testing of core:AttributeLimit

---

modules/multiauth/lib/Auth/Source/MultiAuth.php

By default, multiauth only stores the selected authentication source for the datastore length, which is 4 hours. The default session length is 8 hours. If you try logging out between the 4 and 8 hour marks, you will get an exception saying "Invalid authentication source during logout".
My fix is to store the auth source until session expiration when it won't be needed anymore.

Fix multiauth selected source timeout

---

modules/negotiate/lib/Auth/Source/Negotiate.php

This fixes:
[Tue Feb 16 13:50:09 2016] [error] [client 10.48.224.4] PHP Warning:  Missing argument 2 for SimpleSAML_Error_AuthSource::__construct(), called in /apps/simplesamlphp-bd-1.14.0/modules/negotiate/lib/Auth/Source/Negotiate.php on line 336 
[Tue Feb 16 13:50:09 2016] [error] [client 10.48.224.4] PHP Notice:  Undefined variable: reason in /apps/simplesamlphp-bd-1.14.0/lib/SimpleSAML/Error/AuthSource.php(31)

Fix missing argument

---

.gitignore
lib/SimpleSAML/Metadata/SAMLParser.php
tests/lib/SimpleSAML/Metadata/SAMLBuilderTest.php
tests/lib/SimpleSAML/Metadata/SAMLParserTest.php

- Add test case
- Fix .gitignore since it ignored all metadata folders
Based on https://github.com/simplesamlphp/simplesamlphp/pull/288#discussion-diff-53787274

Expose RegistrationInfo in parsed metadata

---

lib/SimpleSAML/Metadata/SAMLParser.php
tests/lib/SimpleSAML/Metadata/SAMLParserTest.php

Allow RegistrationInfo to be inherited from parent EntitiesDescriptors.
Based on discussion https://github.com/simplesamlphp/simplesamlphp/pull/335#issuecomment-188178369

RegistrationInfo can be inherited from EntitiesDescriptor

---

attributemap/name2oid.php
attributemap/name2urn.php
attributemap/oid2name.php
attributemap/oid2urn.php
attributemap/urn2name.php
attributemap/urn2oid.php
dictionaries/attributes.definition.json

This adds the attribute mappings for [eduPersonUniqueId](http://software.internet2.edu/eduperson/internet2-mace-dir-eduperson-201310.html#eduPersonUniqueId) (defined in eduPerson 201305).
Should I include the commit for the definition of `attribute_edupersonuniqueid` in this PR or you prefer a separate one?

Add attribute mappings for eduPersonUniqueId

---

modules/negotiate/lib/Auth/Source/Negotiate.php

An empty array shouldn't lead to an aborted logon.
Example when we try to get the 'mail' attribute:
UserA has a value set in the mail-attribute and passes the test -> Negotiate logon succeeds
UserB has an empty mail-attribute and fails the test -> Negotiate logon fails and the user has to log on manually (fallback to LDAP is initiated)

Fix typo + authentication-failure on empty attributes-array

---

dictionaries/login.translation.json

"Vette pech" (fat chance) appears to offend some of our users. The translations for these seem to vary wildly:
* dr: "pas de chance" (no luck)
* de: "Tut uns leid" (we are sorry)
* it, da,... : this part is left out. This is the best option in my opinion.

Crude translation

---

modules/core/www/as_login.php

Sometimes appear in error logs as:
PHP Notice:  Undefined index: ReturnTo in .../modules/core/www/as_login.php on line 9
PHP Notice:  Undefined index: AuthId in .../modules/core/www/as_login.php on line 13

Fix PHP notices "Undefined index" in as_login.php.

---

config-templates/config.php
docs/simplesamlphp-changelog.txt
lib/SimpleSAML/Utils/HTTP.php
tests/lib/SimpleSAML/Utils/HTTPTest.php

Allow regular expression matching of trusted.url.domains.

---

docs/simplesamlphp-install.md

* Add an extra apache access control directive
to make it work with newer Apaches
Source: http://stackoverflow.com/questions/23337446/getting-a-403-forbidden-error-for-simplesaml-after-apache-upgrade

docs: make it work with Apache 2.4

---

modules/core/docs/authproc_scopeattribute.md
modules/core/lib/Auth/Process/ScopeAttribute.php
tests/modules/core/lib/Auth/Process/ScopeAttributeTest.php

This makes the filter a little more useful for people who want to generate default values from another attribute only if none already exist (for instance, you want to create eduPersonScopedAffiliation from eduPersonAffiliation _only_ if eduPersonScopedAffiliation was not returned by the authenticaton source.)
The option defaults to false, thus preserving the existing behavior.

Add an onlyIfEmpty option to core:ScopeAttribute.

---

attributemap/windowslive2name.php
config-templates/authsources.php
modules/authwindowslive/lib/Auth/Source/LiveID.php
modules/authwindowslive/www/linkback.php

Microsoft's support for OAuth WRAP has been discontinued, and the old consent.live.com endpoints no longer exist. Whilst there are now probably other ways to connect to a Microsoft Account/Windows Live ID, it may be useful for some to use the new OAuth 2.0 model.
Attributes are now retrieved from the user's profile using the newer Microsoft Graph API rather than the Messenger API. This required additions to the windowslive2name attribute map, but I've preserved the existing ones for anyone who's using this map for something else.
This was done mainly as an exercise in understanding social bridges. Whilst it does work properly, I've only tried limited test cases and the code could probably stand to be improved. However, the previous version doesn't work at all any more - consent.live.com …

Update the authwindowslive:LiveID module to use OAuth 2.0 authorization

---

lib/SimpleSAML/Utils/XML.php

An unnecessary exception has been imported by mistake.

Removed unnecessary exception

---

modules/ldap/lib/Auth/Process/BaseFilter.php

The base class for the LDAP auth process filters doesn't fetch the LDAP port from the auth source configuration. This causes a "Can't connect to LDAP server" type error when using an LDAP server (or tunnel) with a port other than the default 389.

Added port to the LDAP base filter configuration

---

config-templates/authsources.php
modules/authfacebook/lib/Auth/Source/Facebook.php

As of Facebook Graph API v2.4, the returned user object only contains the `id` and `name`. As a result you need to specify in the request url which additional fields you want the API to return. Effectively, the `/{user-id}` call should become `/{user-id}?fields=email,first_name,etc..`.
This PR adds the `user_fields` option to the authfacebook module configuration:
```
/**
* A comma-separated list of user profile fields to request.
*
* Note that some user fields require appropriate permissions. For
* example, to retrieve the user's primary email address, "email" must
* be specified in both the req_perms and the user_fields parameter.
*
* When empty, only the app-specific user id and name will be returned.
*
* See the Graph API specification for all available user fields:
* …
```

Fix issue with Facebook authentication retrieving only user id and name

---

config-templates/config.php
templates/includes/header.php

The Afrikaans translation is complete enough that end-user facing parts of SimpleSAMLphp can use it. This will allow South African users to make use of the translation (indeed, find out it exists) without having to edit code.

Add the existing Afrikaans translation into the list of supported languages

---

modules/saml/docs/sp.md
modules/saml/lib/Auth/Source/SP.php
tests/modules/core/lib/Auth/Source/Auth_Source_SP_Test.php

Hi Jamie,
As you suggested in https://github.com/simplesamlphp/simplesamlphp/pull/400 I worked on some tests for sspmod_saml_Auth_Source_SP to test the "saml:NameID" parameter.
It took a few tries to to find a way to test the code where I made changes. I ended up creating a wrapper around sspmod_saml_Auth_Source_SP so I could just test the private sspmod_saml_Auth_Source_SP::startSSO2() function. By overriding sspmod_saml_Auth_Source_SP::sendSAML2AuthnRequest() the result can be captured, using an exception to prevent running into the assert(FALSE) in https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/saml/lib/Auth/Source/SP.php#L280
It would be nice to be able to test though the public interface like, https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/saml/ …

Test for https://github.com/simplesamlphp/simplesamlphp/pull/400

---

modules/saml/docs/sp.md
modules/saml/lib/Auth/Source/SP.php

Add "saml:NameID" option for use with SimpleSAML_Auth_Simple that allows the Subject NameID to be set in a SAML AuthnRequest.

Allow the optional Subject NameID to be set in a SAML AuthnRequest

---

.travis.yml
TESTING.md
composer.json
composer.lock

Update test notes to point to the 4.8 documentation and describe
how to run an old version of phpunit from composer's bin dir.

Update to phpunit 4.8. Last version with php 5.3 support

---

config-templates/authsources.php
modules/authlinkedin/docs/oauthlinkedin.md
modules/authlinkedin/lib/Auth/Source/LinkedIn.php

- Attributes which can be get from LinkedIn are now configurable
- By default these attributes are requested: id,first-name,last-name,headline,summary,specialties,picture-url,email-address
- Added email-address attribute into the default set
- Fixed link to the documentation

Configurable LinkedIn attributes

---

.travis.yml

The segfault happens in the coverage report. Since we send coverage
info only with PHP 5.6, avoid running it entirely, saves buildtime aswell.

Avoid travis segfaulting phpunit withn PHP 5.3

---

config-templates/config.php

The search and replace in https://github.com/simplesamlphp/simplesamlphp/commit/f25c7815af52a751cb815709ff33abee14e130a4 was a bit overzealous and should not have changed the documentation for this variable, since the default value is still (lowercase) simpleSAMLphp.
See the actual default value here:
https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Store/Memcache.php#L26

Fixed incorrect memcache_store prefix docs.

---

lib/SimpleSAML/Metadata/SAMLParser.php

While parsing the XML metadata file of SP, attributes in AttributeConsumerService marked as required where added multiple times causing duplication of attribute keys in `attributes.required` section.

Fix required attributes duplication

---

modules/ldap/docs/ldap.txt
modules/ldap/lib/Auth/Process/AttributeAddUsersGroups.php

This lines make it possible that the group membership information from an OpenLDAP server can be added as authproc filter. The example is more generally and should work for a basic OpenLDAP setup (at least it is compatbile with our 4 different OpenLDAP servers). It works for us (we use it) but we can't support it.

Added OpenLDAP case for UserGroups

---

config-templates/config.php
lib/SimpleSAML/Locale/Language.php

There are config options that allow the session cookie to be secured, but there are no equivalent options for the language cookie. As a result it is not possible to secure the language cookie.
Whilst it might be desirable to have a cookie containing language preference more widely accessible, some people may wish to lock down the cookie -- particularly where they are implementing policies like HSTS. Having an insecure cookie triggers a flag in audits of HSTS.
This change adds two additional config options allowing the language cookie to be secured. The default of serving an insecure cookie remains unchanged, meaning the change should not affect existing installs.

Allow the language cookie to be secured

---

composer.json
docs/simplesamlphp-reference-idp-hosted.md
lib/SimpleSAML/Metadata/SAMLBuilder.php
lib/SimpleSAML/Utils/Config/Metadata.php
tests/lib/SimpleSAML/Utils/Config/MetadataTest.php

This will allow you to configure an attributes array on contact definitions for trust frameworks such as SIRTFI. This is a continuation from the simplesamlphp/saml2 pull [#79](https://github.com/simplesamlphp/saml2/pull/79).
I thought about having a SIRTFI class that could be included onto the contact person element, but I couldn't think of a clean way of adding it on, but I am open to discussion about that. There are also some todo's on the addContact function that I decided was out of scope for this PR that would have to be addressed if I went down the route of having a separate class for SIRTFI.
Also, saml2 doesn't have a new tag with the updated PR that I submitted there, so I've simply updated the commit hash in the composer config. That can be fixed whenever a new tag is created …

Add ability to define additional attributes on ContactPerson element

---

lib/SimpleSAML/Memcache.php

The exception was never raised because $stats will be array('server' => false) on failure instead of just false.
This eventually led to $ret being NULL when one of the servers is down..
Because of this NULL-value, it also led to an empty memcacheMonitor screen.

Raise exception when memcache-server is down

---

config-templates/authsources.php

Generating <md:RequestedAttribute .../> entries in the xml export format for SPs requires 'name' to be set for the authsource in question, however this is not apparent from the documentation or example use of 'attributes' and 'attributes.required' in the authsources config template.

Slight improvement of documentation in authsources config template

---

README.md

The build status buttons are broken. When clicked, they simply point to their own image. The link where the results can be checked are behind the button.
This is simply fixed by removing newlines in the button code, as GitHub markdown doesn't seem to parse it correctly.

docs: Fix the build status buttons

---

modules/authfacebook/extlibinc/base_facebook.php

As of March 27 Facebook has deprecated their V2.2 API, and have change the response format from their access token endpoint from being URL encoded to JSON encoded.
> [Oauth Access Token] Format - The response format of https://www.facebook.com/v2.3/oauth/access_token returned when you exchange a code for an access_token now return valid JSON instead of being URL encoded. The new format of this response is {"access_token": {TOKEN}, "token_type":{TYPE}, "expires_in":{TIME}}. We made this update to be compliant with section 5.1 of RFC 6749.

facebook oauth response format changed

---

lib/SimpleSAML/Utils/Crypto.php
tests/lib/SimpleSAML/Utils/CryptoTest.php

Hey all! I'm back with some more tests.
This also required adding an additional argument to `SimpleSAML\Utils\Crypto::loadPrivateKey` to ease in testing. Without this additional argument, `SimpleSAML_Configuration::getBaseDir` eventually gets called to determine the private key location.  This doesn't work well with `vfsstream`. This argument shouldn't cause too much trouble, and seems cohesive enough with the function's purpose.

Added tests for SimpleSAML\Utils\Crypto

---

docs/simplesamlphp-modules.md

Fixed a small typo (`du` -> `do`), wrapped long lines around column 72 (to match existing line wraps in the file), and reduced some unneeded extra spaces between words.

docs: Improve raw simplesamlphp-modules.md

---

docs/simplesamlphp-theming.md

I didn't find a proper doc for how to create the URLs for my custom theme, thus looked into other modules.
To make things easier for other people I added the necessary documentation bits.
Would be glad if you could merge this. Happy to make changes to my PR on your request.

Extend theming documentation about resource referencing

---

composer.lock

I believe #592 broke unit tests by adding a dev-dependency to `composer.json` but forgot to update `composer.lock`. Therefore, `composer install` does not install all the necessary dependencies for tests.

Update composer.lock with vfsStream dev-dependency

---

modules/core/docs/authproc_attributecopy.md
modules/core/lib/Auth/Process/AttributeCopy.php
tests/modules/core/lib/Auth/Process/AttributeCopyTest.php

Just like with AttributeMap you can specify a string or array as the destination:
```
50 => array(
'class' => 'core:AttributeCopy',
'sn' => 'urn:mace:dir:attribute-def:sn',
'cn' => array('urn:mace:dir:attribute-def:cn','urn:mace:dir:attribute-def:diplayName')
),
```

feature: AttributeCopy can take array for an attribute

---

modules/discopower/www/js/suggest.js

When IdP has e.g. acronym in the name covered by () or there is dash in the name, then the current suggest algorithm doesn't split the name correctly, so disco doesn't show the name of the organization when you type the acronym or something which is in brackets.

Disco suggest algorithm accepts also -_() characters

---

modules/saml/lib/SP/LogoutStore.php

Fixes #579.
According to [RFC1035 3.1](https://tools.ietf.org/html/rfc1035#section-3.1) and [RFC 2181 11](https://tools.ietf.org/html/rfc2181#section-11), domain names can be up to 255 in size.

FQDN can be up to 255 chars according to RFC1035 3.1

---

lib/SimpleSAML/Utils/System.php

When opcache.validate_timestamps is disabled, then the new metadata will not be read after a metarefresh. This can be solved by adding the metadata file to an opcache blacklist, but calling opcache_invalidate() after writing a file is a nice out-of-the-box solution.
Hopefully, this will enable everybody that is using simplesamlphp to disable opcache.validate_timestamps without running into problems.

Invalidate opcache after writing a file

---

modules/ldap/lib/Auth/Process/BaseFilter.php
tests/modules/ldap/lib/Auth/Process/BaseFilterTest.php

Remove `ldap.password` from being logged, and hide the length of the password in all instances.

Remove sensitive data from logs during LDAP filters

---

lib/SimpleSAML/Metadata/SAMLBuilder.php
tests/lib/SimpleSAML/Metadata/SAMLBuilderTest.php

When there is no `protocols` in `attributeauthority-remote` metadata, the generated xml by SAMLBuilder contains `AttributeAuthorityDescriptor` tag with protocolSupportEnumeration attribute with empty string. 
Shibboleth SPs ignore these entities.

SAMLBuilder AttributeAuthorityDescriptor empty protocolSupportEnumeration

---

modules/core/www/frontpage_federation.php

The exceptions were simply swallowed when something failed during
the lookups. This commit adds some logs to ease debugging.

added exception logging for federation lookups

---

modules/authX509/www/expirywarning.php
modules/authYubiKey/www/yubikeylogin.php

Hi,
I was trying out YubiKey Auth with master when I hit this bug caused by a typo in the core ErrorCodes classname. Grepping the codebase I found another incidence in authX509 where it checks cert expiry. This PR fixes these typos.
Thanks,
Greg

Class name typo causes fatals on some pages

---

modules/core/www/frontpage_config.php

Fixes:
Aug  8 20:44:18 simplesamlphp-2 IDP-MOO[3845]: 3 [d01bee1f99] SimpleSAML_Error_Exception: Error 8 - Undefined index: required
Aug  8 20:44:18 simplesamlphp-2 IDP-MOO[3845]: 3 [d01bee1f99] Backtrace:
Aug  8 20:44:18 simplesamlphp-2 IDP-MOO[3845]: 3 [d01bee1f99] 4 /apps/simplesamlphp/simplesamlphp/www/_include.php:86 (SimpleSAML_error_handler)
Aug  8 20:44:18 simplesamlphp-2 IDP-MOO[3845]: 3 [d01bee1f99] 3 /apps/simplesamlphp/simplesamlphp/modules/core/templates/frontpage_config.tpl.php:91 (require)
Aug  8 20:44:18 simplesamlphp-2 IDP-MOO[3845]: 3 [d01bee1f99] 2 /apps/simplesamlphp/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:405 (SimpleSAML_XHTML_Template::show)
Aug  8 20:44:18 simplesamlphp-2 IDP-MOO[3845]: 3 [d01bee1f99] 1 …

Add missing 'required' value

---

www/admin/metadata-converter.php

Converting XML metadata to PHP on `/admin/metadata-converter.php` will fail when the XML contains leading whitespace.
Annoying some browsers seem to add an empty line when copy/pasting, so this error occurs regularly.
Trimming the xmldata fixes this.

Fix XML validation failure with leading/trailing whitespace

---

modules/adfs/docs/adfs.md
modules/adfs/lib/IdP/ADFS.php

Without proper enctype, every space in $wresult will be converted to a +
I really wonder if this ever worked at all..

ADFS-module: Set enctype on post-form

---

templates/post.php
www/resources/post.css
www/resources/post.js

See issue #593 for a problem description.
SimpleSamlPHP makes use of unsafe inline Javascript and CSS elements.
Although most generated HTML uses SimpleSamlPHP's own headers, the
keepPost option in an authentication request uses the headers of
the PHP application it is sent from. This forces web applications
using SimpleSamlPHP to allow 'unsafe-inline' in their Content
Security Policy.
This commit fixes this issue for the keepPost page ''only'', to
allow PHP applications using SimpleSamlPHP to use a more strict
Content Security Policy. This does not take away from possible
XSS vulnerabilities in other parts of SimpleSamlPHP
In accordance with the coding standards in CONTRIBUTE.md, all tabs in templates/post.php have been replaced by four spaces as well.
One unit test fails:
There was 1 …

Make POST template compatible with CSP

---

lib/SimpleSAML/Auth/LDAP.php

I have been maintaining the PHP LDAP EXOP patch for a few years,
which include the ldapwhoami() function. This has finally made its
way into PHP distribution and will be available in PHP 7.3, but
with a modified prototype.
This changes adapts to this API change. While there, also update
exception handling on par with recent SimpleSAMLphp code

Update PHP API change gor ldapwhoami

---

modules/adfs/lib/IdP/ADFS.php
modules/adfs/lib/SAML2/XML/fed/Const.php
modules/adfs/lib/SAML2/XML/fed/Endpoint.php
modules/adfs/lib/SAML2/XML/fed/SecurityTokenServiceType.php
modules/adfs/lib/SAML2/XML/fed/TokenTypesOffered.php
modules/adfs/lib/XMLSecurityDSig.php
modules/adfs/www/idp/prp.php

I intentionally skipped whitespace-fixes, since there's a separate issue 458 for that.

PSR-2 fix for ADFS module

---

composer.json

Looks like PHP 5.3 support was finally dropped! However it also looks like a spot was missed in the update :)

Remove PHP 5.3 support from composer configuration

---

docs/simplesamlphp-automated_metadata.md
modules/cron/docs/cron.md

@thijskh I opted to do the cron documentation as a separate PR and then I can update PR-685 to document the new features once this is merge.
I was unsure how to build the documentation to verify that the links from `automated metadata` to `cron` were correct.

Document cron module

---

lib/SimpleSAML/Utils/Attributes.php
modules/adfs/lib/IdP/ADFS.php

It doesn't make much sense to have a hard coded AttributeNamespace used for every attribute...
It is a mandatory field in SAML1.1, so we keep the hard coded value as a fallback.
This will convert an attribute called http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress to:
<saml:Attribute AttributeNamespace="http://schemas.xmlsoap.org/ws/2005/05/identity/claims" AttributeName="emailaddress">

Flexible namespace

---

config-templates/config.php

Hi,
I just cloned SimpleSAMLphp and configured it right out of the box to use memcached for sessions, but as soon as I set store type to 'memcache' I got this error:
> Fatal error: Uncaught Exception: /vagrant/www/libraries/simplesamlphp/config/config.php: The option 'memcache_store.prefix' is not a valid string value. in /vagrant/www/libraries/simplesamlphp/lib/SimpleSAML/Configuration.php on line 604
If this is just an empty string in the default config instead of null then there's no out of the box error for novice users to try and figure out if they set the application to use memcache. :-)
Thanks,
Greg

Using null as memcache prefix in default config causes fatal error.

---

modules/cron/bin/cron.php
modules/cron/docs/cron.md
modules/cron/lib/Cron.php
modules/cron/www/cron.php

Make it easier to run SSP cron functionality from CLI.
This allows setting memory_limit and max_execution_time values that are appropriate for cron functionality that you don't wanted enabled for the all requests.
For tests, I'm currently blocked on getting module enabled during testing. See discussion https://groups.google.com/forum/#!topic/simplesamlphp-dev/hqh7VlSSzhw

Allow CLI invocation of Cron

---

modules/saml/lib/Auth/Source/SP.php

Sometimes there are issues with the metadata itself (e.g metadata
expired). These issues cannot be easily determined, due to the
Exception messages being dropped. In these cases, the current 'not
found' message can be ambiguous.

getIdpMetadata: add more debug logging

---

modules/saml/www/sp/saml2-acs.php

The authnInstant is not being set in the saml2-acs.php. Therefore it isn't available for review or usage in auth proc filters, etc.

SAML2-SP: Making the AuthnInstant available in the state array

---

docs/simplesamlphp-sp.md

I was reading the docs and this typo caught my eye.
Hence this PR.

Fix typo in docs/simplesamlphp-sp.md

---

tests/lib/SimpleSAML/XML/ValidatorTest.php

Hey all,
Validator is another security-critical piece of SSP, so let's test it!
These tests exercise most of the behavior in the module, however I couldn't find a good way to test certificate validation against a CA. Unfortunately `validateCertificate` relies on a CA file on the actual filesystem, and neither `validateCAExec` nor `validateCABuiltIn` play nicely with `vfsstream`. Maybe we can find an efficient way to test this functionality in the future.
`testIsNodeValidatedFailure` should also confirm that the fix from https://simplesamlphp.org/security/201710-01 is working :)

Added tests for SimpleSAML\XML\Validator

---

lib/SimpleSAML/Store/Redis.php
tests/lib/SimpleSAML/Store/RedisTest.php

Fixes the following error when using the Redis Store:
```SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
Backtrace:
1 www/_include.php:45 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: SimpleSAML_Error_Exception: Received duplicate assertion.
Backtrace:
1 modules/saml/www/sp/saml2-acs.php:150 (require)
0 www/module.php:135 (N/A)
```

Fix duplicate assertion error using Redis Store

---

modules/ldap/docs/ldap.md
modules/ldap/lib/Auth/Process/AttributeAddUsersGroups.php

The OPENLDAP option uses hardcoded uid to search for. It should instead use the value of attribute.username. This means it also changes the default since attribute.username defaults to samAccountName. So update the docs to make the example work again. Has not been in a release yet so should not break existing installations.

Bugfix: ldap:AttributeAddUsersGroups ignored the attribute.username setting for OPENLDAP.

---

modules/statistics/lib/Graph/GoogleCharts.php

Prevent graph from being blocked because of mixed content.
https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content?utm_campaign=default&utm_medium=firefox-console-errors&utm_source=mozilla

Statistics: use secure endpoint

---

tests/modules/core/lib/Auth/Process/AttributeMapTest.php

Added some tests for `sspmod_core_Auth_Process_AttributeMap`!
I managed to get just about everything but the `loadMapFile` functionality. That function was difficult to test without any modifications to the library. The module and config path functionality ends up returning full filesystem paths which doesn't play well with `vfsstream`, and unfortunately there's no way to mock out the path value. Regardless, this is better than nothing, and maybe we can find a way to test the map file in the future :)

Added tests for sspmod_core_Auth_Process_AttributeMap

---

lib/SimpleSAML/Metadata/Sources/MDQ.php
lib/SimpleSAML/Utils/HTTP.php

Don't bail out if the MDQ cache is broken or the query fails, because
later other metadata sources might provide the metadata for the entity.

Make MDQ more robust on errors (fixes #723)

---

modules/saml/lib/Auth/Process/NameIDAttribute.php
tests/modules/saml/lib/Auth/Process/NameIDAttributeTest.php

This patch fixes the following error when attempting to use NameIDAttribute filter (https://simplesamlphp.org/docs/1.15/saml:nameidattribute):
```SimpleSAML_Error_Exception: Error 1 - Cannot use object of type SAML2\XML\saml\NameID as array```

NameIDAttribute filter: update to use SAML2\XML\saml\NameID

---

lib/SimpleSAML/Utils/HTTP.php

With the release of Google Chrome version 63, we started noticing that the 302 redirect to the Identity Provider was being served from disk cache randomly.  This caused a stale request condition at the Shibboleth Identity Provider.
By adding 'no-store' to the cache-control header, Google Chrome will no longer be able to store the 302 response in the local disk cache.
We will most likely be patching this on our production system, but would greatly appreciate it if this could be merged in so we can go back to having a clean install.
Regards,
Luke

Add 'no-store' to the cache-control header

---

docs/simplesamlphp-ecp-idp.txt
docs/simplesamlphp-reference-idp-hosted.md
modules/core/lib/Auth/UserPassBase.php
modules/saml/lib/IdP/SAML2.php
tests/modules/core/lib/Auth/UserPassBaseTest.php
tests/modules/saml/lib/IdP/SAML2Test.php
www/saml2/idp/metadata.php

This is my attempt to fix, clean up, and complete #233.
This has been tested against Exchange Online. It is missing a `composer.lock` update for the simplesamlphp/saml2#96.

Add IdP support for ECP profile

---

modules/core/docs/authproc_statisticswithattribute.md
modules/core/lib/Auth/Process/StatisticsWithAttribute.php

At the moment, the consentAdmin module generates a lot of spurious saml20-idp-SSO logs as it passes passively through the authproc filters to determine its attribute set. This has the potential to badly skew any statistics of login attempts, such as those generated by the statistics module. Because the passive state is not logged, there's no way to differentiate those generated passively from a genuine login.
This patch causes the StatisticsWithAttribute filter to be skipped when we have a passive request.

Skip logging statistics when we have a passive request

---

lib/SimpleSAML/Store/SQL.php
tests/lib/SimpleSAML/Store/SQLTest.php

Declaration of kvstore _expires field was defaulting to current timestamp in MySQL.
Added mini upgrade script to kvstore init method to add default null value.
This could have been fixed by changing the declaration of the _expire field in the kv store to `_expire TIMESTAMP NULL` but that would not have fixed existing installations.

MySQL key value store now handles NULL expiries.

---

modules/authfacebook/extlibinc/base_facebook.php
modules/authfacebook/lib/Auth/Source/Facebook.php
modules/authfacebook/lib/Facebook.php
modules/authfacebook/www/linkback.php

Per https://developers.facebook.com/docs/facebook-login/security/#strict_mode the
`state` parameter should be used for any state needed after the redirect, and the
redirect URI should remain constant.

authfacebook compatability with Facebook strict URI match

---

config-templates/config.php
docs/simplesamlphp-customauth.md
lib/SimpleSAML/Store/SQL.php
modules/consent/lib/Consent/Store/Database.php
modules/sqlauth/lib/Auth/Source/SQL.php

I may be missing something but I haven't found a way to add the --ssl-ca
MySQL option to my database connection. It appears we just need to pass
in an $options param.

Add PDO $options support

---

lib/SimpleSAML/Utils/HTTP.php
tests/lib/SimpleSAML/Utils/HTTPTest.php

As per mailinglist-discussion:
https://groups.google.com/forum/#!topic/simplesamlphp-dev/sGTsDkDroLE
Also fixes edge-case situation where $_SERVER['SERVER_PORT'] is not set for an HTTPS connection, this function would return an explicit port 80 i.e. ":80" rather than an empty string.

rewrite getServerPort

---

modules/ldap/lib/Auth/Process/AttributeAddUsersGroups.php

There's no need to call another search if a group is not a member of any other groups. At present, if it's not, it'll just throw an assertion.

Prevent an assert by only calling a sub-search if needed

---

modules/consent/lib/Auth/Process/Consent.php
tests/modules/consent/lib/Auth/Process/ConsentTest.php

Fixes simplesamlphp/simplesamlphp#39
This ensures that the attribute hash is the same if the order of the attribute values changes. A user
givers consent to the values, not the order.

Sort attribute values for consent

---

modules/core/docs/authproc_scopefromattribute.md

Change the source attribute to `eduPersonPrincipalName` and add missing commas.

Fix example in the ScopeFromAttribute doc

---

lib/SimpleSAML/Session.php

Fixes that the configured cookie settings are not correctly set for the auth token cookie when remember-me mechanism is enabled and checked.
Cookie ends up getting set with the default params in `HTTP::setCookie`  
https://github.com/simplesamlphp/simplesamlphp/blob/a5437da2dbbb8dc6348cac02dc343c03bc7f3e14/lib/SimpleSAML/Utils/HTTP.php#L1114-L1120

Fix missing cookie params in authtoken cookie when using remember-me mechanism

---

lib/SimpleSAML/Utils/HTTP.php

Just tried this: our proxy denied login because it could not parse the auth data. Adding a space fixed this.
Will also make a PR for master.

space is required before authentication data

---

lib/SimpleSAML/Error/Assertion.php
lib/SimpleSAML/Error/AuthSource.php
lib/SimpleSAML/Error/BadRequest.php
lib/SimpleSAML/Error/BadUserInnput.php
lib/SimpleSAML/Error/CannotSetCookie.php
lib/SimpleSAML/Error/ConfigurationError.php
lib/SimpleSAML/Error/CriticalConfigurationError.php
lib/SimpleSAML/Error/Exception.php
lib/SimpleSAML/Error/InvalidCredential.php
lib/SimpleSAML/Error/MetadataNotFound.php
lib/SimpleSAML/Error/NoPassive.php
lib/SimpleSAML/Error/NoState.php
lib/SimpleSAML/Error/NotFound.php
lib/SimpleSAML/Error/ProxyCountExceeded.php
lib/SimpleSAML/Error/UnserializableException.php
lib/SimpleSAML/Error/User.php
lib/SimpleSAML/Error/UserAborted.php
lib/SimpleSAML/Error/UserNotFound.php

For #458.
Accomplished via: `phpcbf -n --standard=PSR2 lib/SimpleSAML/Error/`

PSR-2 compliant whitespace in error classes

---

docs/simplesamlphp-theming.md
docs/simplesamlphp-upgrade-notes-1.15.md

Version 1.15 introduces a new templating system based on Twig, but the theming documentation has not been updated to reflect how this works. There is at least one module (sanitycheck) that only uses Twig templates, so custom themes need to be updated or that module is not themed. This problem will increase as more modules switch to Twig.
This is an attempt to reverse engineer some of that, and provide some stub documentation. It could probably stand to be improved by people more in the know :)

Document the new Twig templating system

---

config-templates/config.php

This is minor, but if a comma is required when this is enabled the template should reflect that.

Updated config.php template to include comma after baseURL

---

lib/SimpleSAML/Database.php

The use of count function is wrong and unnecessary. 
```
if (count($slaves >= 1)) {
```
should be
```
if (count($slaves) >= 1) {
```
In PHP7.2 this cause an error because `count` check than the parameter must be a `Countable` object or an array.
Anyway, if the array is empty the foreach loop will not run so I remove it.

Fix count slave checking

---

lib/SimpleSAML/Auth/LDAP.php

In case of ADAzure synchronization, the main attribute used is ms-ds-consistencyguid.
It need to be Base64 encode.

[FIX] ms-ds-consistencyguid need also to be Base64 encode

---

config-templates/config.php

Without setting `LC_CTYPE=C` on a Mac, the salt generation command throws an "Illegal byte sequence" error (most probably the `tr` command thinks the input is invalid UTF-8, which might be correct). This PR fixes this problem, and it should not cause any harm on other systems as the C locale should be available just about everywhere.

Add Mac support to salt generation command

---

docs/simplesamlphp-reference-idp-remote.md

Per https://groups.google.com/d/msg/simplesamlphp/ATKQksysR5s/3VhjdLbTAgAJ
there is a feature to allow IdPs to respond to requests sent to different
IdP entityIDs.

Document IDPList option on saml20-idp-remote.php

---

lib/SimpleSAML/Metadata/MetaDataStorageHandlerXML.php
tests/lib/SimpleSAML/Metadata/MetaDataStorageSourceTest.php

Make the XML metadata storage source support loading from a supplied XML string, rather than necessarily opening/fetching a file.
Useful when generating configuration dynamically, as it allows the XML to be passed at that point, rather than having another abstraction to load it.

Support metadataxml in config

---

modules/core/dictionaries/cardinality.definition.json
modules/core/dictionaries/cardinality.translation.json
modules/core/docs/authproc_cardinality.md
modules/core/docs/authproc_cardinalitysingle.md
modules/core/lib/Auth/Process/Cardinality.php
modules/core/lib/Auth/Process/CardinalitySingle.php
modules/core/templates/cardinality_error.tpl.php
modules/core/www/cardinality_error.php
tests/modules/core/lib/Auth/Process/CardinalitySingleTest.php
tests/modules/core/lib/Auth/Process/CardinalityTest.php

Attribute schemas often have specific requirements for the number of
values a particular attribute may have, and violating the cardinality
rules associated with these may have unexpected and undesirable results.
The two authproc filters this change introduces allow the cardinality of
attributes to be tested. core:Cardinality is the more general case, and
allows for both a minimum and maximum number of values to be tested.
Processing will abort with an error if too few or too many are received.
core:CardinalitySingle is a special case of this for single-valued
attributes, and allows various corrective actions to be taken rather
than aborting. This allows for cardinality mistakes to be "fixed" in a
predictable way, and can also be used to construct single-valued
attributes from multi-valued …

Add authproc filter to test correct cardinality

---

modules/metarefresh/lib/MetaLoader.php

If metarefresh refuses to load remote XML, it would be useful to be able to see the error message from the underlying SAML2 or XML parsers in order to determine the root cause of the error.

 Return XML parser error in metarefresh

---

composer.json
modules/core/lib/Storage/SQLPermanentStorage.php
tests/modules/core/lib/Storage/SQLPermanentStorageTest.php

Attempt to fix #744
I have tested it with the oauth-module (currently the only module using it) and it's working like a charm!
Should be fully backwards compatible too!

 Replace deprecated Sqlite-calls with PDO-calls 

---

lib/SimpleSAML/Configuration.php
tests/lib/SimpleSAML/ConfigurationTest.php

The main practical motivation here is to support dynamic (virtual) population of authsources.php - since existing code paths will always attempt to load this from a literal file, via SimpleSAML_Configuration::loadFromFile

Support preload virtual config file

---

lib/SimpleSAML/Utils/Config.php
tests/lib/SimpleSAML/Utils/ConfigTest.php

Option to support Apache CGI in combination with custom config directory.
When setting the environment variable via an htaccess while using PHP via Apache CGI the environment variable gets prefixed with "REDIRECT_". This pull request adds support for reading out the other pull request

Apache CGI support

---

lib/SimpleSAML/Metadata/SAMLBuilder.php
lib/SimpleSAML/Metadata/SAMLParser.php
modules/saml/docs/sp.md
modules/saml/www/sp/metadata.php

This patch adds two metadata configuration options for 'index' and 'isDefault' attributes. We had to be able to output the isDefault attribute in the AttributeConsumingService element.
I don't know if 'attributes.index' and 'attributes.isDefault' is the best and correct names for the options, so please feel free to comment on this if needed.

Added metadata configuration options for 'index' and 'isDefault' attributes in AttributeConsumingService element

---

dictionaries/status.definition.json
modules/core/www/authenticate.php
templates/status.php

It can be useful to see the AuthData when testing an authentication source.
Since the AuthData can be a hierarchy of data of various depths it is converted
into a pretty printed JSON structure and put inside &lt;pre>
Since the amount of AuthData can vary greatly, the data is displayed in side
a &lt;details> element which requires clicking to view.

Show AuthData on authentication status page

---

lib/SimpleSAML/Utils/HttpAdapter.php
modules/core/lib/Auth/Process/Cardinality.php
modules/core/lib/Auth/Process/CardinalitySingle.php
tests/modules/core/lib/Auth/Process/CardinalitySingleTest.php
tests/modules/core/lib/Auth/Process/CardinalityTest.php
tools/phpunit/phpunit.xml

This fixes the unit tests for the Cardinality/CardinalitySingle auth process filters.
The intention is to assert that certain requests result in a redirect.  In order to do this, we need to mock the HTTP helper class, and in order to do that we need to create a non-static HTTP wrapper which we can inject into the cardinality filter instances.

Fixes cardinality auth filter unit tests (#860)

---

lib/SimpleSAML/Configuration.php
lib/SimpleSAML/Utils/System.php
tests/lib/SimpleSAML/ConfigurationTest.php

This port of catalyst/moodle-auth_saml2#85 fixes #559. There are two changes:
* `SimpleSAML_Configuration::resolvePath()` should resolve paths via `SimpleSAML\Utils\System::resolvePath()` for consistency and to reduce duplication
* `System::resolvePath()` should treat paths beginning with a drive letter as absolute

Improve handling of paths containing Windows-style drive letters

---

lib/SimpleSAML/Metadata/MetaDataStorageHandlerPdo.php

By using an appropriate WHERE clause in the SQL statement,
we can avoid loading the whole dataset in getMetaData(),
which brings an welcome performance improvement with large
Metadata sets.

Improve MetaDataStorageHandlerPdo::getMetaData() performance

---

modules/consent/dictionaries/consent.translation.json

Small spelling mistake in consent module.
"Gerbuikersinformatie" to "Gebruikersinformatie"

Updated Dutch Translation (Spelling mistake table_caption)

---

docs/simplesamlphp-authproc.md
modules/core/docs/authproc_cardinality.md
modules/core/docs/authproc_cardinalitysingle.md

It seems we forgot to link the core:Cardinality* authproc filters into the list of included filters. This fixes that, and also gets the crosslinking between the two working.

Improve documentation for cardinality authproc filter

---

modules/authfacebook/extlibinc/base_facebook.php

Do not include query parameters when constructing redirect uri for use with
the `access_token` endpoint.
Background:
Depending on your Facebook app configuration Facebook may return additional query
parameters after a a user authorizes an app. The module was incorrectly adding
these extra params to its redirect uri and generating a redirect uri that is
not in the app's whitelist. The new param that Facebook has added to response is enforce_https=1

Make authfacebook compatible with new facebook response query params

---

lib/SimpleSAML/SessionHandlerPHP.php

As mentioned by @iamtankist in #793 , there is a potential problem if you are trying to update cookie parameters having an active session(https://secure.php.net/session_set_cookie_params) 
There are not much to do for a fix - I just put the call to `session_set_cookie_params` right after closing the previous session, not before as it was

Make sure that session is closed and only then update cookie params

---

docs/simplesamlphp-authproc.md
modules/saml/docs/authproc_authncontextclassref.md

Found existing code when trying to correct the default AuthnContextClassRef value sent, noticed it was undocumented.
Context (no pun intended), since it may suggest another change:
SSP by default sets an `AuthnContextClassRef` of `urn:oasis:names:tc:SAML:2.0:ac:classes:Password`, of which the SAML spec says:
> The Password class is applicable when a principal authenticates to an authentication authority through the presentation of a password over an unprotected HTTP session.
I'd claim (and hope) that most deployers will only ever be running an IDP over TLS (in which case `AC_PASSWORD` doesn't seem appropriate), but I understand SSP cannot blindly default to `PasswordProtectedTransport` either.
Maybe check `SimpleSAML\Utils\HTTP::isHTTPS()` instead and switch to …

Add docs for saml:AuthnContextClassRef filter

---

modules/saml/lib/IdP/SAML2.php

Following up on the idea mentioned in #937: If the transport is secure fall back to the `PasswordProtectedTransport` authn context class ref, otherwise keep the current default of `Password`.
Requires a version of the SAML2 library with simplesamlphp/saml2#129 merged due to referencing a newly defined Constant.

PasswordProtectedTransport authncontext when HTTPS

---

lib/SimpleSAML/Metadata/MetaDataStorageHandler.php
modules/saml/lib/IdP/SAML2.php
tests/Utils/StateClearer.php
tests/modules/saml/lib/IdP/SAML2Test.php

I've added tests for idp initiated login. Since the code path loads metadata I had to add the `ClearableState` interface to `MetaDataStorageHandler` so I could reset its cache of metadata between tests.
I've also added support for the query parameters used by shibboleth for IdP initiated login. This is because (as we migrate Shib IdPs to SSP based IdPs) we encounter broken SPs that make use of IdP initiated login and require the use of shib style idp initiated login.  Yes, it is stupid that the SPs are incapable of making an `authnRequest`.

Idp Initiated login tests + query param compatibility with shib

---

.travis.yml
phpunit.xml

From what I've seen, it's more common to have `phpunit.xml` in the root repository directory. I think this provides a few advantages:
- Developers can simply run `phpunit` instead of `phpunit -c /path/to/configuration`.
- Developers will be able to find the `phpunit.xml` configuration file more easily since it's in a more common spot.
- We don't have to specify `./../../` for all paths in `phpunit.xml`.
- We can delete the `tools` directory since it's no longer used for anything else.

Moved phpunit.xml configuration file to root repository directory

---

docs/simplesamlphp-install-repo.md

Out of the box, installation needs running npm install too. Subversion instructions removed by indication of @thijskh

Removed Subversion section, and added need for npm

---

docs/simplesamlphp-artifact-sp.md
docs/simplesamlphp-googleapps.md
docs/simplesamlphp-idp.md
docs/simplesamlphp-sp.md
modules/saml/docs/keyrollover.md

Change documentation from recommending 2048 bit keys to using 3072 bit
keys.
Given that we're recommending people generate ten-year keys, 2048 bit
keys are probably a bit short. Almost all commercial certificate
authorities now recommend 4096 bit keys, and eduGAIN requires 3072 bit
keys for new federations.
This change aligns the SimpleSAMLphp documentation with the lower
eduGAIN requirement, since that still meets most standards bodies
recommendations for 2028 (ten years from now). cf
https://www.keylength.com/

Update OpenSSL RSA bit length in docs

---

config-templates/config.php
modules/saml/lib/Message.php

This was an hardcoded setting that we would like to change. Therefore making it configurable seems the right thing.
We have a customer with an Microsoft ADFS server that's about one minute ahead of time a few times per day. With this setting, we can allow them to be ahead instead of having the customers of the customers complain.

Create a setting for the allowed assertion offset

---

bin/pwgen.php
lib/SimpleSAML/Utils/Crypto.php
modules/authcrypt/lib/Auth/Source/Htpasswd.php
tests/lib/SimpleSAML/Utils/CryptoTest.php

As discussed during the hackathon;  closes #602
It is fully backwards compatible with current hashes, so it's safe to merge. Will only affect newly generated hashes with `bin/pwgen.php`

Rewrite Crypto::passwordHash() to use BCRYPT instead of unsafe algorithms

---

modules/authorize/docs/authorize.md
modules/authorize/lib/Auth/Process/Authorize.php
modules/authorize/templates/authorize_403.php
modules/authorize/templates/authorize_403.twig
modules/authorize/www/authorize_403.php

Fixes https://github.com/simplesamlphp/simplesamlphp/issues/995.

Show custom rejection message to unauthorised users

---

modules/multiauth/docs/multiauth.md
modules/multiauth/lib/Auth/Source/MultiAuth.php
tests/modules/multiauth/lib/Auth/Source/MultiAuthTest.php

The use case is: We want to use multiauth but without show the select source page. This a extra step than can confuse to our users.
So, if no `source` or `multiauth:preselect` option is present, the optional `preselect` value could be used to redirect directly to default source.
It is responsibility of the custom theme to detect than the request comes from 'multiauth' module and show a way to delegate the authentication to the others sources.
If no `preselect` option is added, the module works as usual.
The proposed config for this is:
```php
<?php
array(
'example-multi' => array(
'multiauth:MultiAuth',
/*
* The available authentication sources.
* They must be defined in this authsources.php file.
*/
'sources' => array(
'example-saml' => array(
// ...
),
'example-admin' => array(
// ... …
```

Optional preselect in multiauth source config

---

modules/saml/docs/sp.md
modules/saml/lib/Auth/Source/SP.php

My implementation of Conditions/AudienceRestriction/Audience support in SAML2 AuthnRequest, as requested in https://github.com/simplesamlphp/simplesamlphp/issues/201
Requeries updated saml2 library: https://github.com/simplesamlphp/saml2/pull/137

Support for AudienceRestriction in SAML2 request

---

docs/simplesamlphp-maintenance.md
lib/SimpleSAML/Store/Redis.php
tests/lib/SimpleSAML/Store/RedisTest.php

For Redis instances that require authentication, the current Redis store does not work.  So, this commit adds optional support for utilizing the Predis password option.  It will pick up the password from the config file and pass it along when it instantiates the Predis client.
The test simply checks that adding the password option doesn't break the constructor. Since Predis parameters end up as protected, we can't verify that the instance contains the password.

Add Password Support to Redis library

---

modules/multiauth/lib/Auth/Source/MultiAuth.php

I was testing the preselect method and I noticed that it was not being used.
When I changed the order in which the state was being saved, it worked.
I also corrected on small spelling mistake (Source)

Multiauth: The preselect param is not being saved in the state

---

lib/SimpleSAML/Metadata/SAMLParser.php
modules/metarefresh/lib/MetaLoader.php

It turns out that in addition to what's described in #1032 and simplesamlphp/saml2#151, there are a couple of minor typos introduced by recent changes that prevent metarefresh from outputting syntactically valid PHP when the flatfile metadata source is configured.
The typo in `lib/SimpleSAML/Metadata/SAMLParser.php` causes metarefresh to crash with an exception in the logs like this:
```
[b28306d351] SimpleSAML\Error\Exception: Error 1 - Call to undefined function http://macedir.org/entity-category-support() at /srv/simplesamlphp-1.17.0-rc1/lib/SimpleSAML/Metadata/SAMLParser.php:1050
[b28306d351] Backtrace:
[b28306d351] 2 /srv/simplesamlphp-1.17.0-rc1/www/_include.php:48 (SimpleSAML_error_handler)
[b28306d351] 1 /srv/simplesamlphp-1.17.0-rc1/www/_include.php:25 …
```

Make metarefresh work in 1.17.0 rc1

---

config-templates/config.php
lib/SimpleSAML/Logger.php

There is an existing StandardErrorLoggingHandler logging class, but no way to use it. Since logging to stderr is potentially useful to people trying to use SimpleSAMLphp in containers, this change makes the existing logging class usable.

Allow StandardErrorLoggingHandler to be used

---

dictionaries/login.translation.json
locales/de/LC_MESSAGES/messages.po

Just noticed this being wrongly. Not quite sure what your merge strategy is... should this go to master, potentially skipping the stable 1.16/next 1.17 channel?

translation: Use proper german wording for login header message

---

modules/saml/lib/IdP/SAML2.php

After updating to 1.17 I started noticing a lot of warnings in the log:
\Mar  4 12:47:16 sv1810934 IDP-BZK[5791]: 3 [c11b0ed290] Unable to generate NameID. Check the userid.attribute option.
SP doesn't ask for a specific NameIDFormat and none is set in the metadata...
current([]) would return false, but we never catch that, so it falls through,..

Supress warning on absent NameIDFormat

---

tests/SigningTestCase.php
tests/lib/SimpleSAML/XML/SignerTest.php
tests/lib/SimpleSAML/XML/ValidatorTest.php

Allows sharing a valid certificate setup with `SignerTest`. In `SignerTest`, reuse "good certificate" as the main certificate for signature and add a second certificate for `testSignWithMultiCertificate`.

Factor out SigningTestCase for reuse

---

docs/simplesamlphp-automated_metadata.md
docs/simplesamlphp-changelog.md
lib/SimpleSAML/Metadata/SAMLParser.php
lib/SimpleSAML/Metadata/Sources/MDQ.php
modules/metarefresh/bin/metarefresh.php
modules/metarefresh/config-templates/config-metarefresh.php
modules/metarefresh/lib/MetaLoader.php
tests/lib/SimpleSAML/Metadata/SAMLParserTest.php
tests/modules/metarefresh/lib/MetaLoaderTest.php

Some metadata publishers offer SHA256 fingerprints to validate the fingerprint of the certificate used to sign metadata. Allow users to configure the fingerprinting algorithm to facilitate validation.
For backward compatibility, the default algorithm remains SHA1.
---
Out of convenience, I rebased this work on https://github.com/simplesamlphp/simplesamlphp/pull/1051. While I prefer to reuse the existing certificate setup architecture, I can rework the PR use master as its base.

Make metadata validateFingerprint algorithm configurable

---

modules/discopower/templates/disco.tpl.php

The template for discopower ends up with broken tabs because the call to
```javascript
$("#tabdiv").tabs
```
is missing.
Looking through the equivalent twig template, the whole function has migrated to [PowerIdPDisco.php](https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/discopower/lib/PowerIdPDisco.php#L288), so rather than fixing it in this template, it makes sense to duplicate what's happening in the twig template. Thus the first commit removes the javascript references to liveUpdate at the bottom in favour of simply including `$this->data['search']` which produces the same result albeit with the tabs call.
At the same time I noticed that both `String.prototype.score` functions were being included (quicksilver and suggest) rather than honouring the one selected in the …

discopower module tabs don't work

---

lib/SimpleSAML/Metadata/SAMLParser.php
tests/lib/SimpleSAML/Metadata/SAMLParserTest.php

There is a simple boolean logic error in the handling of mdui:Keywords and mdui:Logo that results in those elements never being output into metadata.
This impacts any user interface that displays a logo for an entity (such as discovery interfaces). It is a regression that affects the 1.17.1 release.

Fix logic error in UIInfo generation

---

modules/discopower/locales/en/LC_MESSAGES/discopower.po
modules/discopower/templates/disco.twig

simplesamlphp@b3ee105e720a3d243c1a7c8247b4687816542e03 undid simplesamlphp@d13304e8cbc8ecdb83315f8118e4b4dc88d05912
This is a regression that makes the twig template in 1.17.1 unusable. However, the change below is against master and thus incorporates the change from #1079 too.

Make the module-discopower twig template usable

---

modules/discopower/lib/PowerIdPDisco.php

Use keys from `$idpList` instead (similar to https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/discopower/lib/PowerIdPDisco.php#L289)

Remove hard coded tabs

---

lib/SimpleSAML/Utils/System.php
tests/lib/SimpleSAML/Utils/SystemTest.php

Currently the function `System::resolvePath` assumes paths, which are using stream wrappers like `s3://` to be relative to a base path.
To allow the usage of stream wrappers the `System` class has been extended. This gives the ability to store **certificates** and **private keys** in a different location than the server's filesystem but can also be used for other scenarios where configured paths are used (e.g. logdir, datadir, tempdir).

allow paths to use stream wrappers

---

modules/saml/docs/sp.md
modules/saml/www/sp/metadata.php

This commit adds the ability to override the defaults in the generated SP metadata for SLO Location and ACS endpoints. This is necessary for my use case as I have additional ACS endpoints to publish in my metadata beyond the generated ones as well as a custom SLO handler that I need to direct my users to. If unset in the config, it uses the defaults as before.
This addresses #954.

SAML: Configurable SLO and ACS metadata

---

modules/discopower/lib/PowerIdPDisco.php

Following on from #1081, this changes the behaviour of tabs for which there is no translation available. Instead of displaying "not translated ({discopower:tabs:foo})", it will fail to the more graceful and less ugly behaviour of simply displaying the tab's original untranslatable name.

Handle untranslated tabs more gracefully in discopower-module

---

composer.json
modules/authorize/docs/authorize.md
tests/_autoload_modules.php
tests/modules/authorize/lib/Auth/Process/AuthorizeTest.php
tests/modules/authorize/lib/Auth/Process/TestableAuthorize.php

Let me know if you have a recommended way for testing code that calls out `HTTP::redirectTrustedURL`. I avoided that code path in those tests.  For our internal modules we use the technique outlined in https://github.com/cirrusidentity/simplesamlphp-test-utils#mock-redirects

Initial tests for authorize:authorize

---

bin/importPdoMetadata.php

Fixes #1109
Instead of using a hardcoded "metadata" folder, use the metadatadir to import metadata from flatfile into a database.

look it up from the metadatadir from configuration variable

---

TESTING.md
tests/lib/SimpleSAML/ConfigurationTest.php
tests/lib/SimpleSAML/DatabaseTest.php
tests/lib/SimpleSAML/Metadata/MetaDataStorageSourceTest.php
tests/lib/SimpleSAML/ModuleTest.php
tests/lib/SimpleSAML/StoreTest.php
tests/lib/SimpleSAML/Utils/AttributesTest.php
tests/lib/SimpleSAML/Utils/ConfigTest.php
tests/lib/SimpleSAML/Utils/CryptoTest.php
tests/lib/SimpleSAML/Utils/EMailTestCase.php
tests/lib/SimpleSAML/Utils/HTTPTest.php
tests/lib/SimpleSAML/Utils/SystemTest.php
tests/lib/SimpleSAML/Utils/XMLTest.php
tests/lib/SimpleSAML/XML/ParserTest.php
tests/lib/SimpleSAML/XML/Shib13/AuthnResponseTest.php
tests/lib/SimpleSAML/XML/SignerTest.php
tests/lib/SimpleSAML/XML/ValidatorTest.php
tests/modules/core/lib/Auth/Process/AttributeAddTest.php
tests/modules/core/lib/Auth/Process/AttributeAlterTest.php
tests/modules/core/lib/Auth/Process/AttributeCopyTest.php
tests/modules/core/lib/Auth/Process/AttributeLimitTest.php
tests/modules/core/lib/Auth/Process/AttributeMapTest.php
tests/modules/core/lib/Auth/Process/AttributeRealmTest.php
tests/modules/core/lib/Auth/Process/AttributeValueMapTest.php
tests/modules/core/lib/Auth/Process/CardinalityTest.php
tests/modules/core/lib/Auth/Process/PHPTest.php
tests/modules/core/lib/Auth/Process/TargetedIDTest.php
tests/modules/core/lib/Auth/UserPassBaseTest.php
tests/modules/core/lib/ControllerTest.php
tests/modules/multiauth/lib/Auth/Source/MultiAuthTest.php

Remove expectedException annotations

---

docs/simplesamlphp-reference-idp-remote.md
modules/saml/lib/Auth/Source/SP.php

Allows to set a different authnContextClassRef per IDP.
Can be used in cases where one SP has multiple IDP's and one-or-more IDP's require specific non-default values (i.e. Dutch eHerkenning).
It would be very desirable if we can backport this to 1.17

Per-IDP configurable AuthnContextClassRef/AuthnContextComparison

---

lib/SimpleSAML/Metadata/MetaDataStorageHandlerFlatFile.php
lib/SimpleSAML/Metadata/MetaDataStorageHandlerPdo.php
lib/SimpleSAML/Metadata/MetaDataStorageSource.php

Fixes #926
I recently ran into the issue outlined in #926 and upon doing some research this bug was introduced in commit 7dc9d91403c00b5b2cada54ac6dea14ff01baa6a when optimizations were made to the PDO Metadata Storage Handler to improve performance by using a WHERE clause to lookup a specific metadata entry by entity id.  This obviously doesn’t work with __DYNAMIC:*__ entries because dynamic entity ids are generated and merged into the metadata array when the metadata is fetched.
Rather than rollback these changes and lose the full benefit of the optimizations (I see why the change was made, as the load method fetches all metadata from a given table and then processes it all at once), when an idp_hosted metadata set is queried, I changed the query to use a wildcard to lookup rows that …

Fixes #926: PDO Metadata Source Doesn't Load __DYNAMIC:1__ Metadata Sets

---

config-templates/config.php
lib/SimpleSAML/Locale/Language.php
lib/SimpleSAML/SessionHandler.php
lib/SimpleSAML/SessionHandlerPHP.php
lib/SimpleSAML/Utils/HTTP.php
tests/lib/SimpleSAML/SessionHandlerPHPTest.php
tests/lib/SimpleSAML/Utils/HTTPTest.php

Chrome 76 [changes the behaviour of cookies](https://blog.chromium.org/2019/05/improving-privacy-and-security-on-web.html) in a way that breaks SimpleSAMLphp's session cookie. There has been [discussion of this on the REFEDS list](https://lists.refeds.org/sympa/arc/refeds/2019-06/msg00005.html), and my own testing confirms it is a problem in SSP 1.17.x.
In order to work around this problem, we need to allow people to set the SameSite=None attribute on session cookies. This patch introduces a new config option `session.cookie.samesite` that allows people to specify how this should be treated. It defaults to reproducing the existing behaviour of not setting the SameSite attribute at all, but can be set to `'None'` if people need to work around the Chrome 76 problem.
Unfortunately, PHP only …

Add support for RFC6265bis SameSite cookie attribute in 1.17

---

modules/saml/lib/SP/LogoutStore.php

Closes #1089, should probably be backported to 1.17 too

Logoutstore: Fix indexes that are too big

---

modules/core/lib/Auth/UserPassOrgBase.php

This adds the same logging to `UserPassOrgBase::handleLogin` function
as it is in the `UserPassBase::handleLogin` (UserPassBase.php).
Not sure if IP address logging (`$_SERVER['REMOTE_ADDR']`) is still required here.

Add logging for organizational logins

---

docs/simplesamlphp-theming.md
lib/SimpleSAML/XHTML/Template.php

When developing themes it is common to want to make only minor cosmetic changes to the existing template, such as adding additional CSS. Under the old theming system it was possible to inherit the stock theme and alter it by simply include()ing the PHP.
Similar functionality doesn't exist in Twig, but arguably makes more sense here where we can now override a single block. This functionality is already used by themes to override the default theme, but the model doesn't extend to modules. Thus this commit introduces a special `__parent__` namespace in Twig to allow theme developers to reference the original module templates from within their own theme's template.
E.g if I wanted to inheret the entire discopower module's template save for injecting one additional script into it, rather than …

Allow themes to inherit module templates

---

modules/saml/lib/SP/LogoutStore.php

This makes the changes in #1120 specific for MySQL, leaving other types of databases untouched.
Hopefully fixes #1177

Fix column and index-size for MySQL only

---

lib/SimpleSAML/IdP/IFrameLogoutHandler.php

We need a little hack to enforce the use of Twig, even if newui is set to false.
It's either this, or revert to inline HTML in our PHP-files..
Fixes #1191

Fix raw template being returned by SingleLogoutResponse.php

---

docs/simplesamlphp-idp.md

It wasn't immediately clear to me where to put the cert and private key when I went through these instructions recently, so I thought I'd propose a change to make the destination explicit.

clarify where certs go in IdP quick start docs

---

lib/SimpleSAML/Store/SQL.php

Closes #423
~~Needs testing by someone using any DBMS other than mysql & sqllite~~
We can actually test this on any DBMS as the default case should always work.. It works fine after resolving a little mistake

Rationalize SQL Store insertOrUpdate

---

lib/SimpleSAML/Configuration.php
lib/SimpleSAML/Database.php
lib/SimpleSAML/IdP.php
lib/SimpleSAML/Logger.php
lib/SimpleSAML/Memcache.php
lib/SimpleSAML/Session.php
lib/SimpleSAML/SessionHandler.php
lib/SimpleSAML/SessionHandlerPHP.php
lib/SimpleSAML/SessionHandlerStore.php
lib/SimpleSAML/Store.php
lib/SimpleSAML/Utilities.php
lib/SimpleSAML/Utils/HTTP.php
modules/saml/lib/SP/LogoutStore.php
psalm.xml

Fixes all Psalm-issues in all if `SimpleSAML/lib/`.

Fix Psalm-issues batch #3

---

lib/SimpleSAML/Auth/Simple.php
lib/SimpleSAML/Configuration.php
lib/SimpleSAML/Locale/Translate.php
lib/SimpleSAML/Module.php
lib/SimpleSAML/Stats.php
lib/SimpleSAML/Utils/HTTP.php
tests/lib/SimpleSAML/ConfigurationTest.php

When using `Configuration::getConfigItem` or `Configuration::getConfigList` (only one user), the function can return a `Configuration` or `$default`. This makes it hard to handle default cases where the configuration settings are not in config.php.
This PR modifies these functions so that `Configuration::getConfigItem` only returns `Configuration` objects or `null`, and `Configuration::getConfigList` only returns arrays. This removes the need for return value checking in calling functions.
This happens at the cost of being able to require that the configuration option is set, but this is a feature; assume that `['assets']['cache']['max-age']` was required:
```php
$assets = $config->getConfigItem('assets'); // returns empty Configuration
$cache = $assets->getConfigItem('cache'); // returns …
```

Clean up getConfigItem

---

modules/multiauth/templates/selectsource.tpl.php

source text does not need to go through internationalization as it is already handled by the text specified in the authsources file. #1206

Update selectsource.tpl.php to address #1206

---

modules/saml/docs/nameid.md
modules/saml/lib/Auth/Process/SQLPersistentNameID.php
modules/saml/lib/IdP/SQLNameID.php
tests/modules/saml/lib/IdP/SQLNameIDTest.php

SQLPersistentNameID only allowed the global datastore to be used when it is of type SQL. This filter could not be used when the global datastore is for example memcache.
After this change, SQLPersistentNameID can be used with any database (specified by dsn, username, password). The change is backward compatible; without using the new option, it falls back to the SQL datastore and behaves like it did before.
This option is similar as in the Consent module.

add store option to SQLPersistentNameID

---

docs/simplesamlphp-install.md

The current upgrade instructions don't mention that people need to preserve themes or third-party modules, and this has confused some people I've tried to help. Thus I'm proposing adding a note about that.
The second patch is more controversial and had been done separately do it can be discarded if necessary. At the moment the theme on https://simplesamlphp.org/ is not rendering markdown preformatted blocks properly, and the shell script entries are being munged into one line. That means that a copy-and-paste doesn't work. We can fix this by adding semicolons, which usefully doesn't break things later if the theme works again.  (Alternatively someone could fix the theme :-))

Add note about upgrading third party modules

---

modules/core/templates/show_metadata.tpl.php

The code generated: `$metadata['idp'] => array();` causing an error when I used this to copy the metadata and pasted it in the `metadata/saml20-idp-remote.php` file of another server.

core/show_metadata: changed => to =

---

modules/core/templates/show_metadata.tpl.php

Terribly sorry I did not include this one in my pull request from yesterday. As it turned out I added the missing semicolon automatically, but to be correct and allow brainless copy-pasting of this metadata, you'll need the semicolon on the end of the metadata.
PS: Just some background information: I ran into this issue when I tried to copy-paste the metadata for my IdP from another SP that was already using it, to a new SP I was configuring. When you go straight to the IdP and ask the metadata there you use `/www/saml2/idp/metadata.php` and that one is working fine, so that might explain why it took so long to be discovered.

core/show-metadata: added a semicolon at the end of the metadata

---

config-templates/config.php
dictionaries/attributes.translation.json
dictionaries/disco.translation.json
dictionaries/errors.translation.json
dictionaries/general.translation.json
dictionaries/login.translation.json
dictionaries/logout.translation.json
dictionaries/status.translation.json
lib/SimpleSAML/Locale/Language.php
locales/st/LC_MESSAGES/attributes.po
locales/st/LC_MESSAGES/messages.po
modules/core/dictionaries/cardinality.translation.json
modules/core/dictionaries/no_cookie.translation.json
modules/core/dictionaries/no_metadata.translation.json
modules/core/dictionaries/no_state.translation.json
modules/core/locales/st/LC_MESSAGES/core.po
modules/multiauth/dictionaries/multiauth.translation.json
modules/multiauth/locales/st/LC_MESSAGES/multiauth.po
modules/saml/dictionaries/proxy.translation.json
modules/saml/locales/st/LC_MESSAGES/saml.po
templates/includes/header.php

This pull request adds a partial Sesotho translation.
Sesotho is one of the eleven South African official languages, covering the second of the two dominant Southern Bantu language grouping in Southern African (Tswana-Sotho).  It is spoken by about 4million South Africans. It has a very high level of mutual intelligibility with other Tswana-Sotho group languages, including Tswana and Northern Sotho (Sepedi). These are also official languages of South Africa and share a partially standardised orthography with Sesotho.
The translation was commissioned by TENET/SAFIRE, and was done by a professional translation company. It is incomplete because the intent was to cover the parts of the user interface (rather than the admin interface) that we're currently presenting to end-users, on the basis …

Add Sesotho translation

---

lib/SimpleSAML/Store/SQL.php

SQL Store does not work with PostgreSQL DB because 'CREATE INDEX' should be used in PostgreSQL.
Reporting bugs questions answers:
How can we reproduce the bug?
1. set 'store.type' to 'sql' in config.php
2. configure 'pgsql' PDO
3. run SimpleSamlphp with PostgreSQL against which should be run statements that updates 'kvstore' table
Is it reproducible in other environments (for example, on different browsers or devices)?
I reproduced in folowing postgres docker images
- postgres:12.1-alpine
- postgres:11.6-alpine
- postgres:10.11-alpine
- postgres:9.6.16-alpine
What tags should the bug have?
v1.18.*
How critical is this bug? Does it impact a large amount of users?
this affects any user use PostgreSQL and does not have latest kvstore table.
Is this a security issue? 
no.

SQL Store does not work with PostgreSQL DB that does not have latest kvstore table

---

lib/SimpleSAML/Session.php

which may be a `string`, an `array` of `[class|object, method]` or a closure
https://www.php.net/manual/en/language.types.callable.php

allow session.check_function to be any Callable

---

lib/SimpleSAML/Locale/Translate.php
lib/SimpleSAML/XHTML/Template.php
modules/core/templates/base.twig
modules/core/templates/show_metadata.twig
templates/auth_status.twig
templates/includes/expander.twig
templates/metadata.twig
templates/selectidp-links.twig

Enable twig strict vars and fix broken templates

Twig Strict vars

---

TESTING.md

[#3d121](https://github.com/simplesamlphp/simplesamlphp/commit/3d121046c4839a99833fffd2ea78b45258b1bbae#diff-84889d0af78b35050da8d12673769eba) switched from using phpunit annotations to `expectException()` for asserting expected exceptions, but the documentation still mentions the annotation.

Mention expectException instead of phpdoc annotations in TESTING.md

---

docs/simplesamlphp-install.md

Currently when users set up SimpleSAML to start with there's no theming, this adds a step to make sure that is present.

Add npm steps so users have a theme

---

composer.json
composer.lock
modules/admin/lib/Controller/Federation.php
modules/saml/www/sp/metadata.php
www/admin/metadata-converter.php
www/saml2/idp/metadata.php

Instead of `var_export`, this provides nice, PSR-12 compliant output without explicit numeric array indices.

use Symfony VarExporter in metadata converter

---

lib/SimpleSAML/Utils/System.php
tests/lib/SimpleSAML/Utils/SystemTest.php

This has been addressed using the `is_writable` function instead of checking for UID, which only works in a Linux environment.

Issue #1272 - SSP refuses to use temp dir if it doesn't own it, even though it can write to it

---

lib/SimpleSAML/Module.php

If the file system containing the PHP code is case-insensitive, a
request containing an uppercase file extension will return the
contents of the PHP file to the browser instead of executing it.
E.g. a request for this URL will return the source code:
https:/sp.example.org/simplesaml/module.php/core/frontpage_welcome.PHP
Fix that by converting the path to lowercase before checking the file
extension.
See the following page for details:
https://github.com/simplesamlphp/simplesamlphp/security/advisories/GHSA-24m3-w8g9-jwpq

Fix source code disclosure on case-insensitive file systems

---

modules/core/locales/pl/LC_MESSAGES/core.po

In the Polish language, correct translate for the word 'Authentication' is 'Uwierzytelnianie'. Unfortunately, many people write/say 'Autentykacja'. This one doesn't exist in the Polish dictionary. 
**Source**: 
- "English 4 IT" (https://helion.pl/ksiazki/english-4-it-praktyczny-kurs-jezyka-angielskiego-dla-specjalistow-it-i-nie-tylko-beata-blaszczyk,anginf.htm#format/d)
- "Polish dictionary" (https://sjp.pl/Autentykacja)

Fixed incorrect translate for the 'Authentication' word

---

modules/saml/lib/Auth/Process/NameIDAttribute.php
tests/modules/saml/lib/Auth/Process/NameIDAttributeTest.php

Override `NameID` `Format`, `NameQualifier`, `SPNameQualifier` when they **are** `null`

Fix bug in saml:NameIDAttribute authproc filter

---

lib/SimpleSAML/SessionHandlerPHP.php

fixed this warning > Warning: session_create_id(): Failed to create new ID in /var/ssosp/lib/SimpleSAML/SessionHandlerPHP.php on line 176

fixed warning when Warning: session_create_id(): Failed to create ID

---

docs/simplesamlphp-install.md

Currently on https://simplesamlphp.org/docs/stable/simplesamlphp-install the section [3.3 Alternative location for configuration files](https://simplesamlphp.org/docs/stable/simplesamlphp-install#section_3) sits as a subheading beneath [3. Upgrading from a previous version of SimpleSAMLphp](https://simplesamlphp.org/docs/stable/simplesamlphp-install#section_3)
This change creates a section "Configuration" underneath the "Upgrading" section, moving "Location of configuration files" inside that section; then we continue with "Configuring Apache" ... as before.
I'm not familiar with the docs generation process for this project, but I expect this will result in a corresponding update to https://simplesamlphp.org/docs/stable/simplesamlphp-install
Hope this small change helps others to find …

Move config file location docs

---

modules/core/templates/loginuserpass.twig

Fixes 336b7abef59e47c6e16c3587a703af558871072a which changed the label from
'Login' to a single-use 'Log in' whilste the translations only have 'Login'.
modules/core/templates/loginuserpass.twig:              {% trans %}Log in{% endtrans %}
modules/exampleauth/lib/Auth/Source/External.php:     * Log in using an external authentication helper.
modules/exampleauth/lib/Auth/Source/StaticSource.php:     * Log in using static attributes.
modules/exampleauth/templates/authenticate.twig:      <p><input type="submit" value="Log in"></p>
modules/multiauth/docs/multiauth.md:                    'en' => 'Log in using a SAML SP',
modules/multiauth/docs/multiauth.md:                    'en' => 'Log in using the admin password',

core/loginuserpass: Fix login button translation

---

config-templates/config.php
docs/simplesamlphp-database.md
lib/SimpleSAML/Database.php
tests/lib/SimpleSAML/DatabaseTest.php
tests/modules/saml/lib/IdP/SQLNameIDTest.php

In light of increased awareness around the use of oppressive language and its role in the #BlackLivesMatter movement, it seems appropriate to remove references to the master-slave metaphor within SSP. While there are other examples of oppressive language (notably whitelist/blacklist) within SSP, this particular one seems both the most problematic and the easiest to resolve.
Fortunately, there are very few references to master-slave within the core of SSP and their use is limited entirely to the database abstraction layer. Moreover, most of the references are entirely internal within that module with only one external dependency.
This patch follows the suggestions of [draft-knodel-terminology-00](https://tools.ietf.org/id/draft-knodel-terminology-00.html) and other language frameworks to …

Remove master-slave metaphor

---

lib/SimpleSAML/XHTML/Template.php
modules/admin/lib/Controller/Federation.php
modules/admin/templates/federation.twig
tests/modules/admin/lib/Controller/FederationTest.php

Neater display of expire times in admin module.
Skip `expire` ouput in manual metadata conversion. This frequently gives problems when metadata was loaded successfully and everything works, but suddenly breaks days later. Theoretically including the expiration in manual conversion is ‘correct’, but pragmatically does not add much and does cause breakage.

Improve expired handling

---

config-templates/config.php
lib/SimpleSAML/Error/Exception.php

The previous situation was confusing with various contradicting (staments of) defaults, mixed with old style and new style
configuration.
This PR tries to solve it with the "flight forward" by deciding on a useful default (on) and making all configurations adhere to that, and only skip them when explicitly disabled in the new style config. Having backtraces on by default is very useful because it's the only sane way you can now do something when an SSP error occurs. It also is what we have now in the shipped config-template.
This change vastly simplifies the confusing code, and we can resolve a TODO of oldstyle vs newstyle handling so have repaid technical debt.

Improve backtraces configuration.

---

modules/core/lib/Auth/Process/ScopeFromAttribute.php
tests/modules/core/lib/Auth/Process/ScopeFromAttributeTest.php

Consistently treat scopes with multiple @

---

modules/saml/lib/SP/LogoutStore.php

Fixes https://github.com/simplesamlphp/simplesamlphp/issues/1379
This fixes the incorrect `ALTER ... MODIFY` syntax for SQLServer (it's `ALTER ... ALTER`) which prevents the `LogoutStore` to migrate from version `1 -> 2` and from version `3 -> 4`. Previously, migrating the versions failed and the old version was kept. This caused a warning to be logged but no other effect from what I could see.
I used https://github.com/simplesamlphp/docker-simplesamlphp along with a SQLServer image to verify that this fixes the problem, and I was able to successfully migrate the LogoutStore from version `1 -> 2` and from version `3 -> 4` (`2 -> 3` worked before this fix).

Fix SQLServer ALTER syntax

---

modules/core/templates/frontpage_federation.twig

The frontpage_federation template in 1.19 displays expiry dates in the future with a negative expiry:
`European University Cyprus (expired -95.59448483 hours ago)`
This has caused more than one brief moment of panic for metadata that still has a long way to go.
And since we're here, it also uses a precision such that we're measuring microseconds.

Fix logic leading to negative expiry

---

modules/multiauth/templates/selectsource.twig

MultiAuth source selection form has a hidden field AuthState to keep a session handler when user selects the actual authentication source.
The form is created based on the template at `modules/multiauth/templates/selectsource.twig`. AuthState value is subsituted to the template via *authstate* parameter. Apparently there's a trailing space in the value of the target field in the template what propagates to the final form and request, and then may effectively prevent restoration of the session.

Remove trailing space in AuthState value

---

modules/multiauth/docs/multiauth.md
modules/multiauth/lib/Auth/Source/MultiAuth.php

This PR introduces the necessary changes to allow an SP to choose an authentication source of multiauth. It works even if there are redirects during the authentication process because it uses SAML2 standard AuthnContextClassRef. See #912 for more context.

Filter multiauth authentication sources from SP using AuthnContextClassRef

---

config-templates/config.php
lib/SimpleSAML/Utils/HTTP.php
tests/lib/SimpleSAML/Utils/HTTPTest.php

Set intelligent defaults for SameSite cookie automatically so new installers don't need to think.

Allow easy enabling of SameSite = 'None'

---

lib/SimpleSAML/Module.php
tests/lib/SimpleSAML/ModuleTest.php
tests/modules/unittest/README.md
tests/modules/unittest/hooks/hook_invalid.php.orig
tests/modules/unittest/hooks/hook_valid.php
tests/modules/unittest/hooks/invalid_hook_prefix.php

Sometimes we patch or edit a hook to meet our specific needs.
Somtimes this leaves behind a file like FILENAME.orig. The hook
detection login still runs these other files, making for confusing
debugging issues. Use a stricter match on what makes a valid hook name
to avoid these issues.

Ignore invalid hook names

---

modules/saml/www/sp/saml2-acs.php

Hi, thanks for all the hard work around SSP, greatly appreciated!
This pull request makes SAML Response 'InResponseTo' attribute value available in auth state array. The purpose is to make it easily accessible on the SP side after the user authn, for example using the method \SimpleSAML\Auth\Simple::getAuthDataArray.
Use case is the following: we have an SP which enables users to authenticate using Croatian national identity infrastructure (NIAS). They have released a new feature - possibility to include their own header, like a banner, into every SP, so that every service has the same look, so to say, regarding the header part of the site. To get this header, a separate request is needed, with one of the parameters being the value of the 'InResponseTo' attribute of the SAML Response.

Make inResponseTo available in auth state

---

modules/saml/docs/keyrollover.md

The old privatekey_pass was (wrongly) expected to be reused for the new
privatekey_pass. That prevented my SP from loading the new_privatekey.
Users could not log in from entities using the new key.
Clarify that the new key needs a new_privatekey_pass entry.

Key rollover: Doc new_privatekey_pass option

---

modules/core/docs/authproc_pairwiseid.md
modules/core/docs/authproc_subjectid.md
modules/core/lib/Auth/Process/PairwiseID.php
modules/core/lib/Auth/Process/SubjectID.php
tests/modules/core/lib/Auth/Process/PairwiseIDTest.php
tests/modules/core/lib/Auth/Process/SubjectIDTest.php

This rationalizes the behaviour and makes it work the same as the core:ScopeAttribute authproc.
Also additional docs
Closes #1459

Identifiers fix #2

---

modules/saml/www/sp/saml1-acs.php

The additional information helps Service Providers identify Identity
Providers relying on SAML1 and Shibboleth 1.3.

Log which IdP issued a SAML1 assertion

---

config-templates/config.php

Additionally allows generating a password on current gen Macbook.
Before:
LC_CTYPE=C tr -c -d '0123456789abcdefghijklmnopqrstuvwxyz' </dev/urandom | dd bs=32 count=1 2>/dev/null;echo
tr: Illegal byte sequence
After:
LC_ALL=C tr -c -d '0123456789abcdefghijklmnopqrstuvwxyz' </dev/urandom | dd bs=32 count=1 2>/dev/null;echo
nhq2bu42k0iox5svm9rnmmon3oc2i55g

Replace LC_CTYPE with LC_ALL

---

docs/simplesamlphp-changelog.md
lib/SimpleSAML/Module.php

External modules could still be used even when not explicitly enabled.
Master was not affected by this bug.

Fix authproc/authsource in externalized module being usable illegally

---

config-templates/config.php
docs/simplesamlphp-upgrade-notes-2.0.md
lib/SimpleSAML/IdP.php
lib/SimpleSAML/Locale/Language.php
lib/SimpleSAML/Locale/Translate.php
lib/SimpleSAML/XHTML/IdPDisco.php
lib/SimpleSAML/XHTML/Template.php
tests/lib/SimpleSAML/Locale/LanguageTest.php
tests/lib/SimpleSAML/XHTML/TemplateTest.php

Reimplement getPreferredTranslation outside of IdPDisco so it's reusable and much more complete. The new method will search the current, default and fallback language for a displayable string in various metadata fields. This should be much more complete and robust than previous approches. Make it a Twig filter so it can also be used there.
For clarity:
- translateFromArray method/filter will give a single entry for an array with multiple language options. Most useful with e.g. config file options that have this format.
- getEntityPropertyTranslation method/filter will walk the three languages in priority order to find a named metadata key (useful for localized metadata fields where no other fields need to be searched)
- getEntityDisplayName (method only fornow) for the specific case for …

getEntityDisplayName to get entityID's name for display

---

modules/admin/lib/Controller/Test.php
modules/admin/templates/status.twig

This is my second attempt to fix #461. I have some trouble wrapping my head around all the present code and why this was there. But I can now confirm that the attribute names are correctly translated and that we've cleaned up some HTML generation in the controller. So without wanting to claim that I now fully understand all the (historic) intentions I think this gives us a cleaner base to start from.

Reimplement admin module auth test attribute presentation

---

config-templates/config.php
docs/simplesamlphp-upgrade-notes-2.0.md
lib/SimpleSAML/Locale/Localization.php
lib/SimpleSAML/Locale/Translate.php
modules/admin/lib/Controller/Test.php
modules/core/lib/Controller/Login.php
tests/lib/SimpleSAML/Locale/LocalizationTest.php

Now also considers any attributes.po in the configured theme, if any.
Makes the attributes.extradictionary config setting obsolete.
Closes #461

Move configuration of attribute name translation into a separate method.

---

modules/saml/lib/IdP/SAML2.php
tests/modules/saml/lib/Auth/Source/SPTest.php
tests/modules/saml/lib/IdP/SAML2Test.php
www/saml2/idp/metadata.php

As with SP before. Duplicated code exists inside module/saml and in www/idp/metadata.php. Move into one copy and make sure this is tested. The tests are derived from the old code to ensure it covers everything that it did before.

Deduplicate IdP hosted metadata

---

composer.json
composer.lock
lib/SimpleSAML/Locale/TwigTranslator.php
lib/SimpleSAML/XHTML/Template.php
modules/admin/templates/config.twig
modules/admin/templates/federation.twig
modules/admin/templates/metadata_converter.twig
modules/admin/templates/status.twig
modules/core/templates/cardinality_error.twig
modules/core/templates/loginuserpass.twig
modules/core/templates/logout-iframe.twig
modules/saml/templates/proxy/invalid_session.twig
templates/_table.twig
templates/auth_status.twig
templates/base.twig
templates/sandbox.twig
tests/lib/SimpleSAML/XHTML/TemplateTranslationTest.php

This updates twig to version 3 and wrapps translations via symfony/twig-bridge.
You can register your own translation handler or fall back to gettext.
The PR addresses #1273

updated twig to version 3 and added wrapper for translation

---

bin/get-translatable-strings
lib/SimpleSAML/Utils/Translate.php
lib/SimpleSAML/XHTML/Template.php
tests/lib/SimpleSAML/Utils/SystemTest.php
tests/lib/SimpleSAML/Utils/TranslateTest.php

This is likely not yet perfect or complete but it's a start to have something to extract translatable strings into PO files.
What it can do:
- For a module or the 'base' (= main code + the standard modules), walk all Twig templates for strings in the trans() function plus the PHP code under lib for the (Translate::)noop() function.
- Update the `en` po file for the module/for the global messages if not already present.
Since we currently have nothing of the sort I think this is a good step towards fixing #493.
Some things that could be improved upon (later):
- It does not yet merge the new EN strings into the language POs. This can be done but could also be done by the translator, so not sure if it's in scope. If it should be, is there a global list of what the supported languages are?
- …

Initial version of tool to extract translatable strings from templates.

---

modules/admin/lib/Controller/Config.php
modules/admin/templates/config.twig

Previously, the admin module did not provide any information about which modules you have installed or wheter they are enabled. This seems a logical thing to show there.
This is now combined with the "SAML 2.0 IdP" enabled/disabled flag
which was a bit lonely before, as it's the only flag of its type.

Show overview of modules in the admin plugin

---

modules/core/templates/loginuserpass.twig
package-lock.json
package.json
src/css/default-rtl.css
src/css/default.scss
src/js/bundle.js
templates/_header.twig

This is an arguably opinionated implementation of #1566: just remove Selectize and replace it with nothing.
The available alternatives come with loads of features while we essentially use none. So even "only 23 kB gzipped" is 23 kB mostly unneeded. We use it in two places, for languages in the header and organizations on the login form. The standard dropdowns work just fine there in my opinion.
We can add more complex comboboxes when we have something that actually needs them.

Remove selectize

---

modules/admin/lib/Controller/Config.php

Fixes #1570
This matches what is used in `modules/core/www/frontpage_config.php` for the classic UI.

Fix: Predis\Client class name

---

config-templates/config.php
docs/simplesamlphp-upgrade-notes-2.0.md
lib/SimpleSAML/Logger.php
lib/SimpleSAML/Logger/FileLoggingHandler.php

strftime is deprecated and will be removed in PHP 9. SSP 2.0 is our chance to change this format as it's exposed to installers of SSP.
The approch is to keep it simple and just change the format to PHP's built in date() function which remains supported, in one go. As this is SSP 2.0 we're already breaking some config options, and if we make the jump now we can keep the code simple after instead of painstakingly trying to keep compatble also with the old format.
Also we do not try to localize the logging date/timestamps anymore. This matches the syslog approach that this format tried to mimic. We are using the day without leading zeroes now also to be a bit closer to how syslog does it. All just keeping things simple, which is what logging should be.
Likely not many installs are even using …

Change logging date formatting string from strftime() to date().

---

composer.json
composer.lock
lib/SimpleSAML/Session.php

This PR takes care of all deprecation issues.
This is necessary because PHP 8.1 will treat deprecations as exceptions instead of warnings.

2.0:  PHP 8.1 support

---

modules/core/docs/authproc_attributealter.md
modules/core/lib/Auth/Process/AttributeAlter.php
tests/modules/core/lib/Auth/Process/AttributeAlterTest.php

Use case for this would be to run two consecutive AttributeAlter filters using different source attributes, but the same target-attribute. It is implemented in a backwards compatible way, however, I feel that merging would be the logical default.

AttributeAlter:  Add option to merge target attribute values

---

templates/base.twig

This should prevent issues with e.g. Javascript when using SSP to log into MS applications via their embedded browsers. WIth this setting it should be maximally modern.

Instruct embedded IE to behave like the most modern browser they can

---

lib/SimpleSAML/Metadata/Sources/MDQ.php

According to my understanding of the MDQ RFC, the Accept HTTP header is mandatory:
All metadata query requests MUST include the following HTTP headers:
Accept - this header MUST contain the content-type identifying the
type, or form, of metadata to be retrieved.  See section 5.3.2 of
[RFC7231].

add Accept HTTP headers to MDQ queries

---

config-templates/config.php
lib/SimpleSAML/Utils/EMail.php
lib/SimpleSAML/XHTML/Template.php

The PR changes the following:
- Exposes Template::getContents, so Twig templates can be used for other things besides showing web pages (i.e. mail templates)
- Change the EMail utility class to use the newly exposed getContents in favour of calling `render()` on the Twig environment. This will make it possible to use templates provided by modules.
- Change the Email utility class constructor so custom templates can be passed.
These changes should not affect backwards compatibility.

Feature: generic templating / emailing

---

docs/simplesamlphp-changelog.md
modules/core/www/frontpage_federation.php

While it might no longer be needed in the twig-based 2.* version, this is an improvement for the federation-page and translated names that would display as "Array" in the twig-layout of 1.19

translation fixes for twig templates

---

lib/SimpleSAML/Metadata/Sources/MDQ.php

I was getting errors like this while testing the mdq component:
May 23 02:41:48 liblynx simplesamlphp[274543]: 3 [553de61cdc] Error writing MDQ result to cache: The file "/var/simplesamlphp/mdq-cache/sp-check/saml20-idp-remote-a3fb2fc38422855a65925d1cdbf96c1e2f654b22.cached.xml" does not exist
Looking at the code, it seems they were coming from this line:
$file = new File($cacheFileName);
Per vendor/symfony/http-foundation/File/File.php, the constructor by default raises FileNotFoundException unless the optional second parameter is set to $false. I considered adding that parameter, but it looks like the only thing the File object was used for is to pull out the string filename of the file it was created with? So I just removed the object and used the string directly.
Then if the content …

A couple of mdq cache bugs

---

modules/core/docs/authsource_selector.md
modules/core/lib/Auth/Source/AbstractSourceSelector.php
modules/core/lib/Auth/Source/IPSourceSelector.php
tests/modules/core/lib/Auth/Source/IPSourceSelectorTest.php

The PR introduces a new AbstractSourceSelector that can be used to delegate authentication to secondary auth sources based on a policy decision. The first implementation of this is the included IPSourceSelector which picks the secondary auth source based on the user's IP address (i.e. internal or external client).

Feature: Add auth source selector

---

modules/saml/src/Auth/Source/SP.php
tests/modules/saml/src/Auth/Source/SPTest.php

Make sure the `saml:IDPList` and `IDPList` parameters are not overloaded. From now on, saml:IDPList is being used when SSP is used as a proxy while the IDPList parameter is used when SSP is used as in SP-mode and you want to apply scoping to your AuthnRequest.
See https://github.com/simplesamlphp/simplesamlphp/pull/1563 and  for the full explanation of the changes.
Solves https://github.com/simplesamlphp/simplesamlphp/issues/1562

Refactor scoping code in the SP class

---

docs/simplesamlphp-googleapps.md
docs/simplesamlphp-reference-sp-remote.md
docs/simplesamlphp-upgrade-notes-2.0.md
metadata-templates/saml20-sp-remote.php
modules/saml/src/IdP/SAML2.php

We are unable to generate persistent NameIDs based on `simplesaml.nameidattribute`, since we have removed this attribute.
The only way to generate a persistent NameID is to use the appropriate authproc-filter.
This PR cleans up old code & logs and checks point 6 of #1643

Fix NameID generation

---

config-templates/config.php

Any chance `store.redis.password` can be documented in `config-templates/config.php` ?
Support for this option was previously added in https://github.com/simplesamlphp/simplesamlphp/pull/1012 and is documented at https://simplesamlphp.org/docs/1.17/simplesamlphp-maintenance.html#configuring-redis-storage

Document store.redis.password in config.php template.

---

config-templates/config.php
docs/simplesamlphp-maintenance.md
src/SimpleSAML/Store/RedisStore.php
tests/src/SimpleSAML/Store/RedisStoreTest.php

This library currently supports connections to a password-protected Redis instance ([documentation](https://simplesamlphp.org/docs/1.17/simplesamlphp-maintenance.html#configuring-redis-storage)).
However, there are two ways to protect Redis ([documentation](https://redis.io/commands/auth/)):
1. Legacy password protection (config directive `requirepass` in `redis.conf`)
2. Or [ACL's](https://redis.io/docs/manual/security/acl/), which provide control over what commands and keys a client has access to ; those are especially useful when securing a Redis server used by multiple applications
As of Redis 6+, ACL's are the preferred way to protect a Redis instance ([documentation](https://github.com/redis/redis/blob/6.0/redis.conf#L784-L788)). Note that the legacy password protection still works …

Support ACL's when connecting to Redis store.

---

www/saml2/idp/metadata.php

This allows metadata aggregators to cache IdP metadata.

Emit ETag header for IdP metadata

---

www/saml2/idp/metadata.php

Sending the `Etag` header was only one part. This MR implement the other part.
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

Actually handle ETag/If-None-Match logic

---

composer.json
composer.lock
src/SimpleSAML/Locale/TwigTranslator.php

This turned out to be slightly less straight forward than expected. I wasn't sure what to do with the new getLocale() method that 3.x requires.
TwigTranslator is a wrapper around an inner callback, the actual implementation then passes in \SimpleSAML\Locale\Translate::translateSingularGettext(), which already now ignores the passed langcode anyway and is also just a wrapper around gettext, whose interface also doesn't expose the active language and internally relies on the locale API.
Unless \Symfony\Bridge\Twig\Extension\TranslationExtension ever decides to use that method or this implementation is used in another context, it doesn't matter. And that seems very unlikely, so I just went with a hardcoded en.
For context: https://github.com/symfony/symfony/issues/40380
Like the other return …

Translation contracts

---

docs/simplesamlphp-artifact-idp.md
docs/simplesamlphp-hok-idp.md
docs/simplesamlphp-idp.md
metadata-templates/saml20-sp-remote.php
modules/core/docs/authproc_attributelimit.md
modules/saml/routing/routes/routes.yaml
modules/saml/src/Auth/Source/SP.php
tests/modules/saml/src/Auth/Source/SPTest.php

This is an approach to solving #1684.
We keep all the benefits of the new structure (controllers, routes etc). The single thing that this changes is which string is used to identify the route. This means that we reap all the benefits while at the same time not cause any unnecessary migration pain on this front. Changing the ACS requires not just the deployer to do something but to coordinate with potentially many IdPs, while we can easily avoid this.
The ACS is used for machine consumption, not to be typed by a human, so which exact string is in the URL really doesn't matter. It's just a number of characters to identify it.
In my opinion this solution is simple and does not require to add more code, require people to upgrade a 1.19 install first and then exchange metadata and then …

Keep the ACS url as it was in 1.19

---

config-templates/config.php
docs/simplesamlphp-maintenance.md
src/SimpleSAML/Store/RedisStore.php
tests/src/SimpleSAML/Store/RedisStoreTest.php
tests/src/SimpleSAML/Store/StoreFactoryTest.php

I needed this library to support [Redis-Sentinel](https://redis.io/docs/manual/sentinel/) so I picked up the work started in #1137 / #701 and rolled a new patch (based on e57536d311330a781d6a1ad8d7c1f2fe60fbc35e) that applies against the current master (2.x).
According to the [release notes](https://github.com/simplesamlphp/simplesamlphp/releases/tag/v1.19.6) 1.19.6 was the very last release in the 1.x branch so I won't open a pull request against 1.x.
The patch works fine on my side. There is a gotcha about password-protected instances which does not appear to be documented in the [predis documentation](https://github.com/predis/predis/blob/main/README.md) (I only found out about this via [this comment](https://github.com/predis/predis/issues/783#issuecomment-1191192483)), so I added …

Add support for Redis-Sentinel

---

config-templates/config.php

Fix some minor syntax nits in the (commented out) examples in config.php.
The one that always catches me is the missing comma at the end of theme.header, and that's what prompted this. However, I've tried to find other issues and fix those at the same time too.

Fix syntax errors in examples

---

docs/simplesamlphp-googleapps.md
docs/simplesamlphp-upgrade-notes-2.0.md
metadata-templates/saml20-sp-remote.php
modules/core/docs/authproc_targetedid.md
modules/saml/docs/nameid.md
modules/saml/src/Auth/Process/AttributeNameID.php
modules/saml/src/Auth/Process/PersistentNameID.php
modules/saml/src/Auth/Process/SQLPersistentNameID.php

The upgrade notes for 2.0 note that the user id attribute in core:TargetedID has been renamed 'identifyingAttribute'. Similarly, the new PairwiseID and SubjectID filters use 'identifyingAttribute' as well, as does the [consent module](https://github.com/simplesamlphp/simplesamlphp-module-consent/pull/13).
That creates a situation where some NameID-related authproc filters use 'attribute' and some use 'identifyingAttribute' to configure the user-identifying attribute.
It might be desirable to create some consistency and standardise on identifyingAttribute. This pull request does that.
It also updates the documentation in modules/core/docs/authproc_targetedid.md to match the earlier change for core:TargetedID.

Make all NameID authproc-filters use identifyingAttribute

---

config-templates/authsources.php
docs/simplesamlphp-upgrade-notes-2.0.md
metadata-templates/saml20-idp-hosted.php
modules/saml/docs/sp.md
modules/saml/src/Auth/Source/SP.php
src/SimpleSAML/Metadata/MetaDataStorageHandlerFlatFile.php
tests/modules/saml/src/Auth/Source/SPTest.php
tests/src/SimpleSAML/Metadata/MetaDataStorageHandlerTest.php
tests/src/SimpleSAML/Metadata/test-metadata/source1/saml20-idp-hosted.php

Update the examples and documentation for saml:SP to be consistent with the notion that entityIDs are no longer
dynamically generated if the 'entityID' config option is null.

entityID change affects saml:SP too

---

src/SimpleSAML/Metadata/SAMLParser.php

Storing this in each parsed entity has a significant performance impact. It was originally added in fe80b8ad59fd1a07e8ff1eadd234318a083466f5 for use by the 'aggregator' module, which is now replaced by the 'aggregator2' module which does not use this field.

Remove storing entire original entityDescriptor in parsed metadata

---

src/SimpleSAML/Locale/Translate.php
tests/src/SimpleSAML/Locale/TranslateTest.php

Currently, the translateFromArray filter has no fallback to a default locale/language. This makes it behave differently to the trans tag/filter in Twig and the old translation system. It can result in nothing being displayed even though the array it is passed contains an entry matching the default language (hardcoded as 'en').
Because this is a static function, determining the 'language.default' from the config is expensive. But the existing trans filter (as implemented in TwigTranslator.php) already uses Language::FALLBACKLANGUAGE as the default locale and that class is already loaded. So using that constant here is consistent with the other Twig translation functions.

translateFromArray needs a FALLBACKLANGUAGE

---

src/SimpleSAML/Configuration.php

I'm am certainly no psalm expert. In my attempts to add more psalm to the ratelimit module psalm was complaining that Configuration's getOptionalString could never return null even if default is null. I think that psalm maybe doesn't understand `$default is set` since when I changed it to `$default is null` or `$default is string` (and adjust ternary expression) then psalm stopped complaining.
Open to other ideas.

Psalm seems to think of "set" as a type

---

modules/cron/bin/cron.php

The bin script detects if module is enable and if not, lets the user know how to enable it. Update message to reflect SSP2 way of enabling a module.

Fix `cron/bin/cron.php` message that tells how to enable module

---

docs/simplesamlphp-customauth.md

It appears that the custom auth classes (i.e. UserPassBase) were moved from the modules/core/lib to modules/core/src.  Likewise, when creating a custom auth source, I found that the path in my module needs to match this path (e.g. modules/mymodule/src instead of modules/mymodule/lib).  Updated documentation page to reflect the change.

Adjusted module path from "lib" to "src"

---

docs/simplesamlphp-reference-idp-hosted.md
docs/simplesamlphp-reference-sp-remote.md
modules/saml/src/IdP/SAML2.php
modules/saml/src/Message.php

This would encode all attributes sent by the IdP (or decode received by the SP) with base64. As far as I could deduce this is from the early days of federation, used nowhere anymore, no one came forward that did, but cannot get certainty. Best way to find out might just be to drop it and the 2.0 release seems the good moment. We can easily reinstate it if some use case does turn up.
Note that the IdP can still perform this behaviour with the more generic attributeencodings feature.

Remove base64attributes feature

---

src/SimpleSAML/Database.php
src/SimpleSAML/Logger.php
src/SimpleSAML/Logger/FileLoggingHandler.php
src/SimpleSAML/Utils/HTTP.php

Avoid misuse of array_push. PHP 8.x allow us to use the faster `str_contains()`

Micro optimisation and lower memory footprint

---

src/SimpleSAML/Session.php

- Import SimpleSAML\Session twice case warnings.
- Remove other unused imports.

Another definition with same name exists in Session class

---

src/SimpleSAML/Database.php

This will need to be done at some point, and 2.0 seems the right time to break things.

Remove legacy database.slaves option support

---

modules/multiauth/docs/multiauth.md
modules/multiauth/src/Auth/Source/MultiAuth.php
tests/modules/multiauth/src/Controller/DiscoControllerTest.php

The old format has been replaced with a new format in SSP 1.9. The new format makes sense and it's now time to stop supporting the legacy format.

Remove sources format for multiauth replaced in 1.9

---

modules/multiauth/docs/multiauth.md
modules/multiauth/src/Auth/Source/MultiAuth.php
modules/multiauth/src/Controller/DiscoController.php
modules/multiauth/templates/selectsource.twig
resources/css/default.scss
tests/modules/multiauth/src/Controller/DiscoControllerTest.php

- Fix several bugs to make it actually work; it was broken in several ways probably due to refactoring in SSP.
- Simplify code a lot, also make use of things we have already available now.
- Move presentation concerns to the template and use standard functionality for translation
A small change needed to be made in the name of the `css_class` setting (previously `css-class`) in the name of simplicity, it seemed better to change that now than to carry more code to convert the name.

Fix and improve multiauth module

---

src/SimpleSAML/Locale/Localization.php

It is quite fine if e.g. a theme does not have its own locales dir. The exception is already caught, so the application does not actually stop. So, notice it but do not raise high alarms.

Tone down the error level of missing locale dirs

---

docs/simplesamlphp-install-repo.md
docs/simplesamlphp-install.md

Hi, 
since package.json file got removed from simplesamlphp repo in https://github.com/simplesamlphp/simplesamlphp/commit/ad9641785d5e3053ebdaf03d6c32e1e3b273cb11
the instruction in docs related to SSP installation to run the following commands doesn't apply any more:
```
npm install
npm run build
```
This PR simply removes this from docs.
Best regards

Remove instruction to run npm install/build from install docs

---

modules/core/routing/routes/routes.yml
modules/core/src/Controller/Exception.php
modules/saml/routing/routes/routes.yaml
modules/saml/src/Controller/ServiceProvider.php
src/SimpleSAML/Auth/Simple.php
tests/modules/saml/src/Controller/ServiceProviderTest.php

Restores the functionality to trigger authentication by URL.
To not expose individual authsources like we did before, a check was added to test the passed authsource to be saml:SP. Those are the only ones safe to expose like this.
Closes #1682

Reinstate url-based authentication

---

.github/workflows/php.yml
psalm-dev.xml
psalm.xml
tests/modules/core/src/Auth/Process/TargetedIDTest.php
tests/modules/core/src/Controller/LogoutTest.php
tests/modules/cron/src/Controller/CronTest.php
tests/modules/saml/src/Auth/Source/SPTest.php
tests/modules/saml/src/Controller/MetadataTest.php
tests/modules/saml/src/Controller/ServiceProviderTest.php
tests/src/SimpleSAML/LoggerTest.php
tests/src/SimpleSAML/Metadata/MetaDataStorageHandlerTest.php
tests/src/SimpleSAML/Metadata/SAMLBuilderTest.php
tests/src/SimpleSAML/Store/StoreFactoryTest.php

This PR will split psalm-configuration in two and run on our testsuite on a lower errorLevel.
We only want to know about _real_ issues like missing params, not every possible null-value.

Run psalm on testsuite with a different errorLevel

---

docs/simplesamlphp-changelog.md
modules/admin/src/Controller/Test.php
modules/core/public/assets/js/loginuserpass.js
modules/core/templates/loginuserpass.twig
src/SimpleSAML/Auth/Simple.php

This PR fixes two issues with the back-button;
The JavaScript-part makes sure the submit-button becomes enabled again.
Now after fixing this, a new problem arised; the restart-url would be triggered to restart the authentication, but we used `getLoginURL` to generate it, which was recently limited to only work for SP-authsources. The second fix is therefor to properly set a restart-url that works for non-SP authsources.
Closes #1720

Bugfix: Fix use of back-button

---

docs/simplesamlphp-changelog.md
modules/saml/src/Controller/ServiceProvider.php

Reference parameters need to be explicitely marked as such in the arguments array when using call_user_func_array().
Fixes the following exception:
```
SimpleSAML\Error\Exception: Warning - Parameter 1 to SimpleSAML\Auth\Source::completeLogout() expected to be a reference, value given at .../vendor/simplesamlphp/simplesamlphp/src/SimpleSAML/HTTP/RunnableResponse.php:72
Backtrace:
4 .../vendor/simplesamlphp/simplesamlphp/public/_include.php:86 (SimpleSAML_error_handler)
3 [builtin] (call_user_func_array)
2 .../vendor/simplesamlphp/simplesamlphp/src/SimpleSAML/HTTP/RunnableResponse.php:72 (SimpleSAML\HTTP\RunnableResponse::sendContent)
1 .../vendor/symfony/http-foundation/Response.php:394 (Symfony\Component\HttpFoundation\Response::send)
0 …
```

Fix logout completion for SP

---

modules/admin/src/Controller/Federation.php
modules/admin/templates/federation.twig
modules/saml/src/IdP/SAML2.php
src/SimpleSAML/Metadata/MetaDataStorageHandler.php

It gets quite fiddly to get this right. The actual metadata (hosted on the `host` itself) is alreafy correct because the URL generator uses the 'current' entity metadata and current URL. The admin interface of course presents all entities in one page and hence cannot rely on the current URL. Therefore we need to override the url host for this specific display case.
Closes: #1774

Correct host in generated URLS for IdPs with 'host' config in admin/federation

---

docs/simplesamlphp-changelog.md
src/SimpleSAML/IdP.php
src/SimpleSAML/IdP/LogoutHandlerInterface.php
src/SimpleSAML/IdP/TraditionalLogoutHandler.php

Closes #1776
The assocId is nullable for IdP-initiated SLO

Restore nullable assocId for SLO

---

modules/admin/locales/fr/LC_MESSAGES/admin.po

Hi,
While implementing/upgrading to SimpleSamlPHP 2.0.4 i noticed that a lot of translations were missing on modules.
Please find here a full French translation for module Admin ( modules/admin/locales/fr/LC_MESSAGES/admin.po)
Regards,
Ludovic

full french translation of admin.po (admin module fr locales)

---

modules/saml/src/Auth/Source/SP.php
modules/saml/templates/proxy/invalid_session.twig

The invalid session handler currently generates a redirect to a legacy URL (saml/proxy/invalid_session.php) whereas routing has been updated to locate this at a new URL (saml/proxy/invalidSession)
To reproduce the current bug:
* have the saml:SP module set up to support multiple IdPs
* log in with one IdP
* try to log in with a second IdP while the first session is still valid
This patch fixes that bug, and also adds pure styling to the twig template so that the buttons appear consistent with the rest of the new UI.
I've not tried to preserve the legacy URL as nothing outside the current SSP instance should point to it.

Fix invalid session error

---

config/config.php.dist
src/SimpleSAML/Store/RedisStore.php
tests/src/SimpleSAML/Store/RedisStoreTest.php

generate selected SSL context options for the Predis client.
see https://www.php.net/manual/en/context.ssl.php
closes #1804

add support for TLS configuration for Redis Store

---

src/SimpleSAML/Metadata/SAMLBuilder.php

This matches both the code, and the code comments, [the documentation](https://simplesamlphp.org/docs/stable/simplesamlphp-metadata-extensions-attributes.html) and the behaviour of 1.19 so it seems to be a bug due to refactoring that it was changed to Unspecified in 2.x.

Default for entity nameformat when not set should be uri

---

public/saml2/idp/SingleLogoutService.php

> Fatal Error: Cannot use 'Request' because the name is already in use.
I know that is already fixed in main branch, but the Drupal module "Simplesamlphp Auth" will be use the next release 2.1 in their code as dependency, so it would be nice if this bug could be fixed.
See: [Drupal Simplesamlphp Auth issue](https://www.drupal.org/project/simplesamlphp_auth/issues/3349278)

Duplicate use statement for Request class.

---

docs/simplesamlphp-install-repo.md

I hope this cuts down on support questions for people checking out master branch for their deploys.
Probably worth apply to SSP 2.1 and 2.2 branches as well, for when those make the next stable documentation.

Update docs to recommend use a tag when installing through git checkout

---

modules/saml/src/Auth/Source/SP.php

Same message exists in `src/SimpleSAML/Metadata/MetaDataStorageHandlerFlatFile.php`.

Use unique exception message to avoid confusion

---

bin/initMDSPdo.php

This PR fixes static call for non static method in bin/initMDSPdo.php, which raises fatal error in PHP v8.1.
```bash
www-data@5657578d7e53:~/projects/simplesamlphp/simplesamlphp-2.1$ php bin/initMDSPdo.php
PHP Fatal error:  Uncaught Error: Non-static method SimpleSAML\Utils\Config::getConfigDir() cannot be called statically in /var/www/projects/simplesamlphp/simplesamlphp-2.1/bin/initMDSPdo.php:11
Stack trace:
#0 {main}
thrown in /var/www/projects/simplesamlphp/simplesamlphp-2.1/bin/initMDSPdo.php on line 11
Fatal error: Uncaught Error: Non-static method SimpleSAML\Utils\Config::getConfigDir() cannot be called statically in /var/www/projects/simplesamlphp/simplesamlphp-2.1/bin/initMDSPdo.php on line 11
Error: Non-static method SimpleSAML\Utils\Config::getConfigDir() cannot be called …
```

Fix static call for non-static method in bin/initMDSPdo.php

---

config/config.php.dist

Only 'admin' is enabled additionally, 'core' and 'saml' are enabled by default in \SimpleSAML\Module::isModuleEnabled().

Clarify enabled by default modules

---

docs/simplesamlphp-googleapps.md

Two of the code examples on the google apps documentation page contain invalid PHP code. This is a documentation only change to fix the examples.

Fix minor code error in documentation for setting up google apps

---

src/SimpleSAML/Module.php

Fixes TypeError. To reproduce visit `/module.php` _without_ any trailing characters, not even a trailing slash.

Harden module.php endpoint against no input

---

.github/workflows/php.yml
composer.json
composer.lock
docs/simplesamlphp-install.md
modules/admin/src/Controller/Config.php

We currently require `ext-intl`, however we cannot be sure that people using the tarball have installed it.
This PR installs a polyfill that will ensure English translations will always work, with or without `ext-intl`. The `ext-intl` extension has been downgraded to `optional`; only install for non-English deployments.
This ensures people deploying using the tarball will not run into nasty fatal errors like [this one](https://github.com/simplesamlphp/simplesamlphp/issues/1890#issuecomment-1807524926).
Closes #1890

Bugfix for intl-extension

---

modules/core/templates/short_sso_interval.twig

The "Retry login"-button value is missing opening braces, thus displaying the literal string.

Fix core:WarnShortSSOInterval template

---

src/SimpleSAML/Utils/System.php

For the trick to work, the file needs to be on the same filesystem. The tempdir is likely not on the same filesystem so the rename will not be instantaneous. This probably worked in the past when the tempdir was expected to be a subdir of the SimpleSAMLphp installation.
Fix it by writing a file to the same directory as the target file, which will always be on the same FS. Also do not just use a `rand()` number but something more random as we do in other places in the code.

Fix atomically writing to a file

---

docs/simplesamlphp-changelog.md
modules/saml/src/Auth/Source/SP.php

We introduced the ability to proxy RequestedAuthnContext in #833. However, if we're doing that, we must also consider what happens during authentication when the RequestedAuthnContext doesn't match the AuthnContext we have in a cached session.
If we don't compare what we have against what's requested, we may miss a request to step up authentication (e.g. when MFA is required by a specific service). This results in a poor user experience where they've got an IdP behind the proxy that is capable of meeting the request, but have to log out/terminate their SSO session to trigger it.
This patch tries to fix that by comparing whats in our session with what was requested, and triggering authentication again if they don't match. It only uses an exact comparison since we've no way of comparing …

Handle AuthnContextClassRef changes when proxying

---

src/SimpleSAML/Command/UpdateTranslatableStringsCommand.php

This should hopefully minimize the number of changes that git sees when storing these files in a repo
Note that some of the header metadata is not cloned at the moment. If this ordering fixes the issue that was causing git chatter then the metadata clone can be added before merge.
Tested using
```
cd ./bin
./translations translations:update:translatable
vi ../locales/en/LC_MESSAGES/messages.po
```

A first attempt at storing generated po files in sorted order. 

---

.github/workflows/php.yml
src/SimpleSAML/Locale/Localization.php

If there is no `.mo` file available then fall back to loading the `.po` file instead. This should allow installations to still function even if installed with modules that have uncompiled translations and when SSP is installed as a dependency via composer.
Perhaps we should rename `loadGettextGettextFromPO` to `loadGettextForDomain` or something. The caller is not so likely to care if they come from mo or po files or whatnot, that is an implementation detail.

i18n: fall back to loading the po file if the mo file is not available

---

docs/index.md
docs/simplesamlphp-developer-information.md

Some documentation for new and returning developers. This is a place for information about the code which might help developers come up to speed about the code and know what branch to checkout and how some common code flows work (for example a login). 
This is a bit free form at the moment. I am adding sections as I am researching the code in the hopes that the information is of use to others.
Perhaps as well information about testing code and modules for developers could be gathered here. 
It was mentioned on slack that this might be better moved to the wiki. The wiki is not widely linked and this stage and moving things from docs/ to the wiki is likely better handled as a separate task once a clear policy on what should be in docs and what should be in wiki is established.

docs: adding some documentation aimed at new and returning developers

---

docs/simplesamlphp-upgrade-notes-2.0.md

I also moved the entityID point to the top as it seems to be the most common question about upgrading from 1.x to 2.x.
Most of the other information added at the end of document was obtained from slack so might not be 100% the opinion of core developers. Some extra eyes are appreciated, if we can get this info extended and updated in one place that should help everybody.
It also might be useful to mention / link to the 2.0 upgrade notes in the 2.1 upgrade notes. Something like the following: If you are upgrading from a 1.x series release please see the 2.0 upgrade notes (linked) to ensure a smooth transition.

docs: update the upgrade notes for 2.0 with some information from slack about entityIDs

---

config/authsources.php.dist
docs/simplesamlphp-idp.md
modules/exampleauth/src/Auth/Source/UserPass.php

I've been using `exampleauth:UserPass` to test functionality without the need to setup more complex authsources. Over the past week or so I've been tripped up a few times by an inconsistency in `exampleauth:UserPass`, where it doesn't allow any additional configuration in `authsources.php` due to assuming all top level keys are `username:password` pairs.
This PR moves those `username:password` strings under the `users` key, such that other configuration can be added / tested. My latest example of the need for this is trying to add `core:loginpage_links` configuration to `exampleauth:UserPass` configuration in `authsources.php`. With this PR, `core:loginpage_links` links are rendered on the login page for `exampleauth:UserPass`, if configured. Prior to this PR, you get an error when trying …

Configure exampleauth:UserPass credentials in "users" key, not top level config

---

src/SimpleSAML/Locale/Localization.php

Loading from po files is slightly different than the existing path for mo files. The domain from the po file has to be removed in order for the loaded translation to be found by SSP.
This relates to https://github.com/simplesamlphp/simplesamlphp/issues/2009.

i18n: when loading from po file the domain from the file has to be wiped

---

docs/simplesamlphp-maintenance.md
src/SimpleSAML/Metadata/MetaDataStorageHandlerDirectory.php
src/SimpleSAML/Metadata/MetaDataStorageSource.php

A new MetaDataStorageHandlerDirectory class to load metadata from subdirectories
This is a retarget of the original PR https://github.com/simplesamlphp/simplesamlphp/pull/1984 from simplesamlphp-2.1 to simplesamlphp-2.3.
This is another attempt at loading metadata from a subdirectory containing either php or xml files (or both). This specifically allows SP files to be broken out into one file per SP if there are a number of SPs and you wish to maintain a list using one file per SP. 
It seems from the below links that the feature is desirable for a few users and having an implementation based on simplesamlphp-2.1 may allow a merge and closing of a long standing issue and long standing PR.
To be generic this also adds a `file` property to the config of the MetaDataStorageHandlerFlatFile …

update of pull/1984 against 2.3 (A new MetaDataStorageHandlerDirectory class to load metadata from subdirectories)

---

docs/simplesamlphp-customauth.md

When getting started with SimpleSAMLphp and creating my first custom authentication module, following [the docs](https://simplesamlphp.org/docs/devel/simplesamlphp-customauth.html), I hit a couple of minor issues where the docs seem to be slightly outdated when running against version 2.2.1:
**Outdated method signature for login method:**
The existing docs suggest creating a method with signature `protected function login($username, $password)`.  Doing so will result in the following error when attempting to test or use the module:
```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
3 src/SimpleSAML/Error/ExceptionHandler.php:35 (SimpleSAML\Error\ExceptionHandler::customExceptionHandler)
2 vendor/symfony/error-handler/ErrorHandler.php:535 …
```

Fixes to the custom username/password auth docs

---

src/SimpleSAML/Locale/Localization.php
src/SimpleSAML/Locale/Translate.php
src/SimpleSAML/XHTML/Template.php
tests/modules/core/src/Controller/ExceptionTest.php

This is a cleaned up version of the rough code to solve https://github.com/simplesamlphp/simplesamlphp/issues/2013.
The core module has only a few translations (25 ish) and seems like it should be available to all modules for translation. The current fallback translation ordering is module, core, then messages. I have been tinkering with the code at https://github.com/monkeyiq/simplesamlphp/tree/2024/march/i18n-domains2 which includes some translations in each of admin, core, and messages and an explicit callout to these in the federaion admin twig page. That let me see the three files are reachable from that page.

respect the gettext domain for modules

---

modules/saml/templates/proxy/invalid_session.twig
src/SimpleSAML/Command/UpdateTranslatableStringsCommand.php
src/SimpleSAML/Utils/Translate.php

I identified a number of issues in https://github.com/simplesamlphp/simplesamlphp/issues/2041 after starting a dive because a new string with `|trans` was not being picked up and added by the execution of
```
php bin/translations translations:update:translatable
```
I have played with a few configurations to `mergeWith` and this is the result. This should address the issues from 2041 and leaves a few new items open to further investigation. 
A next logical item is: If a translation was placed in the messages.po originally but is discovered only in the admin or saml modules then the script will want to place a translation into `modules/admin/locales/fr/LC_MESSAGES/admin.po` for example. This gives two locations in the `po` files for the same string. I am thinking about elevating the string …

i18n notice new strings, check hooks, dig deeper in twig dirs

---

config/config.php.dist
modules/saml/src/Controller/ServiceProvider.php

2 small fixes to config/config.php.dist so that it complies with PSR12, as defined in phpcs.xml.
1. Comment line 22 of phpcs.xml, to avoid phpcs failure.
2. Run the standards check:
```
phpcs --standard=phpcs.xml --extensions='dist' config/config.php.dist
```
3. Result:
```
-----------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
-----------------------------------------------------------------------------------------
61 | ERROR | [x] Whitespace found at end of line
278 | ERROR | [ ] Line exceeds maximum limit of 130 characters; contains 214 characters
-----------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY …
```

Fix config.php.dist coding standards

---

modules/saml/src/MetadataBuilder.php
src/SimpleSAML/Metadata/MetaDataStorageHandler.php

This goes hand in hand with https://github.com/simplesamlphp/simplesamlphp-module-adfs/pull/18
With these and https://github.com/simplesamlphp/simplesamlphp-module-adfs/pull/18 I can again see the ADFS metadata in the admin/federation page.
The next logical move is getting `getSecurityTokenService` to work again too. Perhaps phase one might be to directly reach out to it and then move to using a hook to call the function.

start to allow adfs metadata in the admin ui again

---

docs/simplesamlphp-changelog.md

I'm guessing this is manually maintained, and that the latest version of `sqlauth` will be pulled through in the simplesamlphp release. If so, the update in `sqlauth` was missed.

Add missing changelog entry for sqlauth adding username_regex option

---

src/SimpleSAML/Metadata/MetaDataStorageHandler.php

This relies on the hook being setup as with https://github.com/simplesamlphp/simplesamlphp-module-adfs/pull/20.

MetaDataStorageHandler::getGenerated uses a hook to allow ADFS metadata

---

src/SimpleSAML/Logger/FileLoggingHandler.php

`date()` does not support microseconds, but `DateTime` does.

Use DateTime() instead of date()

---

src/SimpleSAML/SessionHandlerPHP.php

when migrating from an old saml to a new one the session sometimes desn't deserialize, and it should just be thrown away at that point

---

src/SimpleSAML/SessionHandlerPHP.php

This is an update to https://github.com/simplesamlphp/simplesamlphp/pull/2065 which logs unsucessful unserialize(). The goal of these two PRs together is to allow SSP to be upgraded without errors appearing while also logging errors so that they can be seen if there is no upgrade and perhaps the storage is degrading or unserialize is failing for another reason.

log unserialize failures with descriptive message

---

modules/core/src/Auth/Process/AttributeLimit.php

Fixes https://github.com/simplesamlphp/simplesamlphp/actions/runs/9028875799/job/24810192242#step:11:19 as referenced in https://github.com/simplesamlphp/simplesamlphp/pull/1971#issuecomment-2104356390
```
Warning: PHP Warning:  Undefined array key "/^mail$/" in /home/runner/work/simplesamlphp/simplesamlphp/modules/core/src/Auth/Process/AttributeLimit.php on line 181
Warning: PHP Warning:  Undefined array key "/^mail$/" in /home/runner/work/simplesamlphp/simplesamlphp/modules/core/src/Auth/Process/AttributeLimit.php on line 181
```
The issue the warning is complaining about is handled in the first line of the `filterAttributeValues()` function anyway (it handles the second argument being null), so the warning this PR fixes was harmless and condition already handled. In any case, this PR …

Only filter attributes if there is actually a list of allowed values to filter on

---

modules/saml/docs/sp.md
modules/saml/src/Auth/Source/SP.php
modules/saml/src/Controller/ServiceProvider.php
tests/modules/saml/src/Controller/ServiceProviderTest.php

sp_request_initiation_protocol

---

modules/core/src/Auth/Source/AdminPassword.php
src/SimpleSAML/Error/ErrorCodes.php

In 2.3 and above non hashed admin passwords are not accepted any more. This warns the user and provides some insight to what went wrong and a link with more detail on the exact steps to fix it.
This is the opposite to https://github.com/simplesamlphp/simplesamlphp/pull/2110
This references https://github.com/simplesamlphp/simplesamlphp/wiki/Frequently-Asked-Questions-(FAQ)#failed-to-login-to-the-admin-page-with-and-error-message-admin-password-not-set-to-a-hashed-value for the solution so we can potentially make it more interesting if need be.

23: if the auth.adminpassword is not hashed provide some insight

---

.github/workflows/translations.yml

These updates allow a Translations workflow to complete. It is a bit annoying trying to make sure the access tokens are right for the checkout and push and this particular combination seems to work on the `monkeyiq/2024/may/ci-translations-test` branch I created for testing in the main git repo.
https://github.com/simplesamlphp/simplesamlphp/actions/runs/9297922087

CI: translations job update to allow fetch/push to complete

---

.github/workflows/php.yml
tools/linters/.eslintrc.js
tools/linters/.eslintrc.yml

eslint config commit fixes the Linter-job:
```
Oops! Something went wrong! :(
ESLint: 8.57.0
Error: ESLint configuration in --config » plugin:json/recommended is invalid:
- Unexpected top-level property "files".
Referenced from: /github/workspace/tools/linters/.eslintrc.yml
```
Issue here is that the old `.eslintrc.yml` file is deprecated and a new style .js file is required.
--------
cleanup job commit fixes a bug that before was undetected:
```
.github/workflows/php.yml:305:10: "{outputs: {}; result: string}" value cannot be compared to "string" value with "==" operator [expression]
|
305 |       needs.coverage.result == 'success' ||
|          ^~~~~~~~~~~~~~~~~~
```

Fix Linter + CI clean job

---

docs/simplesamlphp-metadata-endpoints.md
src/SimpleSAML/Configuration.php

Fixes #2130
Since this is broken anyway, I'd like to backport this to the 2.3 branch and add an upgrade note about it.

BC-break: remove deprecated single-string format for endpoints

---

src/SimpleSAML/Configuration.php
tests/src/SimpleSAML/ConfigurationTest.php

This is an update after single string and single array endpoints were removed. See https://github.com/simplesamlphp/simplesamlphp/pull/2131
Note that there are some heuristics that seem to have been implicit.
This will effect all endpoints ArtifactResolutionService, SingleSignOnService, and SingleLogoutService.
If there is no binding set then one is set for you. This matches the default value table from
https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-2.2/docs/simplesamlphp-metadata-endpoints.md
If there is only one end point in the array and the binding is not valid then it is refreshed for you to something that is valid.
On the other hand, for a list of end points no such refreshing is done so that the case of a non default Location with a valid Binding can be the one …

Update test suite for no single string endpoints

---

docs/simplesamlphp-install-repo.md

I have cited the Symfony site here rather than directly recommending commands like the following
```
mkdir /var/cache/simplesamlphp
chmod 700 /var/cache/simplesamlphp
chown apache /var/cache/simplesamlphp
```
This relates to https://github.com/simplesamlphp/simplesamlphp/issues/2139

docs: add info about cachedir to base install info

---

docs/simplesamlphp-install-repo.md

I don't think the user wants to go from a tag checkout to master here if they return to this doc file to perform an update.
I don't know if the composer command needs the windows additional options for the upgrade too. It seems that way.

docs: upgrade command should leave user on a tag checkout

---

locales/lb/LC_MESSAGES/messages.po

Fix typo
I added an ' to line 116 which said an d Passwuert. With my change it will say "d'Passwuert"

Added ' to d Passwuert

---

templates/post.twig

If a posted value is an array, this template iterates through it as 'index' and 'item' and then passes 'value' to the template where it should be 'item'. This is causing post values that are supposed to be the elements of arrays to be the string "Array" instead.

Fix bug in post.twig

---

templates/base.twig

See https://webhint.io/docs/user-guide/hints/hint-meta-charset-utf-8/?source=devtools for the reasoning behind this change. It's fully backwards compatible.

Use the appropriate way to set the charset in HTML5

---

src/SimpleSAML/Locale/Localization.php
src/SimpleSAML/Locale/Translate.php

If you have a module in use such as `multiauth:MultiAuth` and use are using a theme at the same time then you have (or should have) two default translation domains in action: the multiauth and the theme. This PR allows both of these to be in use and will allow a theme to see the module translation domain as well as it's own.
This bug was reported on the users mailing list.

i18n: allow a theme and module to work together

---

src/SimpleSAML/Module.php

This might help to debug when a class is renamed or moved to a new module.
This is a follow on to the thread "Unhandled exeception with v2.2.2" on google groups from today. I put the exists test inside the subclass one so it only runs when things are failing. 
Looking at the other side we should consider if we want this because although it is handy for debugging it does potentially allow probing for classes to see if they exist and perhaps leak information about what version is installed or what modules are available.

In Module::resolveClass throw a different error for class not found

---

.github/workflows/php.yml
modules/core/src/Controller/Login.php
src/SimpleSAML/Error/Error.php
src/SimpleSAML/Error/ErrorCodes.php
src/SimpleSAML/Module.php
tests/src/SimpleSAML/Error/ErrorTest.php

This is a version of https://github.com/simplesamlphp/simplesamlphp/pull/2181 without the test suite update.
I found a few side issues while trying to get the test suite update going so thought I would split out the code code here for consideration.
The goal is to allow a custom ErrorCodes subclasses to be used and have Login keep that association and be able to present information from those custom error codes on the web page.
This is an update to https://github.com/simplesamlphp/simplesamlphp/pull/2181
This relates to and should resolve issue https://github.com/simplesamlphp/simplesamlphp/issues/2133
The ErrorCodes subclass name needs to be saved in the state information in order to set data['errorcodes'] to the custom error code class later in the login method.
To restrict which …

Allow custom ErrorCodes subclasses through Login::handleLogin no test suite version

---

src/SimpleSAML/Metadata/Sources/MDQ.php

Fixes #2199 
* The MDQ cache file is now explicitly decoded as an associative array to match subsequent code expectations.
* The MDQ cache file is overwritten instead of appended to, to prevent an ever-growing corrupt JSON file.
* The cache file extension was updated to `.json` instead of `.xml` to better reflect the content of the file.
* If this change isn't wanted, please let me know and I can revert it.
* I believe this change will also help anyone impacted by the growing cache file since the application will immediately stop trying to read a large file into memory.
The steps to reproduce from the linked issue verifies that the application is no longer re-querying MDQ metadata on every request, and the `<FILE> wasn't an array` errors are no longer appearing in the logs.

Fix MDQ cache file bugs

---

src/SimpleSAML/Metadata/Sources/MDQ.php

As mentioned in some of the review comments for PR #2200.
This is a small PR to update a comment and sprinkle around `JSON_THROW_ON_ERROR`.

An update to the MDQ PR #2200

---

src/SimpleSAML/Locale/Language.php
tests/src/SimpleSAML/Locale/LanguageTest.php

Changing this line allows Portuguese (Brazil) to be selectable from the language menu again in 2.3.
Note that setLanguageCookie() and getLanguageCookie() also contain forced lower casing which is worth investigating too in order to make sure things do not fall through the cracks there.

i18n in 2.3 allow Brazilian to be selected again

---

docs/simplesamlphp-upgrade-notes-2.3.md
modules/core/src/Auth/Source/AdminPassword.php
src/SimpleSAML/Logger.php

This is a follow up to https://github.com/simplesamlphp/simplesamlphp/pull/2222.
I added a new `deprecated` method to Logger. I think this is useful as there are many parts of the code that have `@depcreated` in comments. If that code is wanting to issue a warning then using a specific logger method signals exactly what the intent is.
The upgrade-notes-2.3.md are a little more complex but I tried to make the 2.3.1+ case the default and read easily for folks who are upgrading from 2.2 to 2.3.1+. I notice that the changelog is already updated https://github.com/simplesamlphp/simplesamlphp/commit/023688b50470076e04217726a3618f93e0e82797  to reflect the changes in https://github.com/simplesamlphp/simplesamlphp/pull/2222
We could refine the `Logger::deprecated` to have it's own DEPRECATED=8 …

plain text admin password follow-up

---

src/SimpleSAML/Logger.php

I added the Logger deprecated method in https://github.com/simplesamlphp/simplesamlphp/pull/2223 to allow a clear statement that a logging message is about deprecated functionality that will be removed. 
The use in 2223 is not needed in master as the functionality was removed from there. The `deprecated` method is brought forward without a caller so it is not "missing" from master and doesn't cause an issue in the future if some code calling it is cherry picked.

bring the Logger deprecated method forward from 2.3

---

docs/simplesamlphp-changelog.md
modules/admin/templates/metadata_converter.twig
templates/_table.twig
templates/base.twig

Closes #2228
The whitespace-issue turns out to be not a clipboard.js issue, but appears to be related to the `<pre>`-tag.

Fix deprecation of Twig spaceless-filter

---

modules/saml/src/IdP/SAML2.php
src/SimpleSAML/Configuration.php

The new feature from f99217b43 only worked if a signing cert was present. With no certs present, getPublicKeys threw an exception. Fixed the call from encryptAssertion to getPublicKeys to not require that a key be returned.
Also fixed logic in getPublicKeys
in Configuration.php. Previous logic would return an empty array if a use type was passed in but no keys of that type were found even if required was set to true. Thus, the encryptAssertion bug didn't appear until we had an SP with no certs at all rather than just one without an encryption cert.

Fixes to encryption optional

---

docs/simplesamlphp-sp.md

The endpoints docs were updated here https://github.com/simplesamlphp/simplesamlphp/commit/28f21e762ad80cbbdd661cf0381b0da0b7411e93 to remove the single string format.
This PR updates the Service Provider QuickStart to not used the old single string format.
This was reported in https://github.com/simplesamlphp/simplesamlphp/issues/2258

docs: update SP example to use the non string endpoint format

---

docs/simplesamlphp-upgrade-notes-2.3.md

I realize the endpoint format change may have been omitted from the breaking change section because of the "9-year" deprecation. That, however, does not change the fact that it is actually a breaking change. This was also identified as a breaking change in the [commit](https://github.com/simplesamlphp/simplesamlphp/commit/f0189fd1e69e2d92034c5818d4b8a2586d270483) message.

Move the endpoint breaking change to the "BC break" section

---

docs/simplesamlphp-idp.md

The dated example was cited on slack. This freshens the example to using the array format which is the only way now as shown in simplesamlphp-metadata-endpoints.md.

docs: use array format for ACS and SLS info in idp doc page

---

.gitattributes

This adds syntax highlighting to the various `*.php.dist` files (such as those in `config` and `metadata`.

syntax highlighting for php.dist files

---

metadata/saml20-sp-remote.php.dist

Update the endpoints in the php.dist files to the new only array of arrays format.
Raised in https://github.com/simplesamlphp/simplesamlphp/issues/2258

dist files: update endpoints to new array only format

---

src/SimpleSAML/Locale/Language.php

It seems that even after #2305, 2.3.3 still has one erroneous mention of `st`. This just results in a superfluous warning in the logs (it doesn't actually affect translations).

Remove remaining erroneous mention of st

---

docs/simplesamlphp-install.md

The PR is meant to add index directive into Nginx configuration to solve the error `directory index of /var/www/service.example.com/public/ is forbidden,` Nginx error after successfully installation.

Add the index directive to Nginx configuration

---

src/SimpleSAML/Configuration.php
tests/src/SimpleSAML/ConfigurationTest.php

Since this was supported since 'always', this seems to be quickly becoming a FAQ given that the previous error is very cryptic.

Make explicit what part of the config is wrong when non-array endpoint type encountered

---

modules/saml/src/IdP/SAML2.php

To me this is both a bugfix and a feature:
Using the configured value for the entityID _instead_ of the state-version has two downsides:
- No possibility to overrule the issuer using an authproc (*)
- Configuration might have changed mid-authflow
(*) I have a clear use-case to dynamically change the issuer based on the userPrincipalName, to be able to support [Entra Multiple top-level domain](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-install-multiple-domains#multiple-top-level-domain-support).
To decide:
- Is this a bug or a feature (target at 2.4 or backport to supported versions)?
To do:
- If we agree that my use-case is desirable, I will add an authproc-filter that will override the issuer based on a scoped attribute (likely userPrincipalName, but …

Use entityID from state to allow overriding the issuer

---

metadata/saml20-idp-hosted.php.dist
modules/saml/docs/nameid.md

The comment describing `attributes.NameFormat` in the .dist file was incorrect. I tried adjusting the comment, but maybe we are better off removing the option from the .dist file and letting people read the documentation.

Try to clarify attributes.NameFormat is uri by default

---

modules/saml/docs/nameid.md
modules/saml/src/Auth/Process/AttributeNameID.php
tests/modules/saml/src/Auth/Process/AttributeNameIDTest.php

Allow a new option in place of identifyingAttribute called identifyingAttributes. This option expects an array of attribute names. The first one in the list that's available in the attributes being released to the SP will be used. This is particularly useful in the hosted IdP configuration. One can specify multiple attribute names in order of precedence, and the IdP will release the first one from that list to the SP that's in the SP's 'attributes' array. This avoids having to define a new authproc filter for each SP that needs a different value than the single one that was previously specified using 'identifyingAttribute'.
The change still supports identifyingAttribute option which will be used instead of the new option if both are set.

New 'identifyingAttribute option for SAML Attribute NameID filter

---

tests/modules/saml/src/Auth/Process/NameIDAttributeTest.php

These were all failing because of
"eugeneIdP" is not a SAML2-compliant URI
It seems that adding in the colon makes these a compliant test.
The regex that was failing things is
/^([a-z][a-z0-9\+\-\.]+[:])/i
which is not anchored at both ends, so it seems you can have whatever you want after the colon. As long as there is one with a limited prefix.
I discovered this when making the AttributeNameIDTest for pr 2260. It may also cause other tests to fail creating a bunch of smoke around the harder tests to get working.

Update the SP and IdP URIs to pass the URI regex.

---

src/SimpleSAML/XHTML/IdPDisco.php

When there's only a single IdP to choose from, discovery is useless at best and confusing at worst. Just skip it as we know what the choice will be.

Skip disco when single IdP found

---

src/SimpleSAML/Auth/ProcessingChain.php
src/SimpleSAML/Logger.php

Using `print_r` will allow `__debugInfo` to customize how things are print/dumped. This should allow for cases with cycles to be handled without running out of memory.
Relates to [issues/2367](https://github.com/simplesamlphp/simplesamlphp/issues/2367)
I also found that although this is a Logger::debug the string being passed to the function is probably being evaluated all the time. Even if debug is not on the export, dump, or print_r would run. To help with this I have the debugActive() method to only run the `debug()` call if debug is active. I have some testing using a getString() function and that will always be called when used as part of the string concat to the Logger::debug() method call. As the dumping could be expensive and is not used at all if not debugging this might be handy …

Use print_r to output the filters to handle cycles

---

modules/saml/src/Controller/ServiceProvider.php

During a security review it was found:
_It was possible to retrieve the authentication cookies from the browser and reuse this to
continue on the target website using a different browser and without any authentication.
The cookie and the SAML authentication token were set to HTTPOnly to strengthen the
security of the cookie.
It would be possible to extract the authentication details using CSRF techniques and use
these details to authenticate against the target web application. Similar behaviour would
be observed by users where the application would not request login credentials if the
expire duration has not been reached yet._
Therefore it seems the simplesamlphp cookies should be deleted on logout. I'm not sure if this cookie expiry is perhaps better done in `doLogout()`.

Destroy session cookies on logout

---

docs/simplesamlphp-changelog.md
src/SimpleSAML/Locale/Localization.php

If there is no header in the po file then it was not being found for a theme. This PR allows po files to exist without any header such as the below.
msgid ""
msgstr ""
"X-Domain: worldpeace\n"
This was reported here https://github.com/simplesamlphp/simplesamlphp/issues/2384
I have verified using the theme in that issue and with this PR the "MY CUSTOM TRANSLATION" should appear when one selects French and the po file lacks any explicit header.

i18n: set the domain for a theme if it is missing

---

modules/saml/src/Controller/ServiceProvider.php
tests/modules/saml/src/Controller/ServiceProviderTest.php

Some bots generate requests that have an empty ReturnTo. This causes a lot of load (e.g. generating a discovery screen) while it's obviously wrong. Therefore check for this explicitly early on and stop processing.

Throw exception also when ReturnTo is specified but empty

---

composer.json
composer.lock
docs/simplesamlphp-metadata-extensions-idpdisc.md
modules/saml/docs/sp.md
modules/saml/src/Auth/Source/SP.php
modules/saml/src/IdP/SAML2.php
src/SimpleSAML/Metadata/SAMLBuilder.php
src/SimpleSAML/Metadata/SAMLParser.php
tests/src/SimpleSAML/Metadata/SAMLParserTest.php

Closes https://github.com/simplesamlphp/simplesamlphp/issues/28
I know next to nothing about this specification, but I've made the following assumptions:
- Multiple entries of this element are allowed
- These entries only make sense in the Extensions of an SPSSODescriptor
I've verified that:
- Setting this in a `saml:SP`-entry results in an entry in the SP-metadata
- Parsing XML-metadata containing this entry results in a proper SSP metadata-array.

Backport support for IDP Discovery protocol

---

src/SimpleSAML/Locale/Translate.php

This was raised with solution at
https://github.com/simplesamlphp/simplesamlphp/issues/2407
I have added a comment to the method doc block to warn about these extra parameters which are expected in some contexts

i18n allow the substitution of SPNAME and other TWIG variables

---

src/SimpleSAML/Locale/Localization.php

This is a follow up to the theme domain handling update from https://github.com/simplesamlphp/simplesamlphp/issues/2384
If you copy the translations for an existing theme or module and forget to change the domain setting in the po file then it might not be found by SSP. With this warning message you will at least have some indication as to why this might have happened.

i18n warn if a module has an unexpected domain in its po file.

---

composer.json

Sometimes folks might have php executable as php84 for example and the env command might be needed to find or resolve the php in use.

Move to direct execution of these to allow env to find php

---

composer.json

Some installs and composer checkouts are likely to not have the setfacl in place for the cache. The documentation is updated to mention that this is a really good idea but in the shorter term we should not assume this and not run these commands that depend on it automatically.

Disable clearing the cache for now on update

---

docs/simplesamlphp-reference-idp-remote.md

Since that list includes both CBC and GCM modes and is explicit with possible values that are full identifiers.

Update the IdP docs to reference the sharedkey_algorithm list

---

src/SimpleSAML/SessionHandlerPHP.php

Scrub the `expire` key for `session_set_cookie_params`
If that is set then the session_set_cookie_params() will complain. It
is probably best to convert it to working on lifetime but only if
lifetime is also not explicitly set.
Util\HTTP::setCookie() handles the expire and passes that on to the php API.
https://github.com/simplesamlphp/simplesamlphp/blob/93ca2d0043ae1175192ab4aded579e328a3ee4fa/src/SimpleSAML/Utils/HTTP.php#L1117
This relates to https://github.com/simplesamlphp/simplesamlphp/issues/2425

Scrub the expire key for session_set_cookie_params

---

src/SimpleSAML/Utils/HTTP.php

Fixes #2422 
This PR adds checks to `SimpleSAML\Utils\HTTP` methods to prevent exceptions when running in CLI scripts.

[#2422] Add empty checks to $_SERVER variables in SimpleSAML\Utils\HTTP

---

tests/src/SimpleSAML/ConfigurationTest.php

In ConfigurationTest.php update Constants:: to C::, as in the `use … as ...;` statement.
Apparently PHP particularly doesn't care, or this test was never executed (maybe you need [tombstones](https://github.com/scheb/tombstone)?).

In ConfigurationTest.php update Constants:: to C::, as in the use

---

src/SimpleSAML/Utils/HTTP.php
tests/src/SimpleSAML/Utils/HTTPTest.php

The $matches[0] should not be using the DIRECTORY_SEPARATOR since it is working on a string that is created using '/' and the REQUEST_URI.
This relates to https://github.com/simplesamlphp/simplesamlphp/issues/2424

Better handle win paths here by splitting on dir separator

---

docs/simplesamlphp-changelog.md
modules/saml/src/Auth/Source/SP.php

Closes #2448
While throwing an exception is the right thing to do, it may also be a little harsh.
Definitely not something we should do in a minor release.

bugfix: log a warning instead on throwing an exception for invalid entityIDs

---

bin/memcacheSync.php
modules/core/src/Controller/ErrorReport.php
modules/saml/src/Controller/ServiceProvider.php
modules/saml/src/IdP/SAML2.php
src/SimpleSAML/Command/SspCacheClearCommand.php
src/SimpleSAML/Command/UpdateTranslatableStringsCommand.php
src/SimpleSAML/Metadata/MetaDataStorageHandlerDirectory.php
src/SimpleSAML/Metadata/MetaDataStorageHandlerPdo.php
src/SimpleSAML/Metadata/SAMLParser.php
src/SimpleSAML/Module.php
src/SimpleSAML/Utils/Auth.php
src/SimpleSAML/Utils/Config/Metadata.php
src/SimpleSAML/Utils/Crypto.php
tests/modules/saml/src/Auth/Source/SPTest.php

- Undeclared variable (incorrect name)
- Move some deprecated static functions to instances
- Namespacing on various PHPdoc tags
- Various PHPdoc tags NULL to lowercase
- Fix a PHP 8.2 deprecation re string interpolation

Fix various errors and warnings detected in VS Code

---

src/SimpleSAML/SessionHandler.php
src/SimpleSAML/SessionHandlerPHP.php
src/SimpleSAML/Utils/HTTP.php

According to [Mozilla Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Set-Cookie#secure), `Secure` attribute should be allowed on localhost even if HTTP is used.
It makes testing a little easier.
My only doubt is about "localhost" vs "127.0.0.1" should both be allowed or only the former?

Allow "Secure" cookie attribute via HTTP on localhost

---

docs/simplesamlphp-advancedfeatures.md
docs/simplesamlphp-changelog.md

Remove information in simplesamlphp-advancedfeatures.md about possible fallback from metadata.sign.privatekey to privatekey in IdP and SP metadata files
This was raised in
https://github.com/simplesamlphp/simplesamlphp/issues/2447 as not working for IdP metadata. I have seen that is currently the case.
It should also be confirmed that the fallback is not actively working for SP metadata to make sure that this PR does not change existing functionality.
Perhaps also we should strenghten this to make sure that if metadata.sign.enable=true in the IdP/SP metadata file then we *require* you to set the metadata.sign.privatekey and metadata.sign.certificate. Though that would be a breaking change as well so should be a 2.5 type udpate.
This PR is the opposite to …

Docs: remove information about fallback from md.sign.pk to pk

---

composer.json
composer.lock

In `SimpleSAML\Utils\Time::parseDuration()` we call `SimpleSAML\XML\Assert::validDuration()`.\
This is only available since `simplesamlphp/xml-common:1.24.2`.
Currently there is no explicit requirement for `simplesamlphp/xml-common`, it is only pulled in as an indirect dependency.\
There could be other version constraints in a project that cause `simplesamlphp/xml-common` to be downgraded to something less than 1.24.2.
It is generally best practice to explicitly require things we use directly.
(I open this PR for 2.4.x, but maybe you want it somewhere else and then backport, up to you)

Require xml-common:^1.24.2

---

docs/simplesamlphp-advancedfeatures.md

This is a very small example of check_function without using modules. I think making the paths very simple to find the function is probably a good idea. I had some issues with using modules where perhaps the module had to be enabled and loaded (makes sense) but if you just want a single function you might want to just put it into a single file and not have to dance with modules just for a `check_function`.
The example also has some more docs in comments to try to explain things to an interested reader. I have tried to make the code in the new example very simple so that it can be experimented with by an interested reader right away (rejecting one of their test logins) and get them up to speed.

Small check_function example

---

docs/simplesamlphp-changelog.md
src/SimpleSAML/Session.php

If the user configuration includes a definition of the check_function we should not silently ignore it if we can not call it. Consider for example if the admin is using that to reject or drop a session for a group of nefarious users. They would rather know that the function is not callable than assume everything is ok. This could happen after initial testing for example if the function is in a module that was not enabled during an upgrade etc.
My main doubt here is that it could cause error messages to appear during a 2.4 series update. But then it will only happen if there is an existing error in config.php.

Consider it an error if session.check_function can not be called

---

.gitignore
modules/core/src/Auth/UserPassBase.php
modules/exampleauth/public/assets/css/default.css
modules/exampleauth/routing/routes/routes.yml
modules/exampleauth/src/Auth/Source/UserClick.php
modules/exampleauth/src/Controller/ProfileAuth.php
modules/exampleauth/templates/userclick.twig
modules/multiauth/src/Auth/Source/MultiAuth.php
tests/modules/multiauth/src/Controller/DiscoControllerTest.php

A new authsource that lets user choose preconfigured profiles from a list.
authsources.php:
```
'profileauth' => [
'exampleauth:UserClick',
'users' => [
[
'uid' => ['student'],
'displayName' => ['Student'],
'eduPersonAffiliation' => ['student', 'member'],
],
[
'uid' => ['employee'],
'displayName' => ['Employee'],
'eduPersonAffiliation' => ['employee', 'member'],
],
],
],
```
If only one user is configured, the profile chooser will be skipped and login is automatic.

Add ProfileAuth authsource

---

modules/admin/templates/federation.twig
modules/core/templates/logout-iframe.twig

A few of the Twig templates still have old FontAwesome 4 icon names. While these are mostly backwards compatible still, at least one used in the logout-iframe.twig has gone completely (circle-o-notch) resulting in a broken display.
This updates the names to the version 6+ naming per https://docs.fontawesome.com/v6/web/setup/upgrade/whats-changed#icons-renamed-in-version-6

Update FontAwesome icon names
