.coveralls.yml, .travis.yml, README.md, composer.json, composer.lock, tools/phpunit/phpunit.xml
=> Add coveralls support

dictionaries/status.definition.json, modules/core/www/authenticate.php, templates/hostnames.php, templates/includes/attributes.php, templates/status.php, www/example-simple/hostnames.php
This page allows to view nearly everything of the active session,
except for the NameID. Display this as well.
=> Add NameID to attributes status page.

config-templates/config.php, lib/SimpleSAML/Metadata/MetaDataStorageHandlerMDX.php, lib/SimpleSAML/Metadata/MetaDataStorageSource.php
With this MDX metadata handler simpleSAMLphp can load metadata dynamically from MDX servers (like [pyFF]).
More about Metadata Query Protocol: https://github.com/iay/md-query
[pyff]: https://github.com/leifj/pyFF
=> Adding MDX metadata handler

docs/simplesamlphp-authproc.txt, modules/core/docs/authproc_attributecopy.txt
https://groups.google.com/forum/#!topic/simplesamlphp-dev/4TheEMit2hg
=> Added documentation for AttributeCopy authentication processing filter.

dictionaries/login.definition.json, modules/core/templates/loginuserpass.php
Impatient users will press the button twice which leads (esp in Chrome it seems) to NOSTATE errors.
=> Disable login button with JS after first click.

config-templates/authsources.php, lib/SimpleSAML/Auth/LDAP.php, modules/ldap/lib/ConfigHelper.php
=> LDAP Connection Improvements

lib/SimpleSAML/Utils/Net.php, tests/Utils/NetTest.php
Some coverage for IPv6 support.
=> Update IPv6 CIDR checks.

composer.json, composer.lock
Implies update simplesamlphp/saml2 because share the same dependency
=> Use robrichards/xmlseclibs instead simplesamlphp/xmlseclibs

dictionaries/admin.definition.json, templates/metadata-converter.php, www/admin/metadata-converter.php
=> Support file uploads in metadata converter.

docs/simplesamlphp-googleapps.txt
As per https://groups.google.com/forum/#!topic/simplesamlphp/nFXerlX839E
=> Use $metadata array for example IDP and SP metadata

lib/SimpleSAML/Auth/LDAP.php
(as suggested by jhaar in issue #120 and used by us)
=> use LDAP_OPT_DIAGNOSTIC_MESSAGE for better error reporting in LDAP

config-templates/config.php, docs/simplesamlphp-upgrade-notes-1.14.txt
=> Set trusted.url.domains default to array()

composer.json, composer.lock, lib/SimpleSAML/Bindings/Shib13/Artifact.php, lib/SimpleSAML/Bindings/Shib13/HTTPPost.php, lib/SimpleSAML/Metadata/SAMLParser.php, lib/SimpleSAML/Metadata/Signer.php, lib/SimpleSAML/Utils/XML.php, lib/SimpleSAML/XML/Shib13/AuthnResponse.php, modules/adfs/lib/IdP/ADFS.php, modules/adfs/lib/XMLSecurityDSig.php, modules/cas/lib/Auth/Source/CAS.php, modules/core/lib/Auth/Process/TargetedID.php, modules/metarefresh/lib/MetaLoader.php, modules/saml/docs/sp.txt, modules/saml/lib/Auth/Process/PersistentNameID2TargetedID.php, modules/saml/lib/IdP/SAML2.php, www/_include.php, www/saml2/idp/ArtifactResolutionService.php
Refactoriced the way than XML is loaded to use SAML2_DOMDocumentFactory class.
=> XML data is loaded using SAML2_DOMDocumentFactory class

lib/SimpleSAML/Utils/HTTP.php
Don't gather the proxy.auth setting if we don't use it
=> Minor optimalization - Don't gather settings if we don't use them

.coveralls.yml
this was added to fix a bug - now we need to remove it :-)
=> remove src_dir from .coveralls.yml

config-templates/authsources.php, lib/SimpleSAML/Auth/LDAP.php, modules/ldap/docs/ldap.txt, modules/ldap/lib/ConfigHelper.php
feature enhancement for Issue #25 
Added ability to define custom LDAP search filters
Based off rastrano's work https://groups.google.com/forum/#!topic/simplesamlphp/MjkxXM-0ru4
=> - Added search.filter to allow for custom LDAP search filters

config-templates/config.php, lib/SimpleSAML/Locale/Language.php, lib/SimpleSAML/Locale/Translate.php, lib/SimpleSAML/XHTML/Template.php, modules/consent/templates/consentform.php, modules/consentAdmin/templates/consentadmin.php, modules/consentAdmin/www/consentAdmin.php, modules/core/lib/Auth/Process/LanguageAdaptor.php, modules/core/templates/frontpage_federation.tpl.php, modules/core/templates/logout-iframe.php, modules/discopower/templates/disco-tpl.php, templates/includes/attributes.php, templates/includes/header.php, templates/logout.php, templates/selectidp-dropdown.php, templates/selectidp-links.php, templates/status.php
This is the previous "template-refactor" branch:
* rebased to newest master
* fixes due to comments on that branch, namespaces included
* one more wrapped function in Template: includeInlineTranslation(). This is used in a single place that lacks any strings with translations, even English...
Manually click-tested.
=> Template refactor rebased

modules/core/templates/loginuserpass.php
The login-page would not verify as valid XHTML 1.0 Transitional
=> Fix misplaced </tr> (2x)

config-templates/config.php
Minor changes to use SimpleSAML namespace to Logger logging level definitions.
=> SimpleSAML namespace usage in config.php

modules/radius/docs/radius.txt, modules/radius/lib/Auth/Source/Radius.php
* Code formatting
* Improve error messages
* Add new option `realm` that will be postfixed to the entered username
=> Several updates to the Radius module

lib/SimpleSAML/Metadata/MetaDataStorageHandler.php, lib/SimpleSAML/Metadata/MetaDataStorageHandlerFlatFile.php, lib/SimpleSAML/Metadata/MetaDataStorageHandlerPdo.php, lib/SimpleSAML/Metadata/MetaDataStorageSource.php, lib/SimpleSAML/Utils/HTTP.php, tests/lib/SimpleSAML/Utils/HTTPTest.php, www/admin/hostnames.php
This fixes the issue 337.
I added a function getSelfHostWithout port to retain the original behaviour. 
I've also added some unit tests.
Cheers
=> Fixes issue 337

modules/core/templates/loginuserpass.php
Fixes: Mar 25 11:06:53 simplesamlphp INFO [0015a148dc] Template: Looking up [{login:processing]: not translated at all.
=> Fix missing curly bracket

modules/memcacheMonitor/dictionaries/memcachestat.definition.json, modules/memcacheMonitor/templates/memcachestat.tpl.php
Fix missing type attribute to comply with W3c XHTML 1.0 Transitional
Also added some missing definitions to the dictionary.
=> General improvements of MemcacheMonitor module

CONTRIBUTE.md
There are guidelines for code formatting, so I'm going to suggest guidelines for commit formatting.
=> docs: Recommend the usual commit message rules

templates/includes/header.php, www/resources/default.css
Remove inline style sheet so external CSS works.
Updated default.css so that things keep the same look.
=> Remove inline style sheet

docs/simplesamlphp-modules.md
Enabling/disabling modules through config.php rather than touching 'enable'/'disable' files inside module directories.
=> Update module docs

docs/simplesamlphp-reference-idp-remote.md, docs/simplesamlphp-sp.md, lib/SimpleSAML/Metadata/SAMLParser.php, lib/SimpleSAML/Utils/Crypto.php, metadata-templates/shib13-idp-remote.php, modules/saml/lib/Message.php
Issue a notice when the option is used nonetheless.
Closes: #432
=> Deprecate the certFingerprint option.

templates/metadata.php
=> Fix object operator bug on templates/metadata.php

modules/authcrypt/lib/Auth/Source/Htpasswd.php
$password and $crypted where swapped
=> Fix APR1_MD5::check call

modules/discopower/lib/PowerIdPDisco.php
Not sure on which branch I should create pullrequest...
=> bugfix: Discopower ignored filtering of hide.from.discovery metadata property

lib/SimpleSAML/SessionHandler.php, lib/SimpleSAML/SessionHandlerStore.php, lib/SimpleSAML/Store.php, lib/SimpleSAML/Store/Memcache.php, lib/SimpleSAML/Store/SQL.php, modules/riak/lib/Store/Store.php, modules/saml/lib/IdP/SQLNameID.php, modules/saml/lib/SP/LogoutStore.php, modules/saml/www/sp/metadata.php, modules/saml/www/sp/saml2-acs.php, tests/lib/SimpleSAML/Store/SQLTest.php, tests/lib/SimpleSAML/StoreTest.php, www/saml2/idp/ArtifactResolutionService.php
Modified ` SimpleSAML_Store` to be PSR-4 compliant.
=> Modified SimpleSAML_Store to PSR-4

lib/SimpleSAML/Bindings/Shib13/HTTPPost.php, lib/SimpleSAML/Utilities.php, lib/SimpleSAML/Utils/XML.php, lib/SimpleSAML/XML/Errors.php, lib/SimpleSAML/XML/Parser.php, lib/SimpleSAML/XML/Shib13/AuthnRequest.php, lib/SimpleSAML/XML/Shib13/AuthnResponse.php, lib/SimpleSAML/XML/Signer.php, lib/SimpleSAML/XML/Validator.php, modules/saml/lib/Auth/Source/SP.php, modules/saml/lib/IdP/SAML1.php, modules/saml/www/sp/saml1-acs.php, tests/lib/SimpleSAML/XML/ErrorsTest.php, tests/lib/SimpleSAML/XML/ParserTest.php, tests/lib/SimpleSAML/XML/Shib13/AuthnResponseTest.php
Two commits: one refactorized all classes in lib/SimpleSAML/XML directory to PSR-4 and the other to PSR-2.
Some new tests added.
=> SimpleSAML_XML_* classes refactorized to PSR-4 and PSR-2

lib/SimpleSAML/Bindings/Shib13/Artifact.php, lib/SimpleSAML/Bindings/Shib13/HTTPPost.php, modules/saml/lib/IdP/SAML1.php, modules/saml/www/sp/saml1-acs.php
Two commits: one refactorized all classes in lib/SimpleSAML/Bindings/Shib13 directory to PSR-4 and the other to PSR-2.
=> SimpleSAML_Binding_Shib13_* classes refactorized to PSR-4 and PSR-2

composer.json, config-templates/config.php, lib/SimpleSAML/Store.php, lib/SimpleSAML/Store/Redis.php, tests/lib/SimpleSAML/Store/RedisTest.php
The commit message and issue are pretty self-explanatory. Let me know if you have any concerns!
=> Added Redis as possible session storage mechanism, fixes #574

docs/simplesamlphp-install.md, docs/simplesamlphp-maintenance.md
Per https://github.com/simplesamlphp/simplesamlphp/pull/585 :)
=> Added Redis session storage documentation

composer.json, tests/lib/SimpleSAML/Utils/SystemTest.php
Hey all,
I noticed this file was missing tests so I wrote some :)
=> Added tests for SimpleSAMLUtilsSystem

lib/SimpleSAML/Session.php, lib/SimpleSAML/SessionHandler.php, lib/SimpleSAML/SessionHandlerCookie.php, lib/SimpleSAML/SessionHandlerPHP.php, lib/SimpleSAML/SessionHandlerStore.php, modules/core/lib/Auth/Process/ExtendIdPSession.php, modules/core/www/loginuserpass.php, modules/core/www/loginuserpassorg.php, modules/saml/lib/SP/LogoutStore.php
Refactorized all classes in lib/SimpleSAML/SessionHandler* to PSR-4 (PSR-2 is not necessary).
=> SimpleSAML_SessionHandler* classes refactorized to PSR-4

tests/lib/SimpleSAML/Utils/XMLTest.php
=> Added tests for SimpleSAML\Utils\XML

lib/SimpleSAML/XML/Signer.php, tests/lib/SimpleSAML/XML/SignerTest.php, tests/modules/consent/lib/Auth/Process/ConsentTest.php, tests/modules/saml/lib/Auth/Source/Auth_Source_SP_Test.php
Added some more tests! Also, fixed a PSR-2 issue in `Signer`, and had to add some additional `$full_path` arguments since `vfsstream` doesn't play well with `getCertPath`.
=> Added tests for SimpleSAML\XML\Signer

templates/base.twig, templates/includes/header.php
for better mobile/small form factor support (eg when using landscape) - don't specify the device-width etc (see e.g. https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/UsingtheViewport/UsingtheViewport.html )
=> adjustment of meta viewport

.travis.yml
And hopefully PHP 7.2 soon too :)
=> Add PHP 7.1 to TravisCI build versions

modules/core/templates/loginuserpass.php, www/resources/default.css
As mentiond in #618, a PR :-)
Feel free to request changes. Would be glad to see this merged.
=> Fix for #618, correcting the login layout on mobile screens.

attributemap/name2oid.php, attributemap/oid2name.php
Trivial addition of sshPublicKey OID to attributemaps.
=> Provide OID mapping for sshPublicKey

lib/SimpleSAML/Store/Redis.php
=> Correct Redis store port argument string

config-templates/config.php, www/errorreport.php
=> Add sendmail_from option

lib/SimpleSAML/Auth/Default.php, lib/SimpleSAML/Auth/LDAP.php, lib/SimpleSAML/Auth/ProcessingChain.php, lib/SimpleSAML/Auth/ProcessingFilter.php, lib/SimpleSAML/Auth/State.php
Working toward some of the requested tasks in
https://github.com/simplesamlphp/simplesamlphp/wiki/List-of-tasks
=> PSR-2 compliance in lib/SimpleSAML/Auth/ directory

.gitignore, .php_cs.dist, composer.json, composer.lock
Added  php-cs-fixer config and composer meta. For https://github.com/simplesamlphp/simplesamlphp/issues/583
=> Added php-cs-fixer config

tests/lib/SimpleSAML/Store/SQLTest.php, tests/lib/SimpleSAML/StoreTest.php
I've refactored some tests with [`assertNull`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertNull) and [`assertFalse`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertFalse).
=> Refactoring tests

config-templates/config.php
It's mentioned in the docs, but should be in the config template as well..
Not sure whether this requires extra comments too.
=> Add new config option

modules/sqlauth/default-disable
No need to default-enable this quite specific module
=> Update and rename default-enable to default-disable

modules/multiauth/docs/multiauth.txt, modules/multiauth/lib/Auth/Source/MultiAuth.php, modules/multiauth/templates/selectsource.php
Added help option to multiauth
=> Multiauth help message

modules/metarefresh/locales/en/LC_MESSAGES/metarefresh.po, modules/metarefresh/templates/fetch.twig
Also added translation scaffolding.
=> Twigified 'metarefresh' module

lib/SimpleSAML/Logger.php
Fixes edge-case https://github.com/simplesamlphp/simplesamlphp/issues/741 where application has one of the known LoggingHandlers' name as a defined class
=> Fix bug in createLoggingHandler

modules/casserver/www/serviceValidate.php, modules/core/lib/Auth/Process/PHP.php, tests/modules/core/lib/Auth/Process/PHPTest.php
`create_function` has been deprecated in PHP 7.2.
=> Replace deprecated create_function

lib/SimpleSAML/Utils/HTTP.php
forward-port of my recent fix in branch 1.15
=> space is required before auth data

CONTRIBUTING.md
I have made a lot of changes to wording and organization of topics. I hope these changes are viewed as improvements to readability. If anyone has edits they would like to make to this PR, I am open to your thoughts!
_Thanks for such a great library!_
=> Edits to CONTRIBUTING.md

modules/metarefresh/lib/MetaLoader.php
And so avoid some messages in log file.
=> Check responseHeaders presence before use them

lib/SimpleSAML/Auth/LDAP.php, modules/ldap/docs/ldap.md, modules/ldap/lib/Auth/Process/BaseFilter.php, modules/ldap/lib/ConfigHelper.php
Closes https://github.com/simplesamlphp/simplesamlphp/issues/8
=> Add ldap-search scope

modules/adfs/lib/IdP/ADFS.php
This PR addresses the remainders of https://github.com/simplesamlphp/simplesamlphp/pull/469, so we can finally close that one.
=> ADFS improvements

modules/core/lib/Storage/SQLPermanentStorage.php
Adresses https://github.com/simplesamlphp/simplesamlphp/issues/20
The suggested fix in the issue is not a proper one.. There's a cron hook for removing expired entries.
Calling `$this->store->removeExpired();` on every single lookup would be horrible overkill.
We may never expose expired data in the first place and that's what this PR does; filtering it out.
=> SQLPermanentStorage:  Check for expiration

lib/SimpleSAML/Utils/HTTP.php, tests/lib/SimpleSAML/Utils/HTTPTest.php
https://github.com/simplesamlphp/simplesamlphp/issues/594
=> Fix edge-case #594 with integer SERVER_PORT

modules/statistics/templates/statistics.tpl.php, modules/statistics/www/showstats.php
This closes https://github.com/simplesamlphp/simplesamlphp/issues/7
I've applied the attached diff against the current codebase.
=> statistics: show decent error-message when no data is available

templates/includes/header.php
Follow PSR-2 coding style.
Order languages by their code.
=> PSR-2 Coding style

lib/SimpleSAML/Metadata/MetaDataStorageSource.php
Now using DiscoHints->IPHint to support specified SAML extension for IdP discovery
=> Use DiscoHints instead of custom configuration to enable IdP discovery

lib/SimpleSAML/Logger.php, modules/core/docs/authproc_attributelimit.md, modules/core/lib/Auth/Process/AttributeLimit.php, tests/modules/core/lib/Auth/Process/AttributeLimitTest.php
Enhancements to AttributeLimit to give additional control over allowed values
=> AttributeLimit: allow options to use regex or ignore case.

modules/core/dictionaries/cardinality.translation.json
Updated, and Added cardinality translations for Afrikaans (af).
=> Cardinality: Add Afrikaans translations

modules/smartattributes/lib/Auth/Process/SmartID.php, modules/smartattributes/lib/Auth/Process/SmartName.php
Fixes https://github.com/simplesamlphp/simplesamlphp/issues/841
=> smartattributes: fix bug

modules/core/lib/Auth/Process/AttributeMap.php, tests/modules/core/lib/Auth/Process/AttributeMapTest.php
More details in a comment left on #828.
=> Fix #828, infinite loop in AttributeMap behavior

modules/consentAdmin/www/consentAdmin.php
sspmod_consent_Auth_Process_Consent::getTargetedID() is aware of bridged/proxied connections, and generates its ID with the remote IdP's entityId. In order to retrieve this consent information and determine whether it has changed, consentAdmin needs to do the same. The way it currently does so is by detecting saml:sp:IdP in the state and loading the remote IdP's metadata in place of the local IdP's.
Unfortunately this doesn't work properly if saml:PersistentNameID and saml:PersistentNameID2TargetedID are used on a bridged connection. When the real authproc filter runs, saml:PersistentNameID uses the local IdP's entityID to generate a nameID and that is not available when consentAdmin calls processStatePassive() for a bridged connection. This means that consentAdmin always shows SPs using …
=> Get consentAdmin to send better state information to processStatePassive

modules/.gitignore
Ignore the enable file in modules
=> Ignore the enable file for modules

modules/saml/lib/SP/LogoutStore.php
=> Update logoutstore table migration syntax for PostgreSQL

config-templates/authsources.php, dictionaries/login.definition.json, modules/core/lib/Auth/UserPassOrgBase.php, modules/core/templates/loginuserpass.php, modules/core/www/loginuserpassorg.php, tests/modules/core/lib/Auth/UserPassOrgBaseTest.php
This is #855 prepared for master, in an attempt to shrink #717
=> Implement "Remember my Organization" in multiple-ldap

modules/oauth/config-template/module_oauth.php, modules/oauth/hooks/hook_cron.php, modules/oauth/hooks/hook_frontpage.php, modules/oauth/lib/Consumer.php, modules/oauth/lib/OAuthStore.php, modules/oauth/lib/Registry.php, modules/oauth/libextinc/OAuth.php, modules/oauth/www/getUserInfo.php, modules/oauth/www/registry.edit.php, modules/oauth/www/registry.php
Attempt to reduce footprint of #717
=> oauth: Fix indentation / PSR-2

modules/authYubiKey/www/yubikeylogin.php, modules/authfacebook/extlibinc/base_facebook.php, modules/core/www/loginuserpass.php, modules/core/www/loginuserpassorg.php, modules/discopower/www/style.css, modules/memcacheMonitor/www/memcachestat.php, modules/oauth/config-template/module_oauth.php, modules/oauth/hooks/hook_cron.php, modules/statistics/lib/Statistics/FieldPresentation/Entity.php
Mostly whitespace.. Attempt to reduce the footprint of #717
=> assorted fixes

modules/authfacebook/lib/Auth/Source/Facebook.php
@tvdijen requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/simplesamlphp/simplesamlphp/
=> Scrutinizer Auto-Fixes

composer.json, composer.lock
Checked all usages and found no incompatibilities.
I cannot use this package in my project because of the gettext limitation.
=> Upgrade gettext to latest version

modules/oauth/lib/Consumer.php
`stream_context_create` functionality is handled with HTTP::fetch()
=> Fix for #933

lib/SimpleSAML/Utils/Auth.php, modules/core/dictionaries/frontpage.definition.json, modules/core/dictionaries/frontpage.translation.json, modules/core/locales/en/LC_MESSAGES/core.po, modules/core/locales/nl/LC_MESSAGES/core.po, modules/core/templates/_frontpage_menu.twig, modules/core/www/frontpage_auth.php, modules/core/www/frontpage_config.php, modules/core/www/frontpage_federation.php, modules/core/www/frontpage_welcome.php, templates/index.twig, www/admin/index.php
=> Add logoff button for admin-interface

lib/SimpleSAML/Auth/LDAP.php, lib/SimpleSAML/Auth/ProcessingChain.php, lib/SimpleSAML/Metadata/SAMLParser.php, lib/SimpleSAML/XHTML/Template.php, modules/authYubiKey/lib/Auth/Source/YubiKey.php, modules/authfacebook/extlibinc/base_facebook.php, modules/cas/lib/Auth/Source/CAS.php, modules/cdc/lib/Server.php, modules/consent/lib/Consent/Store/Database.php, modules/core/lib/ACL.php, modules/statistics/lib/Graph/GoogleCharts.php
- Updated the phpDoc comments to match the code
- Added return statements
- Added return values
=> Added return statements, updated return types

docs/simplesamlphp-reference-idp-remote.md, modules/saml/lib/Auth/Source/SP.php
Patch to fix #498 - more detail is included in that issue.
=> Allow scoping to be disabled for ADFS (fixes #498)

modules/core/lib/Auth/Process/AttributeMap.php, tests/modules/core/lib/Auth/Process/AttributeMapTest.php
=> Fixes #970, improve AttributeMap overwrite behavior

modules/.gitignore, modules/admin/lib/ConfigController.php, modules/admin/lib/TestController.php, modules/admin/templates/authsource_list.twig, modules/admin/templates/status.twig
It needs some polishing (graphically), but technically it's working.
=> newUI: initial work on admin 'Test authsources'

lib/_autoload_modules.php, tests/lib/AutoloadModulesTest.php
Fixes simplesamlphp/simplesamlphp#1030
Refs vimeo/psalm#1162
=> Autoloader infinite recursion fix

modules/discopower/templates/disco.tpl.php, modules/discopower/www/assets/css/disco.css
update paths, change `post` to `head`
=> Discopower fixes

modules/discopower/lib/PowerIdPDisco.php, modules/discopower/templates/disco.tpl.php, modules/discopower/templates/disco.twig, modules/discopower/www/assets/js/tablist.js, modules/discopower/www/tablist.php
=> Remove the inline javascript from discopower-module

lib/SimpleSAML/XHTML/Template.php
Convert Twig-calls to namespaced ones
=> Twig namespaces

.appveyor.yml, tests/BuiltInServer.php, tests/lib/SimpleSAML/ConfigurationTest.php
=> Use Appveyor for CI on Windows

modules/saml/lib/BaseNameIDGenerator.php
Fixes https://github.com/simplesamlphp/simplesamlphp/issues/1135
=> Properly set NameIDFormat on generation

composer.json, composer.lock, lib/SimpleSAML/Auth/ProcessingChain.php, lib/SimpleSAML/Auth/Source.php, lib/SimpleSAML/Auth/State.php, lib/SimpleSAML/Bindings/Shib13/Artifact.php, lib/SimpleSAML/Bindings/Shib13/HTTPPost.php, lib/SimpleSAML/Configuration.php, lib/SimpleSAML/Error/UnserializableException.php, lib/SimpleSAML/HTTP/Router.php, lib/SimpleSAML/IdP.php, lib/SimpleSAML/IdP/IFrameLogoutHandler.php, lib/SimpleSAML/Locale/Localization.php, lib/SimpleSAML/Locale/Translate.php, lib/SimpleSAML/Metadata/MetaDataStorageHandlerFlatFile.php, lib/SimpleSAML/Metadata/MetaDataStorageHandlerSerialize.php, lib/SimpleSAML/Metadata/MetaDataStorageSource.php, lib/SimpleSAML/Metadata/SAMLParser.php, lib/SimpleSAML/Metadata/Signer.php, lib/SimpleSAML/Metadata/Sources/MDQ.php, lib/SimpleSAML/Utils/EMail.php, lib/SimpleSAML/XHTML/Template.php, lib/SimpleSAML/XHTML/TemplateLoader.php, lib/SimpleSAML/XML/Parser.php, lib/SimpleSAML/XML/Shib13/AuthnRequest.php, lib/SimpleSAML/XML/Shib13/AuthnResponse.php, lib/SimpleSAML/XML/Signer.php, lib/SimpleSAML/XML/Validator.php, psalm.xml
Fixes all Psalm-issues in all subdirs under `lib/SimpleSAML`.
I hope it is not too big to review. I've added a few comments to the parts that are likely to raise questions
=> Fix Psalm-issues batch #1

lib/SimpleSAML/Store/SQL.php
Closes https://github.com/simplesamlphp/simplesamlphp/issues/963
=> Use ALTER TABLE, or CREATE INDEX for SQLite instead

modules/saml/lib/SP/LogoutStore.php
=> Rewrite table upgrade

config-templates/config.php, lib/SimpleSAML/Locale/Language.php, lib/SimpleSAML/SessionHandler.php, lib/SimpleSAML/SessionHandlerPHP.php, lib/SimpleSAML/Utils/HTTP.php, tests/lib/SimpleSAML/SessionHandlerPHPTest.php, tests/lib/SimpleSAML/Utils/HTTPTest.php
Per discussion in #1153, this forward ports 465faf6 to the master branch.
=> Add support for RFC6265bis SameSite cookie attribute

lib/SimpleSAML/Metadata/MetaDataStorageHandler.php, modules/admin/lib/FederationController.php, modules/core/www/frontpage_federation.php
Closes https://github.com/simplesamlphp/simplesamlphp/issues/747
=> Show expired entities in federation-page

modules/core/templates/logout-iframe-wrapper.twig, modules/core/templates/logout-iframe.twig, modules/core/www/idp/logout-iframe.php, src/css/default.scss, src/js/logout/logout.js, src/js/logout/main.js, templates/IFrameLogoutHandler.twig, webpack.config.js
This resolves #944.
@tvdijen, @thijskh, would you mind taking a look into this to see if I am missing something or something breaks?
=> Migrate logout to twig

modules/exampleauth/templates/authenticate.twig, modules/exampleauth/www/authpage.php
We shouldn't have html in PHP-files
=> Twigify exampleauth

modules/admin/lib/FederationController.php
Closes #1195
Will display an entityID if no suitable translation is available.
=> Fix Admin UI glitch

modules/core/lib/Controller.php, templates/auth_status.twig
Make authData available in template
=> Add authData

lib/SimpleSAML/Store/SQL.php
Change lib/SimpleSAML/Store/SQL so it can store sessions on MSSQL servers
=> Sql sessions for mssql

lib/SimpleSAML/Store/Redis.php
Added "database" parameter for Redis Client.
=> Redis connection parameter update

lib/SimpleSAML/Module.php
=> Standardize the way we collect PATH_INFO

modules/saml/lib/Auth/Source/SP.php
Fix set AuthnContextClassRef Comparison
=> Fix AuthnContextClassRef Comparison on Request

.travis.yml, composer.json, lib/SimpleSAML/Metadata/SAMLParser.php, modules/admin/lib/Controller/Test.php, modules/saml/lib/IdP/SAML2.php, modules/saml/lib/SP/LogoutStore.php, modules/saml/www/sp/saml2-acs.php
Upgrade to v4 of the SAML2-lib
=> Upgrade saml2 library dep

docs/conf.py
Seeing other readthedocs projects and documentation, a configuration file is used for theming the documentation interface. I have just added a very basic initial document.
=> Created conf.py with basic readthedocs configuration

lib/SimpleSAML/Module.php
fix issue #1305 for 1.18 by backporting fix from master
=> backporting fixes for Metadataparser from:

modules/saml/lib/SP/LogoutStore.php
Closes https://github.com/simplesamlphp/simplesamlphp/issues/1323
=>  fix createLogoutTable method

lib/SimpleSAML/Error/ErrorCodes.php, locales/el/LC_MESSAGES/messages.po, locales/en/LC_MESSAGES/messages.po, locales/nl/LC_MESSAGES/messages.po, locales/st/LC_MESSAGES/messages.po, locales/xh/LC_MESSAGES/messages.po, locales/zu/LC_MESSAGES/messages.po, modules/cron/locales/nl/LC_MESSAGES/cron.po, modules/cron/templates/croninfo.twig
- fix a Dutch translation typo (_contrab_ should be _crontab_)
- add some missing Dutch translations
- add a line break to properly align the first `# Run cron:` line in module.php/cron/croninfo.php
=> Few small improvements

modules/admin/lib/Controller/Config.php, modules/admin/lib/Controller/Federation.php, modules/admin/lib/Controller/Test.php, phpunit.xml, tests/modules/admin/lib/Controller/ConfigTest.php, tests/modules/admin/lib/Controller/FederationTest.php, tests/modules/admin/lib/Controller/TestTest.php
I'm sure there's more coverage to be gained here, but for now I'm out of inspiration
=> Admin controller tests

modules/saml/docs/sp.md, modules/saml/lib/Auth/Source/SP.php
=> Provider name

lib/SimpleSAML/Error/AuthSource.php, lib/SimpleSAML/Error/CriticalConfigurationError.php, lib/SimpleSAML/Error/Error.php, lib/SimpleSAML/Error/Exception.php, lib/SimpleSAML/Error/UnserializableException.php, lib/SimpleSAML/Error/UserAborted.php, lib/SimpleSAML/Utils/XML.php, modules/saml/lib/Error.php, modules/saml/lib/Error/NoAuthnContext.php, modules/saml/lib/Error/NoAvailableIDP.php, modules/saml/lib/Error/NoPassive.php, modules/saml/lib/Error/NoSupportedIDP.php, modules/saml/lib/Error/ProxyCountExceeded.php, www/_include.php
=> Improve error handling

docs/simplesamlphp-reference-sp-remote.md, modules/saml/lib/IdP/SAML2.php
=> Allow additional Audiences to be specified

modules/admin/templates/federation.twig, package-lock.json, package.json, src/css/default.scss, webpack.config.js
=> Update FontAwesome to 5

modules/saml/lib/Auth/Source/SP.php
=> Support saml:Extensions inside Authsources.php

lib/SimpleSAML/Metadata/MetaDataStorageHandler.php, lib/SimpleSAML/Metadata/Sources/MDQ.php, modules/core/lib/Auth/Process/PHP.php, modules/saml/lib/Auth/Source/SP.php, tests/lib/SimpleSAML/Store/RedisTest.php
Removed line when removing @return void in last commit
=> Removed line in last commit

docs/simplesamlphp-reference-idp-remote.md, docs/simplesamlphp-reference-sp-remote.md, modules/saml/lib/IdP/SAML2.php, modules/saml/lib/Message.php
Closes #1376 
Closes https://github.com/simplesamlphp/saml2/issues/179
=> Configurable symmetric encryption algorithm

lib/SimpleSAML/Utils/Crypto.php, tests/lib/SimpleSAML/Utils/CryptoTest.php
=> Do not allow the password hash to be used for authentication.

modules/saml/lib/Auth/Source/SP.php
my first PR on github, but change should be easy to understand.
=> typo in 'WantAssertionsSigned' in SP.php

lib/SimpleSAML/Compat/Logger.php, lib/SimpleSAML/Compat/SspContainer.php, www/_include.php
This removes the circular dependency between SSP & the saml2 library and allows us to merge #1441 without breaking the build.
=> Import saml2 container into ssp

docs/simplesamlphp-reference-idp-hosted.md, docs/simplesamlphp-reference-sp-remote.md, docs/simplesamlphp-upgrade-notes-2.0.md, modules/saml/lib/Message.php
Closes https://github.com/simplesamlphp/simplesamlphp/issues/1407
=> Conform SAML2INT; check AuthnReqsignature unless specifically disabled

docs/simplesamlphp-changelog.md, modules/admin/lib/Controller/Federation.php
FIX Invalid argument supplied for foreach() when there is no contacts in metadata of a service provider
=> FIX warning in FederationController

lib/SimpleSAML/SessionHandlerPHP.php
=> 1.19:  Fix php session handler

lib/SimpleSAML/Database.php, lib/SimpleSAML/Metadata/MetaDataStorageHandlerPdo.php, tests/lib/SimpleSAML/DatabaseTest.php
Closes https://github.com/simplesamlphp/simplesamlphp/issues/1392
=> Fix entity data size for MySQL

lib/SimpleSAML/Utils/HTTP.php, tests/www/IndexTest.php
=> Alter logics to support HTTP/2.0

lib/SimpleSAML/Error/Error.php, lib/SimpleSAML/Locale/Translate.php, lib/SimpleSAML/XHTML/IdPDisco.php, lib/SimpleSAML/XHTML/Template.php, modules/admin/lib/Controller/Test.php, modules/core/lib/Controller/Login.php, modules/cron/lib/Controller/Cron.php, tests/modules/core/lib/Auth/Process/PHPTest.php, tests/modules/core/lib/Auth/Process/TargetedIDTest.php, tests/modules/multiauth/lib/Auth/Source/MultiAuthTest.php, tests/modules/saml/lib/Auth/Process/NameIDAttributeTest.php
Closes #1541
Also:  https://github.com/simplesamlphp/simplesamlphp-module-discopower/commit/c897ee3abc2128454d92b29890bcb913c6652de7
=> Remove references to defaultDictionary

lib/SimpleSAML/Database.php, lib/SimpleSAML/Metadata/SAMLBuilder.php
=> Bugfix: persistent overrides options

bin/convertTranslations.php
script which shuffles .po file content from SSP-style codes to normal gettext() style msgid = EN, msgstr = XX language files, and back again
=> convert translation to gettext style

modules/multiauth/locales/en/LC_MESSAGES/multiauth.po
"and" was repeated twice in msgid and msgstr
=> Small writing error in multiauth.po

config-templates/config.php, docs/simplesamlphp-changelog.md, docs/simplesamlphp-upgrade-notes-2.0.md, modules/saml/docs/sp.md, modules/saml/lib/Auth/Source/SP.php, modules/saml/www/sp/saml2-acs.php
Make it possible to refuse unsolicited responses
=> Allow to refuse unsolicited responses

docs/simplesamlphp-sp-api.md, modules/core/lib/Controller/Login.php, tests/modules/core/lib/Controller/LoginTest.php
For this move the detection and validtion of a ReturnTo parameter
from the cleardiscochoies method into a helper method so it can
be reused. Also update the dos for this change.
=> Make ReturnTo parameter work again for logout.

composer.json, composer.lock, lib/SimpleSAML/Configuration.php, lib/SimpleSAML/Locale/Localization.php, lib/SimpleSAML/Logger/FileLoggingHandler.php, lib/SimpleSAML/Logger/StandardErrorLoggingHandler.php, lib/SimpleSAML/Metadata/MetaDataStorageHandlerFlatFile.php, lib/SimpleSAML/Metadata/MetaDataStorageHandlerSerialize.php, lib/SimpleSAML/Metadata/MetaDataStorageSource.php, lib/SimpleSAML/Metadata/SAMLParser.php, lib/SimpleSAML/Metadata/Signer.php, lib/SimpleSAML/Metadata/Sources/MDQ.php, lib/SimpleSAML/Module.php, lib/SimpleSAML/XHTML/Template.php, lib/SimpleSAML/XML/Signer.php, modules/core/lib/Auth/Process/AttributeMap.php, tests/lib/SimpleSAML/ModuleTest.php
Instead of making our lives difficult, we should be using the already available `symfony/filesystem`.
Added bonus is that these classes can be DI'ed for unit testing purposes.
Note: I haven't field-tested this change _yet_ and we may want to add more cases.
=> Use Symfony/filesystem

config-templates/config.php, lib/SimpleSAML/Metadata/Sources/MDQ.php
Closes #1629 
Needs testing as I don't have a test-setup with MDQ in place.
=> Replace remove fingerprint-check with proper signature verification

lib/SimpleSAML/Error/ErrorCodes.php, templates/error.twig
Ticks box 1 on https://github.com/simplesamlphp/simplesamlphp/issues/1643
=> Fix error messages

config-templates/config.php, docs/simplesamlphp-advancedfeatures.md, docs/simplesamlphp-changelog.md, docs/simplesamlphp-idp.md, docs/simplesamlphp-reference-idp-hosted.md, docs/simplesamlphp-reference-idp-remote.md, docs/simplesamlphp-reference-sp-remote.md, src/SimpleSAML/Configuration.php, src/SimpleSAML/Metadata/SAMLParser.php, src/SimpleSAML/Metadata/Signer.php, src/SimpleSAML/Utils/Crypto.php, src/SimpleSAML/XML/Signer.php
This pull request adds the ability to load certificate and private key data from the database in addition to local files.
=> Add ability to retrieve certificates or private keys from database

modules/saml/src/IdP/SAML2.php
We only have the means to generate a transient NameID. If a different one was requested, the code would crash because nameIdValue would be used while unset. Fix that we fall back to transient in such a case.
=> Fix fallback to transient NameID when no format available

composer.json, composer.lock
Followup to #1675 
I somehow missed one dependency, so that one was still on Symfony 5.
=> Also update symfony/dependency-injection

config-templates/config.php, locales/sk/LC_MESSAGES/attributes.po, locales/sk/LC_MESSAGES/messages.po, modules/admin/locales/sk/LC_MESSAGES/admin.po, modules/core/locales/sk/LC_MESSAGES/core.po, modules/saml/locales/sk/LC_MESSAGES/saml.po, src/SimpleSAML/Locale/Language.php
Add Slovak translation for base, and modules saml and admin.
Since I've not found any up-to-date documentation as to how to generate translation files, locale files were created manually based on English language files with headers updated partially.
=> Add Slovak translation

modules/saml/src/Controller/Metadata.php, modules/saml/src/Controller/ServiceProvider.php, modules/saml/src/IdP/SAML2.php, src/SimpleSAML/Auth/ProcessingChain.php, src/SimpleSAML/Metadata/MetaDataStorageHandlerSerialize.php, tests/modules/saml/src/Controller/MetadataTest.php, tests/modules/saml/src/Controller/ServiceProviderTest.php, tests/src/SimpleSAML/Metadata/MetaDataStorageHandlerTest.php, tests/src/SimpleSAML/Metadata/MetaDataStorageSourceTest.php, tests/src/SimpleSAML/Metadata/test-metadata/source1/saml20-sp-remote.php
This is basically what you added fixed for 1.19 in #1672, #1673 also implemented for the new code in 2.0
=> Add ETag and check for modifiedness of metadata

src/SimpleSAML/IdP.php
=> Fix: ADFS IdP loads metadata of disabled SAML IdP

src/SimpleSAML/SessionHandler.php
* Fix return type
* Change how static $sessionHandler assigned so psalm can detect it is no longer null.
=> getSessionHandler never returns null

bin/get-translatable-strings, bin/importPdoMetadata.php, bin/initMDSPdo.php, bin/memcacheSync.php, bin/pwgen.php, docs/simplesamlphp-install.md, modules/core/src/Controller/ErrorReport.php, modules/cron/bin/cron.php, src/SimpleSAML/Configuration.php, src/SimpleSAML/Error/ConfigurationError.php, src/SimpleSAML/Module.php, src/SimpleSAML/Utils/Config.php, src/_autoload.php, tests/routers/configLoader.php, tests/src/SimpleSAML/ConfigurationTest.php, tests/src/SimpleSAML/ModuleTest.php, tests/src/SimpleSAML/Utils/ConfigTest.php, tests/src/SimpleSAML/XHTML/TemplateTranslationTest.php, www/_include.php
Happy new year! 
I'll keep picking low hanging fruits while getting to know the code base, if that is OK.
=> Avoid cascading calls in autoloader

modules/core/docs/authsource_selector.md, modules/core/src/Auth/Source/AbstractSourceSelector.php, modules/core/src/Auth/Source/IPSourceSelector.php, modules/core/src/Auth/Source/Selector/RequestedAuthnContextSelector.php, modules/core/src/Auth/Source/Selector/SourceIPSelector.php, tests/modules/core/src/Auth/Source/Selector/RequestedAuthnContextSelectorTest.php, tests/modules/core/src/Auth/Source/Selector/SourceIPSelectorTest.php
Select the proper authsource based on the RequestedAuthnContext in an AuthnRequest.
=> RequestedAuthnContext source selector

bin/build-release.sh, composer.json
Otherwise when untarring the tarball all individual files and dirs are created in the current working directory
=> fix: tarball extracted in current directory

locales/de/LC_MESSAGES/attributes.po, locales/de/LC_MESSAGES/messages.po
Hi!
I've corrected a few German translations, mainly "Heimorganisation" to "Heimatorganisation".
=> Correction of German translations 

src/SimpleSAML/Metadata/MetaDataStorageHandlerPdo.php
=> feat(pdo): add removeEntry method to clear expired metadata

composer.lock, docs/simplesamlphp-changelog.md, modules/saml/src/Controller/ServiceProvider.php
Closes #1812
Additionally the saml2-library has been bumped to reflect the specs requirement on incoming messages;
https://github.com/simplesamlphp/saml2/commit/b4daf21db8dba7dd6c3591286794ce5c9ccc7dc1
=> Bugfix: Set destination on signed LogoutResponse for POST and Redirect bindings

docs/simplesamlphp-changelog.md, modules/cron/routing/routes/routes.yml, modules/cron/src/Controller/Cron.php, tests/modules/cron/src/Controller/CronTest.php
Closes #1831
To do: backport to 2.0 branch
=> Bugfix: do not expose cron-API if it's not properly configured

docs/simplesamlphp-reference-idp-hosted.md, modules/core/routing/routes/routes.yml, modules/core/src/Controller/Exception.php, modules/core/templates/error.twig, src/SimpleSAML/Metadata/SAMLBuilder.php, tests/modules/core/src/Controller/ExceptionTest.php
=> Add support for Metadata Deployment Profile for errorURL

.github/workflows/build-release.yml, .github/workflows/php.yml, .gitignore, composer.json, composer.lock
=> Replace composer-dependency with phar-file

modules/saml/src/IdP/SAML2.php
=> Restore metadata.sign functionality

docs/simplesamlphp-authproc.md, src/SimpleSAML/Auth/ProcessingChain.php, src/SimpleSAML/Auth/ProcessingFilter.php, tests/src/SimpleSAML/Auth/ProcessingChainTest.php, tests/src/SimpleSAML/Auth/ProcessingFilterTest.php
Taken from cirrusidentity/simplesamlphp-module-general with thanks to @pradtke 
Closes #1693
Closes #1766
=> Import the conditional authproc-filters

public/_include.php, src/SimpleSAML/Error/ErrorHandler.php, src/SimpleSAML/Error/ExceptionHandler.php
=> Move the custom Error- and Exception handlers to their own classes

docs/simplesamlphp-googleapps.md
Use config format per https://simplesamlphp.org/docs/2.0/saml/nameid.html
=> Update authproc config syntax

modules/multiauth/src/Auth/Source/MultiAuth.php
=> MultiAuth: Fix TypeError due to missing keys in source array

src/SimpleSAML/Store/SQLStore.php
Resolves https://github.com/simplesamlphp/simplesamlphp/issues/1917
=> [sqlsrv] fix prefix

config/config.php.dist, src/SimpleSAML/Kernel.php
=> Add cachedir-setting and use it for Symfony cache

src/SimpleSAML/Configuration.php, src/SimpleSAML/Utils/XML.php
=> Look for the schema files in the right place

src/SimpleSAML/Locale/Localization.php
This brings https://github.com/simplesamlphp/simplesamlphp/pull/1968 into branch 2.2 from branch 2.1
=> crossport: bring in pr1968 to the 2.2 branch

config/config.php.dist, docs/simplesamlphp-changelog.md
* Remove configuration for removed core:StatisticsWithAttribute module.
* Add release note to tell users to migrate or disable
Closes #1999
=> Document and remove configuration for StatisticsWithAttribute module

locales/es/LC_MESSAGES/messages.po, modules/saml/locales/es/LC_MESSAGES/saml.po
This adds missing Spanish translations and fixes a few of the existing ones.
=> WIP: Update Spanish translations

modules/saml/docs/authproc_subjectid.md, modules/saml/src/Auth/Process/PairwiseID.php, modules/saml/src/Auth/Process/SubjectID.php, tests/modules/saml/src/Auth/Process/SubjectIDTest.php
Closes #2005 
WIP:  only code, still needs unit tests + updated docs
=> Add support for hashing unique part of subject-id

src/SimpleSAML/Auth/Source.php
=> get_class() is deprecated

src/SimpleSAML/Store/SQLStore.php
This pull request makes the following changes:
- Add a new private function to hash string.
- Hash session ID when set, get and delete session from the database.
=> [#2105] Hash session ID in the database

locales/lb/LC_MESSAGES/messages.po
Fixes existing translatiion according to official rulesets (lod.lu / spellchecker.lu)
Adds (most) missing translations
=> Fixes and completes luxembourgish (LB) Translation

composer.json
Hopefully this will get the CI system happy again.
=> allow phpstan/extension-installer

docs/simplesamlphp-reference-idp-hosted.md, modules/saml/src/IdP/SAML2.php
=> Add the possibility to continue if no encryption cert is available

config/config.php.dist, docs/simplesamlphp-upgrade-notes-2.3.md, src/SimpleSAML/Locale/Language.php, src/SimpleSAML/Locale/Localization.php
Closes #2214
Backport to 2.4 & 2.3 release branches.
=> Bugfix: Fix regression in language codes

docs/simplesamlphp-developer-information.md
This could have more information but it is a start in the right direction.
=> docs: add some dev info about ssp-assets-base to help new developers find things

src/SimpleSAML/Store/SQLStore.php
This is the suggested SQL update from https://github.com/simplesamlphp/simplesamlphp/issues/2224
=> sqlsrv update for schema migration

composer.json, composer.lock
Sort of a cherry pick but with a `composer update twig/twig` in there.
=> bump twig to 3.14.0 here too

docs/simplesamlphp-upgrade-notes-2.4.md
This relates to https://github.com/simplesamlphp/simplesamlphp/pull/2270
=> docs: add some info about the new entityid metadata setup from pr 2270

docs/simplesamlphp-reference-idp-remote.md
This is in response to https://github.com/simplesamlphp/simplesamlphp/issues/2282.
=> docs: update from old many endpoint formats to the one now in use

src/SimpleSAML/Locale/Language.php
This is an update suggested in https://github.com/simplesamlphp/simplesamlphp/issues/2305#issuecomment-2472849503
=> i18n: update this message to be less misleading

metadata/saml20-sp-remote.php.dist
fix issue with saml20-sp-remote.php.dist arrays
=> fix double =>

src/SimpleSAML/Locale/Localization.php
i18n: this is just the removal of the mo file loading. The patch looks a bit more complex than that #2330
=> rebase of pr 2330

modules/saml/docs/authproc_scopedissuer.md, modules/saml/src/Auth/Process/ScopedIssuer.php, tests/modules/saml/src/Auth/Process/ScopedIssuerTest.php
=> Feature: Add authproc-filter to be able to manipulate the Assertion's Issuer

modules/core/src/Auth/Source/AbstractSourceSelector.php
Minor update to the recent commit here https://github.com/simplesamlphp/simplesamlphp/commit/5f4a47f32cd7787e845445595da4b33f28f1415b
=> It seems the & should be after the array here.

tests/modules/saml/src/Auth/Process/AttributeNameIDTest.php
This relates to the `toArray()` code in https://github.com/simplesamlphp/simplesamlphp/actions/runs/12343307955/job/34444204125
=> An update to the AttributeNameIDTest for the 2.4 branch

docs/simplesamlphp-sp-api.md
Perhaps here I could reference sspsmall once that is in better shape to help small deployments get up and runnnig.
=> Docs: Clarify that the Simple API needs a saml:SP

docs/simplesamlphp-changelog.md
This relates to https://github.com/simplesamlphp/simplesamlphp/pull/2278
=> Update changelog for removal of cookie during SLO update

modules/saml/src/Auth/Source/SP.php
https://github.com/simplesamlphp/simplesamlphp/pull/2336#issuecomment-2703296461
=> This brings forward the 2.3 merged part of pull 2336

config/config.php.dist, src/SimpleSAML/XHTML/Template.php, tests/src/SimpleSAML/XHTML/TemplateTest.php
Add configuration that enables/disables twig template debug mode
=> Twig_templates_debug_mode

docs/simplesamlphp-reference-sp-remote.md
See this thread: https://groups.google.com/g/simplesamlphp/c/qL1VSnMyj7k/m/uWaSvCamAwAJ
=> update the list of encryption algorithms supported

modules/saml/src/Controller/ServiceProvider.php
This is a reversion of
https://github.com/simplesamlphp/simplesamlphp/pull/2278
It has some issues with running SimpleSAMLphp as a bridge https://github.com/simplesamlphp/simplesamlphp/issues/2435
=> Revert Destroy session cookies on logout #2278

locales/id/LC_MESSAGES/attributes.po, locales/id/LC_MESSAGES/messages.po, modules/admin/locales/id/LC_MESSAGES/admin.po, modules/core/locales/id/LC_MESSAGES/core.po, modules/cron/locales/id/LC_MESSAGES/cron.po, modules/debugsp/locales/id/LC_MESSAGES/debugsp.po, modules/saml/locales/id/LC_MESSAGES/saml.po
This PR is the result of running a commercial AI translator tool over the Indonesian translations file, and then I had the result of that verified (line by line) by a native Indonesian speaker (ie. a real person) who works for our company.
=> Update and improve Indonesian translations

docs/simplesamlphp-reference-idp-hosted.md, modules/saml/docs/sp.md
Link to the relevant section in both SP and IdP hosting sections of the docs.
This was raised in https://github.com/simplesamlphp/simplesamlphp/issues/2447
=> docs: add some information about metadata signing

locales/th/LC_MESSAGES/attributes.po, locales/th/LC_MESSAGES/messages.po, modules/admin/locales/th/LC_MESSAGES/admin.po, modules/core/locales/th/LC_MESSAGES/core.po, modules/cron/locales/th/LC_MESSAGES/cron.po, modules/debugsp/locales/th/LC_MESSAGES/debugsp.po, modules/multiauth/locales/th/LC_MESSAGES/multiauth.po, modules/saml/locales/th/LC_MESSAGES/saml.po
This PR is the result of running a commercial AI translator tool to generate some baseline Thai translations, and then I had the result of that verified and heavily modified (line by line) by a native Thai speaker (ie. a real person) who works for our company.
In her words "some parts [of the baseline AI generated translations] still feel a bit like there were written by AI, which can make them sound a little unnatural in Thai".
=> Add Thai translations

src/SimpleSAML/Session.php
This was raised in https://github.com/simplesamlphp/simplesamlphp/issues/2482
=> Always clamp the expires time in setAuthorityExpire

config/config.php.dist, src/SimpleSAML/Utils/HTTP.php, templates/post.twig, tests/src/SimpleSAML/Utils/HTTPTest.php
Improves user experience during cross-site POST when the SP is slow or unresponsive, which previously left users on a blank SSP page and suggested a failure.
Introduces a loader and explanatory messaging to indicate the POST is in progress and set expectations.
Accessibility considerations were incorporated and validated using the WAVE browser tool.
=> slow post ux improvement
